<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Design</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a5389b5b-aea7-4e3f-ad2e-4a85d9e6fb6c</testSuiteGuid>
   <testCaseLink>
      <guid>4699260c-5aa7-4cfa-92b2-b763add0b9bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/Base-Small - Default Landing State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c750a9-8ac1-492e-a4b1-0cea38bbd99a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63426c1e-1621-42b4-9924-f0debc6d3fe6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/Base-Small - Select Story Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19664672-b613-406d-82f8-065686484877</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>956a95c7-8fda-4dc3-bc45-fdecd12eceaa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/CTA - All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d428fa6-5404-4820-a3fe-106eaad10dd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>959e728f-711e-4358-8e55-e1ae264beadc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View More Features Drawer - all elements display properly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab58a8f6-6cb1-4b71-a882-925d65ae75d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d4f383e-5764-40a7-8c17-427ef1b93262</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View More Features Drawer - carousel when 6 or more features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6685570f-341e-44d3-ae29-b0cd81de041b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67bd5fd2-fb0d-4d1c-a87c-d09a593e653f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View More Features Drawer - collapses when accordion header is clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3762a441-43e4-4815-b568-737a47d3c688</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a1ec05f-04ec-4e17-8795-3c49db1729e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View More Features Drawer - expand accordion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e238b54-0e00-402a-92b1-b1e63861ff1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>002cd17d-affc-4e75-9eb9-ee8f9fb614b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View More Features Drawer - hyperlink text in body copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35cf7eec-ab13-41df-b701-6375b7d5626b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
