<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divider</name>
   <tag></tag>
   <elementGuidId>74ffe35c-776f-4359-8ff8-f2d56bdaaf56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[spacing=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
