<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>desktopVS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7b87a37f-e215-4c4d-9f45-d1cf1527590a</testSuiteGuid>
   <testCaseLink>
      <guid>24c4ddf1-0fd1-4704-b838-a6f283af32a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04419f1a-b01b-4591-890c-6a342dcb282c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3b22005-7d25-45c7-97ce-4b91ab7ce876</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - hybrids</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eb67622-8ea5-48da-a97d-3fadd24936ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1975e626-66f4-4eeb-b485-be4950e7ec93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de679600-39f0-44bf-b9d8-0d8da64c2d56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ba80b40-e68d-4d88-a314-8889fb02b53b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - sedans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d9f1fce-3be1-472f-9b7a-f2c577bb78f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36573527-51de-4c57-8779-420356dd4e60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - SUVs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3478e216-8176-445f-9d5b-733b2984ec88</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
