<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HeroSalesEvent</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e3cc1b05-fbf7-4d7a-969e-f2c6ce6ba0e7</testSuiteGuid>
   <testCaseLink>
      <guid>8d75300f-723e-455e-aa2d-63f9bd4e6853</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Hawaii</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29ba53c-1ede-4672-a25a-b1a17f4fa170</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08496ea1-c46e-4989-b94b-20909c33d538</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Puerto Rico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cec357-0398-46d6-b8d0-ea2926f7f2ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7147ef3d-88c6-4968-92f7-6cd5e6c4fd0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared ZIP code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65366c90-75a7-4d00-89e7-f9462ed0c4be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21014a17-7516-43b2-be37-d4e9b2d69059</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Technical Difficulty Server Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19ec1f04-26d6-4f7a-87c5-46cde55668f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4755f35-8901-47fb-9a14-a2db23854472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/UI form Validation (invalid)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb8bf3e4-c125-41d4-b8b8-da389ed43e83</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abe25c00-4784-452f-ad7e-55fe9f485cbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/UI form Validation (valid)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc3d28b-9ff2-4bd5-b87e-35f943258a0a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6452f49-f83d-4691-ac0c-5913ac6c5e63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/ZIP code field visible at all times</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d9cd7d4-ecb3-4ef6-8a2c-4a75c363b33b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>156fd543-4a58-4849-adb4-a8f078ecb3d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Unassigned ZIP - Expand search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77c5e6bc-13c7-4e51-a029-fe2c37178c4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8d24c22-3dd5-416e-900d-f87d24a8f568</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Click EXPAND CTA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0be07dcc-f7b3-4a6d-9051-bc5f67741151</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>580b5c90-7a26-4312-a1b3-3d78f836d317</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Click EXPAND CTA - Invalid ZIP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ebce967-ce71-488e-ae2f-b5ba645e0f71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c600280-c34c-4b9d-853b-589eee8d5d64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Expand - Enter ZIP code 58102</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5f1caeb-d8a9-432d-b08d-24b06ba4fd2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ac94af4-3059-474f-a995-04d5ac0675c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Expand - Enter ZIP code 95730</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f5da9e-1b39-449c-812f-99be218c8b45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9e35d44-4056-4b18-80a9-d24632046d45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Expand - Select Dealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43253014-483c-4b25-9e3c-174709d72442</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7454118d-e753-421f-99fe-d333a2dc3ce8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared Overlay - Change ZIP code CTA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7be4900b-5edd-4178-8ee3-6e1d4688144c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f855393b-fce2-417a-ad5a-585f185a22e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared Overlay - Click X button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04627fa3-ff07-4505-b6d1-9ac78574f8a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0235634e-3a9e-48cc-8db5-ace51ce91116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared Overlay - Enter shared market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6257bc85-09b4-4ad3-aa8d-0bb27cc37dcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>557f9258-d17d-4904-8f1a-47df2635daec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared Overlay - Select Market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dd1b93f-34ad-4f34-b640-1eec592e5599</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>435af2d2-6c06-4e28-ab56-7382b7b22b95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Shared Overlay - Hover over options - desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4653e555-330a-4b92-8812-5efd348aa8ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc6b9e5e-fc57-4bf4-92e8-6363f74350fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/ZIP change</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b34c24-13ac-4ac1-b9aa-72e249bc8fd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d28c6fc-c830-4116-8a6b-3d7e011621ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Offer Cards - Offer details drawer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a13d115d-3c8f-4add-8a23-ad3c2fb42f20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9dbca3aa-5e0a-4005-a095-debd01e43f2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Available offers display when ZIP code is entered, and other content is unaffected</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54370857-76fb-4205-80a9-59846ad7a278</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c10e9351-a4c4-4ff9-8f91-56faf7b027a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/Offer Cards match displayed model series-year</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a69e468c-5da1-47b8-b325-229e7b53c9ab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
