<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HeroOffers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b884ebe3-8896-426c-8196-0515f0e94465</testSuiteGuid>
   <testCaseLink>
      <guid>ebdade1c-a826-4ba1-91b1-847cfbd55521</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/hero offers display based on entered zip code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ae7309-c5dc-45e8-8f35-baa6cef9f715</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8abe67f4-dca0-4069-91d2-b183f21c9fb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/hero offers display for market selected in shared zip overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7b8077f-3e7d-440b-9c79-6ea95f105087</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b88fd26d-5f00-43a7-badb-8ce3417bd343</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/invalid zip code validation for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88c2af10-c728-4396-83d2-dcbd57004f48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33ec06b1-ca12-4f94-b6c8-aaa6acfef248</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/market LDA title for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8600d10e-55e9-4ba8-a499-c910f802ad6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93a29bcc-9f39-4019-a01d-37ec56e29327</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/shared zip overlay for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>914869ca-fd3a-4d64-920b-02dbdeaff423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e76f4ca5-d8e1-4676-ada9-ddb5c142c592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/tooltip displays hero offer details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26fabb99-22dd-4dd0-83fd-444d2844d83b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3994e506-4865-435c-8752-35276f532e34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/unassigned zip code validation for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c11d423f-8720-424c-86ee-8c87fe288046</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f25e446-1c2f-4601-a03d-6a9b9e0610eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/zip change for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b34c24-13ac-4ac1-b9aa-72e249bc8fd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e406c24-8cdc-427e-a236-4f80e8c5d657</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/zip code character cap for hero offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9351a19a-8c1d-418c-9eb3-f2827635fa04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6190a315-a1d1-4c11-a0e3-878a967d75ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroOffers/ZIP code field visible at all times</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d9cd7d4-ecb3-4ef6-8a2c-4a75c363b33b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
