<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3d0e66a5-d2f8-4633-93e9-0142438f88e6</testSuiteGuid>
   <testCaseLink>
      <guid>e4ccc321-a49d-4dcf-b53d-c43060b525fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/1-2 CTAs present in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d313fa6e-b3a3-4b90-b24a-558ab8723b0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b33de967-80c0-43be-b850-d09e17b087df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/aligned text for specs, pricing and CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbd24550-079a-4e9c-ad66-db240ed522b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce60ba25-d5e6-416c-bbfa-a99b6a6446ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/correct hero specs for displayed model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3a080ae-48d4-441d-a3a3-a1388ca6c356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0943dfba-d418-4ea9-a140-3f8490f4fe8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/hero supports image and video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0a56df3-3d9e-4e3a-8bff-9cf9c57443ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e96084ef-9884-4f1f-94bf-99e1d6be832e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/Quick Links are visible above the fold</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bd39e4f-bdac-484b-af54-7c6fd4fc656a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
