<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero-QL-DM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3d0e66a5-d2f8-4633-93e9-0142438f88e6</testSuiteGuid>
   <testCaseLink>
      <guid>e4ccc321-a49d-4dcf-b53d-c43060b525fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/1-2 CTAs present in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d313fa6e-b3a3-4b90-b24a-558ab8723b0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b33de967-80c0-43be-b850-d09e17b087df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/aligned text for specs, pricing and CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbd24550-079a-4e9c-ad66-db240ed522b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce60ba25-d5e6-416c-bbfa-a99b6a6446ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/correct hero specs for displayed model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3a080ae-48d4-441d-a3a3-a1388ca6c356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0943dfba-d418-4ea9-a140-3f8490f4fe8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/hero supports image and video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0a56df3-3d9e-4e3a-8bff-9cf9c57443ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e96084ef-9884-4f1f-94bf-99e1d6be832e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/Quick Links are visible above the fold</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bd39e4f-bdac-484b-af54-7c6fd4fc656a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9700558e-c386-428f-91ea-285102091fd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/asset disclaimers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8125fd70-6d6a-4a0a-8216-25ff769a57d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1aee6365-2b35-46ad-831e-82d01ab386b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/asterisk disclaimers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da389d0f-ea6b-4493-b0a1-0b1483a71e8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c4b6cd3-c249-49ae-8bc7-120356f172b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/carousel for additional hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfca16e6-24c2-4e94-bd88-7358974c60b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e956c547-b324-4dce-aee8-6c638835f7f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/HeroModule/clicking stops hero carousel timer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a9a2be-b4fd-40ec-98aa-9cdf161675c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63e96688-7c74-4336-81d3-6e67f1a85122</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/QuickLinks/BYL, FAD and Offers links are present</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c8b222a-6a6a-403e-96f1-2238f075d882</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>024a5125-93b5-437d-830d-7396d26bfe1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/QuickLinks/Increases opacity when a user hovers over an icon</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b259079e-c4ae-4677-8514-de5791a0d573</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b61d734c-479d-47a7-a204-50c8fc77779d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/QuickLinks/When a user tap-clicks on an option icon or name the system shall navigate the user to the target location</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3342b0b5-cba7-4436-a4f7-ca535666ff7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>076bb977-60e5-4d39-a715-fd80751b9186</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/DividerModule/Divider line is shown between modules</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f45559d4-aff9-4dcc-b3f4-b1cbb907f583</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
