<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MB-VS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f2adb840-6443-40eb-af98-3bab3675fa40</testSuiteGuid>
   <testCaseLink>
      <guid>8fb144c7-cea4-47c0-a1ba-bf148e326f88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/MessageBar/Module links to functional URL, and has a rollover state</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb818632-7a1a-4543-9b6f-ac2efbf40cfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2732317d-4fc7-475b-ae33-c32732ac21ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/all vehicle segments clickable in vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ec398b2-4bb1-4bd7-9d5c-23e0de55e674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36de8cc7-4fd8-4bbc-87c6-ef7ba240725a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/clickable vehicle selector thumbnails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>587ff40d-9d81-4d2e-bd84-9c7215b71476</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c32c4f7-5bbc-4f64-bbc6-cb9d996807f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/Select Vehicle - correct prices are displayed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85def622-c9b3-4a06-b9e6-7b7fe99cb690</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>227ed72c-7db7-443a-ae7d-54bbcf70471d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/Select Vehicle - color swatches for selected vehicle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0682d5c-3edc-49d9-a6ce-0acf028c9fde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85b0fa33-0ffa-442a-a42f-eebf502615f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/Select color swatch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e848b825-cee8-4160-88bd-8f67adacd574</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55435bdc-bae5-4264-9f0a-b0f85c1adac7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/Color swatch carousel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd22425e-5ef8-4141-99a4-828aa8c6339e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b89002d-3982-4b2e-881f-62adb02b2406</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/Navigate models - Save users selection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94ffc9a-9ae3-4fed-8bd7-3eec85e97d20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a97249a-4e9d-439a-b82f-bd19eb169d79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c7cd174-8b6b-4502-98e6-68caea03bab2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
