<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tiles-Grid-MB-VS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f2adb840-6443-40eb-af98-3bab3675fa40</testSuiteGuid>
   <testCaseLink>
      <guid>f5cb21dc-6b9e-4937-8590-104656115e40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/ContentGrid/Images and CTAs are clickable-tappable, and update on hover</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe38b4f-c924-48d9-9e4b-422d068134ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdb7a26d-4d55-4217-a511-bc9603b6bf35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/ContentTiles/Images and CTAs are clickable-tappable, and update on hover</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ae4a3c9-edc4-4d14-858f-21a5f2f32f26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c60a350d-37df-43c3-80bc-c93e5c7fa9f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/ContentTiles/Promo carousel for 4 or more tiles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721d3f12-e8ed-4df0-beb6-ed85c02c9b1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fb144c7-cea4-47c0-a1ba-bf148e326f88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/MessageBar/Module links to functional URL, and has a rollover state</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb818632-7a1a-4543-9b6f-ac2efbf40cfa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
