<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VehicleSelectorPersonalized</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7b289f3a-1c7a-4af4-b1ac-7eca242108b9</testSuiteGuid>
   <testCaseLink>
      <guid>114bc099-5449-412e-9c18-3790248be9f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - ES PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817576b9-8af6-4398-8443-bed3e9f499de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe71a658-ee6b-40e0-a4e6-bacccf0b345d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - GS PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>978bd7ac-1a18-49a4-aa7e-59462c39b558</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d65697b5-2488-4d65-b1fc-2c5aa224d6f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - GX PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8123aa97-abf7-4011-bc56-4aca9048c543</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d48d465b-ffb3-49f2-a425-f4a31b7102fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - IS PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b178cb7-0182-4e91-b837-0ca7d3116123</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a7ab87e-02dc-47a0-9e22-f8edc9560a50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - LC PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35cf7c31-df80-46bf-b3ae-64dfae62fb00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18e5791c-54c9-4508-92db-14451789f7b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - LS PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a2b8f6e-8c6b-427c-bffa-ecc37eb6958b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24dd1b08-1c89-4d10-8b28-9420b6e28fe4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - LX PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4a6a16c-5181-4260-a47e-f36fc170783a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df7fbd7b-2874-4e80-a593-465e8a826a17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - NX PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83338ef2-320c-4df9-9474-28f39902ff38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d378cdf-2ac7-488c-8021-e08e35266821</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - RC PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03710b45-1eae-4087-a605-4d6df8fe8285</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0b509f3-2089-4c4d-9bd2-b2ffc49e3342</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - RX PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e5f8bf-8ac4-493d-8d36-528b9935800a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fac21ebe-a5dd-4b61-9bad-c657a3cc177a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/personalized vehicle selector matches users segment-model - UX PMOI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ccd1490-4477-4a55-a13c-5bf25563e483</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
