<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VehicleSelector</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1cc9bde9-7c5a-4efc-9f82-dcaabbe99d3b</testSuiteGuid>
   <testCaseLink>
      <guid>f8b3e5f4-ef10-441c-87de-923b0f4a8313</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/all vehicle segments clickable in vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ec398b2-4bb1-4bd7-9d5c-23e0de55e674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0075c4b-30aa-4b39-910b-491768a7c73e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/background image for vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a15271-f520-4acb-8c1e-28e64fe93a5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c73aaa99-75b0-444c-a0b6-9fcfe3538252</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/BlueKai personalization</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c58a1e2f-4287-4062-927d-e60fbc5c5a08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>431b11b1-272b-4d82-9519-902e09b40c01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/clickable vehicle selector thumbnails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>587ff40d-9d81-4d2e-bd84-9c7215b71476</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6b76ecd-299e-4efa-97ff-efdcc0ed7b8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/default vehicle selector category matches hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc8c8fa3-b531-410a-b60f-5fa4a69bbb34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce6df172-f811-4d40-b189-af463ff3efe5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/different image-video background for each vehicle segment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1765a01e-cfac-41c7-9ed2-74194e05bc54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7ded6a4-c4f0-40a6-84fd-d14da47c73fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelector/nav arrows for 9 or more vehicle selector color swatches</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689be816-9f6c-4a8b-9a70-ad7380c9b538</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
