<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VSSalesEvent</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>573771da-fc19-43fe-8d16-b6a4c5a569f2</testSuiteGuid>
   <testCaseLink>
      <guid>ad4d0a4c-6a0b-49ba-8724-ab46de0117f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Unknown Location - Offers Module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d440b7d6-516f-48a7-9e8e-fd5420a305af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d97073b-4492-4368-a28e-ee65631a4785</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04419f1a-b01b-4591-890c-6a342dcb282c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>024017b8-b530-40dc-b062-98ac3ceec669</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - hybrids</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eb67622-8ea5-48da-a97d-3fadd24936ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>430a7192-1ef2-4e06-a4dc-154a9041bd40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de679600-39f0-44bf-b9d8-0d8da64c2d56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59c22138-79a2-42b5-8243-54ebe004103a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - sedans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d9f1fce-3be1-472f-9b7a-f2c577bb78f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d320ec64-ef9d-4814-b596-5a9e78740c21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offers match selected model - SUVs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3478e216-8176-445f-9d5b-733b2984ec88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22b2844b-5880-4bdd-92c8-e73927340456</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Default-Location-Known - Offers Module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc72d472-acbb-49e3-8100-a42dae8a7984</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66a362df-9260-443f-a97e-06b37dfeb34c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Fewer than 3 cards will be centered in module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f2e72c0-50a1-406b-a101-95736a7c5e13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84c868eb-3e17-4b06-9c30-3b93883b209a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/Offer Details drawer displays vehicle selector offer details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ee8f98-5f15-4e0f-b7e6-a2116ca82d4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a31c686-575d-44ba-9377-b1dc55d9188d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/VehicleSelectorOffers/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44bccceb-30b7-434a-b26a-55d0ae3dd924</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
