<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ca1874e7-dce4-49b3-9463-98845235dc0b</testSuiteGuid>
   <testCaseLink>
      <guid>0dabb736-be2c-477f-848b-0edac9a72731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7abf3385-f1d0-49df-ab5c-8eac06d4b547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1faec40a-58f7-4a45-9a27-f2531b41c408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d9aaef2-bd2e-4381-8ebc-ae6550eccc41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>418082af-f5dc-4251-b48a-21786d00e3f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fae6584-dbe4-4fe2-8c60-b2301c4aa6f9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
