<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Subnav</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>de3a1a61-2295-4992-934c-7b6b185a1c6d</testSuiteGuid>
   <testCaseLink>
      <guid>7578054f-cd4f-4371-bd42-0d260da8749e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Desktop Navigation - Click BYL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb261c15-abb1-4d96-b4f8-412734e718c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f9fddb6-08e4-48ee-a561-deea73307c11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Front End Routing - Clicking link on same page shows overlay or scrolls to appropriate section</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c043e21-ee4d-4a09-9109-05ea7ea76a11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>147862be-80a9-48e2-8576-eeaf878cea7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Design</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c520386-ad19-407f-8dad-e21ccf772e79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa712c7d-323a-431d-ad70-65645c2f8a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a42166f-1daa-4d76-8161-466eb665d030</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2380b799-84d7-49ae-9712-ef49972c9649</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eaf3803-ecc3-46ad-a844-966664517a5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2148f91a-6ac7-49d8-9ac7-40b1973f5954</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27a1312a-a0fc-4c4b-a2e4-6f8977b0b273</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfc9cd1e-d09f-4216-b12c-a2333a14ea31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3ddf2bd-7e4c-4b88-96f9-46a3464cf269</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f13f7ba2-3849-4cb9-a7aa-8c16d8e5cb1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Technology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d49290e1-001e-4d0e-8ff0-8f26894b5f45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>783ce7e5-307d-42ed-91f4-2f03ad8577a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf7eb94f-2dff-4e77-95b5-4d912a2a2f5a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
