<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Technology</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>52fa1a27-2c81-42f0-b7c0-18cfa4768bf6</testSuiteGuid>
   <testCaseLink>
      <guid>07fb4d30-d4c0-45df-9789-3687e46f4c1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/Base-Small - Default Landing State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59054045-5b04-4da1-be56-3ddd19751184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b90a841-6786-4f26-a3fe-c0ce49749fcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/Base-Small - Select Story Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a09262b-699b-469f-8661-75e605b93d2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>448b797f-a6bf-47a5-8468-d547c689fbf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/CTA - All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99cb281c-702d-4f68-abf2-17d683ea2ef0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f08d2157-6dc2-4efd-8f0c-a424b602e153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View More Features Drawer - all elements display properly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>950c7fe1-32ec-4e93-9393-164873ce1adf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c62df6d6-765d-4012-b573-8af85d803346</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View More Features Drawer - carousel when 6 or more features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>771bd0e4-0b8f-47b3-b6b2-f16cc4c5d276</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f67042dd-db27-434d-ae47-4341f7936e60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View More Features Drawer - collapses when accordion header is clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>513b4d48-69d5-43a4-9aff-790c9d7576d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8eba686-443f-4b37-b133-a22dd8c98af4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View More Features Drawer - expand accordion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eefc371-2a3d-44b8-b6ee-9f6bf7403e9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba5f93f7-afef-44e1-aa95-ec168c19fee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View More Features Drawer - hyperlink text in body copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9cef5fd-5285-48f1-85f3-1001540670a4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
