<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8da873b3-c712-46c2-937f-9c362ccc0bd4</testSuiteGuid>
   <testCaseLink>
      <guid>c36d984d-5cb0-4d19-a8bb-4ad88e5aa9dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/ZipGate/Default State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fda3463f-cfad-4fcb-80d7-68cb8044b9c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bacec73-d7a3-4935-9c47-2c63eb7f1bdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/ZipGate/Form validation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>853be7e9-4b4d-4d8c-abcc-2622d9d26372</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d618c155-e10b-484a-9102-a55d4cef1553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/ResultsModule/ZIP code based result</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc0d8388-e0eb-49fc-8fa5-083ed6f92935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c675138c-dd00-4ff0-98e7-dc9cddf679e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/ResultsModule/Click more dealers CTA - successful search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>700b2eb5-241a-4206-a38d-a00e30ee4913</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5b9e762-c400-4f10-a4e9-017c895cece8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/DealerDetails/Page title</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87655d90-e708-4fc4-aeb2-a3fedbf639c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>111b77d6-f518-42c7-a06a-d9a6a1dc2ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FAD/DealerDetails/Contact Module - Sales Column - Dealer Inspire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6714400c-6422-42ea-9c7e-8b18f4c6c8c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
