<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Design</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b25a277a-a853-438c-9a56-2b7c2c16b5c9</testSuiteGuid>
   <testCaseLink>
      <guid>897c1e80-1382-4bf6-bb1a-b8f3ccbf57ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/Base-Small - Default Landing State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6764b3-5427-4736-83f4-e1e9b73e2167</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa88da6b-c7bb-41e0-9fab-20c9fef8bde4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/Base-Small - Select Story Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b64ca3d9-81f3-40d8-aa1e-78c0c5a90b92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df2f88b1-5cd4-40b4-8e10-3f693359eda6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/CTA - All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>533fd7b8-c91a-4c05-ac52-9fcf76b1ff9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37b9693a-de8a-4a84-bc99-14026cb09bb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View More Features Drawer - all elements display properly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>530c0630-fcee-46c6-a5e3-43c7386e7530</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78186b0e-039a-41a9-a8d5-84fa42a0eda3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View More Features Drawer - carousel when 6 or more features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>599d8cd4-6385-4522-9f0e-6a8015af80dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>209bdc82-596d-46c8-af03-d808d3e87793</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View More Features Drawer - collapses when accordion header is clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd597b60-d45d-459d-82a0-0b814cdccb70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1da92a3-99da-4b30-af32-a5e78e273248</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View More Features Drawer - expand accordion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb8ed14-a73c-4547-8007-6ef110fcad8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f255d40-73e4-49e9-9a49-8b8bc0d9205e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View More Features Drawer - hyperlink text in body copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3283a34d-9110-48af-9862-78d81170cc59</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
