<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Performance</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4f7fb447-4447-45d9-b920-fa250b5da6dc</testSuiteGuid>
   <testCaseLink>
      <guid>f66d91af-d88e-4784-88af-20e38898b639</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/Base-Small - Default Landing State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78fdb529-a55e-4c74-b14f-7692aae6e3a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff018f40-fb16-4fa1-8b0e-70c752e07cf6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/Base-Small - Select Story Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb986be-70ba-4b7b-b730-da4366eff478</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2bddbfa4-3f4e-4222-854f-b5227fcbe434</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/CTA - All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faf8adb3-6e14-4b29-a9a8-da4670fba8d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8694165-53b9-4dcd-acb7-cee92b75cd94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View More Features Drawer - all elements display properly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e3ad21-8c12-4e60-83bb-4947257bc071</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8219488-f63e-4c47-9dc7-ca3ea8b3287b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View More Features Drawer - carousel when 6 or more features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bb33e90-8f5e-42e7-bc68-e7f080701b1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a16096d-0ad9-4e4a-9b47-4343f3e48f62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View More Features Drawer - collapses when accordion header is clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e9b6b0f-b7b2-4cdb-876a-60582cbae16a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94983a09-df8e-4266-bc76-ba14389d09a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View More Features Drawer - expand accordion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>180d6298-ff8f-480c-8f60-85b366bb9422</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bce9809b-5516-4184-b95f-6d91c62f3c56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View More Features Drawer - hyperlink text in body copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17fe76b3-50f9-4f32-8df4-aee8156d858c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
