<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Offers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8220470c-160d-4392-a2b0-cc7f6109ee31</testSuiteGuid>
   <testCaseLink>
      <guid>3522f50a-064f-497b-88dd-d071463cef43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Browse Offers - Change zip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c25332f1-eb96-42df-85e2-e1e45099b44a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3170a6-b9bc-4e5e-a3e8-6e358cd62156</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Change Zipcode - Click Change</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>475390d7-cd1a-4417-a34d-9a6715a4796d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92024952-b214-4a16-a398-d58550c3ca0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Change Zipcode - Submit new valid zip-code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eea3897-0845-4244-88f9-72ea5e34a890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fe901f4-5a71-4acf-866f-199df2e0a153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code - Information systems required to submit offers are not functioning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf07fe67-8c2b-426c-971f-9d96bb9864e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3091bf84-58e1-4dcb-8cc2-aaf18af4dfec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code Unknown location - Enter Valid Zip code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb258c96-596f-417c-a7d3-4b004fae959a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60c9119f-0021-42c2-83a9-38494fd9d7bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code Unknown location - Expand Zipcode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74493d42-93b3-435a-ba76-d21715ba36b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e79dc755-8188-4ab3-9d6a-0fd8d6dec328</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code Unknown location - Invalid Zip entry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fda6c1-5cda-4749-9981-42554196febe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab339866-bdc8-4cb4-accc-a85dfe6ca3ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code Unknown location - Non-Continental US Zip code Entry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ce57fb-06e0-4c4f-aafe-b3366bdedd06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25a48c46-574c-426d-b602-a3fb8cc85733</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Enter Zip Code Unknown location - Shared Market Zip Entry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3c4933f-dc28-463f-9298-768cb91232d7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
