<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Technology</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>501d8f32-06d3-4f55-8340-e1dbc69f423c</testSuiteGuid>
   <testCaseLink>
      <guid>2dae9384-e45b-44a4-bf2c-28cbd3ff49b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/Base-Small - Default Landing State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54b92dfb-5e41-4958-905b-3ec8b3b9f00b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6de0000-5eb6-4ea6-9a11-772039894e85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/Base-Small - Select Story Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769d3341-648c-486d-b917-c266388c10d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>628e8b34-5dba-4227-a9a9-982274588ebb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/CTA - All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e776393a-d7d7-4422-bc2c-86611b9e0c79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d10db737-2a69-4fe0-84e9-c5e546ceb4f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View More Features Drawer - all elements display properly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff1286ca-1f27-446c-97b6-16a093c92556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e6b0c43-c5c6-44cd-bc29-c65a9df21bb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View More Features Drawer - carousel when 6 or more features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>536e8f9e-d6dc-47c3-8305-61fecbbc5333</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aaa6b1a0-425e-4d59-8b8c-cd10fffc424e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View More Features Drawer - collapses when accordion header is clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5b3e98c-4928-40ed-92fd-b58d077d2f17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>699feb6c-45e0-4403-bd53-1a6de849f48b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View More Features Drawer - expand accordion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a395ce4a-cd27-41ba-a017-6c1bf7eebca0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3aa02e4-db8c-49ba-b140-09f2759f7a3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View More Features Drawer - hyperlink text in body copy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>321d5fa4-9f87-4346-84e5-d15f5337a292</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
