<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>201daf57-ceb9-4d27-bd18-fd75597fda8d</testSuiteGuid>
   <testCaseLink>
      <guid>15ef83bc-1482-4fb2-a12b-a7630cea994c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>233bd51a-6d8d-45f8-b478-65f176d4a654</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f46f9e6-23dc-43fb-884a-2c7a32118788</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>068c14f6-6483-4487-b0c9-7f648bdcbcf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5419a223-2b7a-4f64-9ae3-ce8d917e74fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88fa0df6-24e0-40e5-b684-81b58a6337bb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
