<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9cf700f7-4816-4c8f-b916-3802d564811c</testSuiteGuid>
   <testCaseLink>
      <guid>c86ccf70-c752-41a4-bd41-8d62dc3e2d24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19a7de26-4b88-45d6-85e5-7b168af3d87a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11286fbb-ac6c-490a-854a-a55ed8e1dd2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>944bb333-30f6-4916-ad64-001ae9964ae3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>792024fd-f23b-4b71-9228-1abb36ec27cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf97927c-d17b-484a-aed3-47abc57d2059</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
