<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Offers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a9cb6129-3592-48c8-b5a5-9e90c836fc89</testSuiteGuid>
   <testCaseLink>
      <guid>6adfd917-ce9f-49eb-a9bf-927c309896ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Browse Offers - Change zip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1b21900-eea5-4f56-95f7-16fd2afc6143</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>915ff4bd-c574-47a4-b3e3-2b484ca4712f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Change Zipcode - Click Change</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6281c457-8e8d-4562-958c-787cd7a61979</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cea065d2-b957-4275-a97e-1ed19e7af97f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Change Zipcode - Submit new valid zip-code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a22a49f4-97d2-420f-a51b-242d5026e0c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6152c1e0-9401-4aab-a970-2375096703bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code - Information systems required to submit offers are not functioning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aec959b-e37e-4b4c-afb9-c3c633323fe8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be9edbd0-811f-406f-b43f-1821ec6b1556</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Enter Valid Zip code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf3ed4e-5b5b-4c56-ae65-535a4d4d84b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>919f7d88-558a-49e3-938b-d62490a48e56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Expand Zipcode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77f56269-51b8-4075-84cc-3c8de811b1e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bd11cfb-1861-4af9-aa03-dd2236d99ff7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Invalid Zip entry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6fdfa68-b48f-449b-aadc-1cdec060ef56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79f3b1cd-ec6b-48a9-a9cf-cd4ea290e2a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Non-Continental US Zip code Entry - Hawaii</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b801a0b-c3e5-459a-a53f-1ecfd229a79d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47d644d6-5fbd-400c-814b-61c81bd1023e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Non-Continental US Zip code Entry - Puerto Rico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bef37d8-16bf-464f-80ca-c9d2ab9bc908</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a90e6d14-1568-464e-9925-bd10fd42e4d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Enter Zip Code Unknown location - Shared Market Zip Entry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7b9f78-ce78-4373-8e82-23e574f37a42</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
