<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Subnav</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2e307d51-6003-454a-88e8-a55ed8186ede</testSuiteGuid>
   <testCaseLink>
      <guid>ce0f6bc8-f10b-4334-b1c4-0a4350deac8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Design</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cae2255-675e-4df7-a606-b269221604dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1598ce5b-d8d2-4a23-b658-6f5008ec41ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83c98741-7be8-45a2-bd98-a6c5253a561b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3e0c960-2cce-48c8-b761-5a6fa78a038c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca42e1d5-17c8-4d3e-aa81-8e3919735ba7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17b2e667-3bc4-4941-8d45-b639175d179a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c14d85-88b4-4999-9660-81b4da804115</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94626fd6-ff49-4ee9-ad92-0884902d6fa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c101d999-0afc-4f0f-9cbf-ba624734a5ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bccef9fc-028e-488b-82e8-83879da91774</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Technology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07a2256e-e623-4c0e-a8f8-6c6f663cc36d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d969a088-e00c-4ce8-9f99-05f137be793c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Desktop Navigation - Click BYL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7c8e639-1148-4156-8974-a323ca10631b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae1c8145-ac0e-4854-8ba4-0e5b19031cfb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Front End Routing - Clicking link on same page shows overlay or scrolls to appropriate section</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>008d59ed-0fda-40a1-baf4-771a70f42353</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
