<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subnav</name>
   <tag></tag>
   <elementGuidId>82e51e69-3a2b-4057-836c-bb6313146a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id*=&quot;subnav&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
