<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>all</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ce90d0b2-e239-4bf9-aaec-a8320b0bbe52</testSuiteGuid>
   <testCaseLink>
      <guid>aa049475-1c6f-4c2b-97cf-fbac8d8aa627</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a66dca1-630a-4e98-9227-4b51aa5dc2a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad1fea84-a801-41f7-ba59-7a6c1d2cef2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a97955-4662-4eaa-ac57-aa47a0d6a1fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdae9ad2-d306-4db4-8922-7924dbd68936</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Gallery - View Content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba72f90-8a36-4d78-9e30-896adf2e0029</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c030452-8f76-4482-83e3-52c751067bf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Header/Lexus logo is present</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48781c33-d138-4fa4-a31a-20574ed477e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2bb61cf-5d6b-4eff-b284-4d615014c970</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Key information displayed in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c3d7b2-da8e-4f93-abc9-4f85f0bd5b69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ef1eef8-a8aa-4c41-af9b-36e8b031d517</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Press release text link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5f08865-2023-4d91-85fb-e62a214cb95d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf4e61ec-d8ac-446b-8890-fada73a4fcad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Social media overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6900afe7-4b44-4fbe-9ea4-602f48d278eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16f3e4aa-476b-42df-88b4-9bef4e274064</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Stay Informed button opens form overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>036ec222-ceb1-495c-aa3b-eee0cfe696e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aaf7f72b-5111-4ff3-8bd8-e3173d2b0497</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Promo/Select Promo Tile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30d01bf3-aa07-4e0f-822a-37e9b69834ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d34f132-908d-406b-a152-e659c26b2c63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/SignupForm/Close button X</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ac7b3e9-29b5-402f-ab7c-90151da7309c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c5199b0-31ce-4065-85a4-ba28e1e98203</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/SignupForm/Deep linking</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b0829b6-a151-4c85-9446-f7d5cec135c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2db7a3a0-019f-4fc9-85bf-24db04b856da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/SignupForm/Headline outlining that user will receive further updates</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e06d114-0713-44b2-8500-03ac28ed62ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d307724-0e56-4a6f-ad00-bc7793ed6a92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/SignupForm/Information validation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b4b7b67-53df-45f9-9442-e9ca50b83e40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdd67c9c-994d-4d6d-bfcb-0209bb3c3ff4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f8b2d54-1e06-4e0c-9212-4c01db014ebd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
