<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Gallery</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3349f31c-ff89-402d-b9aa-6a6f843ba915</testSuiteGuid>
   <testCaseLink>
      <guid>24b0ec0e-f7da-49e9-82ef-03053894f15a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a66dca1-630a-4e98-9227-4b51aa5dc2a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bb4e2d1-d6fc-4e93-b75d-248632f8cc81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a97955-4662-4eaa-ac57-aa47a0d6a1fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfd5abbb-ed77-4eda-afc6-97de2164ed19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Gallery/View Gallery - View Content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba72f90-8a36-4d78-9e30-896adf2e0029</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
