<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8aee628b-a8b9-425d-8b61-19957340527b</testSuiteGuid>
   <testCaseLink>
      <guid>a18606a1-250d-4432-ad2e-aaf7df7dd455</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Key information displayed in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c3d7b2-da8e-4f93-abc9-4f85f0bd5b69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e73496b-8066-4c79-8a97-c154424076e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Press release text link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5f08865-2023-4d91-85fb-e62a214cb95d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>828af5ca-83bc-44ae-a926-05dd8878c7ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Social media overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6900afe7-4b44-4fbe-9ea4-602f48d278eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8a9b77e-6018-4470-b586-7477a2166b24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-FC/Hero/Stay Informed button opens form overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>036ec222-ceb1-495c-aa3b-eee0cfe696e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
