<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Gallery</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>116e2e33-a67d-4f4c-8d66-0cb604e655d5</testSuiteGuid>
   <testCaseLink>
      <guid>3aa8d77a-45b0-40e0-ad60-2feeac33e975</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aae0c87-9894-42db-85a7-7e0df753442b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba5eab8f-8b26-4128-ab98-aa4a395b6cbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>096f00b3-f2f7-40e5-87e7-f7995bd39c54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e860771b-9ac2-4cf4-8c3b-5e2c6bff4e2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Gallery/View Gallery - View Content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6449281-6989-4008-927d-08f325b29499</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
