<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5ac40e1d-f795-4339-86d7-4b2755f5340f</testSuiteGuid>
   <testCaseLink>
      <guid>5768d443-c5b4-4ebe-9437-e84051861836</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Hero/Key information displayed in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c1d039d-cfc3-4110-bfeb-0e3c88e701c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>717a3761-f6de-4abe-9fe2-ccb7b859ae92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Hero/Press release text link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d6aa1f-871e-423d-abe7-2d81d7ae2417</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72824c09-bf0b-4868-bbdb-8ef2224f0a03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Hero/Social media overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>265e67d8-7054-4fa5-8c25-c27b1435460c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>245c7550-ec0e-415d-bc60-82ce127ce3c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/Hero/Stay Informed button opens form overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2320141f-eb4a-43a2-86b7-3e903d11a7d0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
