<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignupForm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7bf64a51-c72e-4568-917e-088658dbc72e</testSuiteGuid>
   <testCaseLink>
      <guid>df165773-8f4a-43b8-a954-4953058c5c1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/SignupForm/Close button X</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5956e549-5c9c-4344-84ce-1bd669848fea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3ad80fd-cceb-4e7f-8a1b-e93374283663</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/SignupForm/Deep linking</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17f3068-07c7-4491-a209-b1409ef7ca87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f2371b5-4d05-4c5f-bb1e-f553dbe989ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/SignupForm/Headline outlining that user will receive further updates</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31925228-ccc6-424b-89af-cbc56be23c7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f0eb5e3-3e86-4d94-a55f-344229eb5021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/SignupForm/Information validation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>610c9be5-5bdb-4380-a132-2fc5f742fc8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3904d25b-262f-4c26-8c8e-a9e25872cc49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-30/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5272ccbe-87e8-4aab-a6b7-fac2570f95fd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
