<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid module 03 - tile1 image</name>
   <tag></tag>
   <elementGuidId>e78b3d51-d494-4b5e-a981-7655271e7e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src, '.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[spacing*=&quot;block&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id = 'content-grid'])[3]/div/div[1]/a[contains(@href, '/')]//img[contains(@src, 'image')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>.jpg</value>
   </webElementProperties>
</WebElementEntity>
