<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid module 02 - tile2 image</name>
   <tag></tag>
   <elementGuidId>7e2e3f12-8999-4ee4-9655-ec3d64b9ab2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src, '.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[spacing*=&quot;block&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id = 'content-grid'])[2]/div/div[2]/a[contains(@href, '/')]//img[contains(@src, '.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>.jpg</value>
   </webElementProperties>
</WebElementEntity>
