<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid module 03 - tile3 image</name>
   <tag></tag>
   <elementGuidId>9e9b1197-2aa4-4a89-8d77-5f1719c4aae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src, '.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[spacing*=&quot;block&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id = 'content-grid'])[3]/div/div[3]/a[contains(@href, '/')]//img[contains(@src, '.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>.jpg</value>
   </webElementProperties>
</WebElementEntity>
