<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hybrids</name>
   <tag></tag>
   <elementGuidId>725e1115-66ee-4764-8539-e3ffaffbaa72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@data-category, 'Hybrids')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'VehicleSelector']//span[(contains(text(), 'HYBRIDS') or contains(., 'HYBRIDS'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Hybrids</value>
   </webElementProperties>
</WebElementEntity>
