<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Gallery</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1ea4e364-2081-4a1f-82f0-bea61c3bb606</testSuiteGuid>
   <testCaseLink>
      <guid>7e2ae2b5-bad1-4431-a0b7-73a9d477f588</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7a63c25-fb1e-41c3-80ab-832d8420151b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4932572-aef3-47c3-adf8-43dc0988ff00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e1a9135-0b10-40fa-a6a5-1863f8e479ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19efbd92-edca-4c24-9192-72d6f0d55089</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Gallery/View Gallery - view content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>094907aa-4ef5-4310-bc86-0876abda6ff4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
