<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>InformationLayer_Desktop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e08095f3-e2bf-4e3f-b5c8-3cc706c02992</testSuiteGuid>
   <testCaseLink>
      <guid>a0271a73-1614-4e5a-be26-913bacd04a07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Desktop - Add removed model-style(s) to Feature Matrix - Select Multiple Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b9bc13-ff7f-4d5e-92aa-5b36a044a509</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be563dcd-9216-47d1-a05a-8ee2fc2661d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Desktop - Add removed model-style(s) to Feature Matrix - Select One Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee31c0f1-421e-49a4-a765-9aa180543e69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e99f732b-b4a8-471d-9cd1-2100bee4ccc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Desktop - Compare Model Features - Feature Legend</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d31f9c67-8709-4d98-9d9e-f8ad5bc1fdee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf75443f-8869-4b19-8ffc-42e69f4a1679</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Desktop - Compare Model Features - Features are grouped into Feature Categories</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af2156df-909d-4d88-98f4-9bf690078b3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63cb10e2-af86-46d2-9ecd-93f03a4254f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61e3eec6-3d03-417a-9ae7-274b666848e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18229e61-039a-4bbf-9675-b45e30bd627a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Remove model-style from feature matrix - Desktop - Remove model-style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3076d864-8af1-4f0c-8f89-a3f71d773145</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de3e080a-e950-49d3-985e-ce01617cccde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/InformationLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d146950-afb8-4337-b479-6fd5f4149e52</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
