<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Styles_Desktop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>533988eb-0dc2-452e-8840-6d374e27ccdf</testSuiteGuid>
   <testCaseLink>
      <guid>14681300-b1e7-4bd6-b44d-d18767e34a84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/Access compare styles feature (IL) - Desktop - Click Compare Features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e6f7178-cb9a-4c13-a41a-6a1ab4e1e7c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34f66f12-06e3-4caf-ba5f-031adac89421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69d32cf4-baf2-4389-ad47-970346a79f52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1acc102-c612-4bd3-aa8d-d1ad77433702</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/Model Picker - Tabs (Desktop Only) - 2 tabs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08dbb98-8277-4d20-b0f1-839956e602d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df9095a0-fd3c-48e6-ab26-46f6f1d194de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/View selected style overview - Style Overview - Default-Non-Special Edition</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545c1aea-181a-45fe-a700-a3713a26e0f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
