<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ES</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4f2062fa-448b-4ccb-ac43-5530fa6ed28a</testSuiteGuid>
   <testCaseLink>
      <guid>f7a87708-ec66-418b-a829-1fb60145c72d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78439974-a9be-4c58-a0e5-8946894419fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b5f0dff-8ce4-43be-8911-c477f1748ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc92bec-596f-4aa0-8827-96031b5966c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50e900f7-585c-4e53-9741-fd2ce497d345</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6cd9c9a-c0e8-41f7-a8d5-c2385f1b2636</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
