<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LSh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4d580a10-1551-4887-9123-12e063fb6b1b</testSuiteGuid>
   <testCaseLink>
      <guid>b10ac2c4-1bb2-43ad-bdfd-2a6f452f0633</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/InfoLayer/Features - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43e7b4a5-1f52-441a-9ae4-7d435fca8aa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d392516d-d4ad-41de-b1c3-5fc181816760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/InfoLayer/Specs - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5dde028-bb61-4b37-b890-fc49f0520177</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>158d4d68-18c6-427f-a504-c275c43ac278</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/SignupForm/Submit form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47898fbf-afee-44b9-8eed-bbe8c701204f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
