<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>InformationLayer_Desktop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>94091c9a-30b8-492b-9617-16b12463555c</testSuiteGuid>
   <testCaseLink>
      <guid>fea61f5f-eca5-402c-b60d-2f4306dd9e3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Desktop - Add removed model-style(s) to Feature Matrix - Select Multiple Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18265a95-adea-4102-b605-093886971661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4fa9784-5a4a-4c30-a481-6b0f3daec18c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Desktop - Add removed model-style(s) to Feature Matrix - Select One Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2338411-9fb0-455e-8d40-b1ae811ec02d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f6b95f7-7623-4b16-98d2-877cb3b344aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Desktop - Compare Model Features - Feature Legend</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d853821c-2e5f-4f78-ac5c-12130dada959</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3a56c1a-a314-470d-97ee-bdf1f5c4a728</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Desktop - Compare Model Features - Features are grouped into Feature Categories</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>649ba304-518a-47d2-913e-2e4571b80cf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ed2d31d-e188-4118-9a3c-7a4b1031de48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bb3813f-fbcc-4945-938b-95b04a16e984</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ca8a907-1d1a-49d3-aad1-284938e40462</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Remove model-style from feature matrix - Desktop - Remove model-style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad959796-c4fd-46fb-90b3-8669a64241e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a42007c-ac27-4322-8630-c95dfcffb8ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InformationLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a6420b4-299f-4319-a41c-3984f2b1cb32</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
