<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Styles_Desktop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4fe07a35-0abe-4d24-bfe4-5a325e50f771</testSuiteGuid>
   <testCaseLink>
      <guid>ca14aa8c-c39e-4b47-a1bc-5b58e405d7d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Access compare styles feature (IL) - Desktop - Click Compare Features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a9b4ff-a016-498a-8980-30f2c5b880eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e53c76f-0035-4697-87f3-e6c07a3d9412</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ecdefd-9719-48b1-a02c-628518fab69f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61fa9518-baf1-4e32-b7f8-28f7b9b55a59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Model Picker - Tabs (Desktop Only) - 2 tabs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b09c4f0-9f17-4cfc-9c72-a697bd796e21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1cf8aeba-b897-47b9-9809-913d3b9b0ba8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/View selected style overview - Style Overview - Default-Non-Special Edition</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ebd474-befc-459c-ae54-1a700b4fbb88</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
