<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Gallery</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>76b3c45f-c06e-4bea-93fa-8b5eb3d6342f</testSuiteGuid>
   <testCaseLink>
      <guid>9903bc52-3308-417e-a8d5-311dc608902e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d565118-96ea-4454-bcc7-0301fcced9c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d6b6ad7-5791-4f3c-a44e-00a0abded578</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ec3f504-6a71-492d-be55-9eec4513fa22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf687078-efa7-4ce5-aed5-54319ca8570e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/Gallery/View Gallery - View Content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20617062-e165-461e-b5ee-b8bb0cceef84</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
