<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignupForm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>621f613e-a005-4aec-b814-39d8feb4ed9a</testSuiteGuid>
   <testCaseLink>
      <guid>d8460fc7-09e7-4d62-92d5-bd9fb5808b4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/SignupForm/Close button X</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eb2a4ac-2a3f-4cb5-81f7-3654fd83bfda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>672efb08-b195-4beb-9893-921c72ec0c77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/SignupForm/Deep linking</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e1a3ca0-fd17-4904-af6b-b9b70169c9c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10f6f3f7-142c-4942-ac63-290e8ddaf9ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/SignupForm/Headline outlining that user will receive further updates</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>186977b4-b29a-4410-ac81-00e808039e8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb097845-1462-4ec6-96af-58e0d059c8c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/SignupForm/Information validation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5197fedf-6481-4e64-8788-140d7738d04a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6b5ce46-cfc9-4bed-a297-7201f9b6f4e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-1/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58508ab4-964c-49a3-9afe-9e4288f2ff1c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
