<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NonSEHero</name>
   <tag></tag>
   <elementGuidId>724ef0af-c057-4e0e-bf28-273c9d52b028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NonSEHero</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
