<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ContentModule</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>94b11e4f-c845-49ef-9f27-778f37813d3c</testSuiteGuid>
   <testCaseLink>
      <guid>770234f1-5746-43ac-aecb-27e034e7d063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/2 variations of CTA buttons in content module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1dd80ef-8190-49bf-86cd-49bf2497773f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20494adc-c069-4655-9cc5-6b545f6ae8e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/3 content blocks in content module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce36487-34ad-45b7-bc43-231809b7a18d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7ac63ae-9dd5-43d3-b893-19e39e27980f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/clickable-tappable CTAs in each content block</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f94d2359-dde4-4494-965d-4e0026a4b0a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
