<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VehicleSelectorOffers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5c533fc3-41b3-42d6-892a-2b603a19afb2</testSuiteGuid>
   <testCaseLink>
      <guid>007c7ee4-eb54-456a-9837-bb362c44993e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/all vehicle segments clickable in vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b57aa6b-2a71-4fed-93cc-6719f521e31e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40770ddb-aa7c-4dd4-9cc3-04fd802effb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/background image for vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2de3f282-f285-414a-8e38-30c19e554f47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>965eb081-6dab-4bd0-a263-86351aeae5b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/clickable vehicle selector thumbnails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa0fe125-51c8-4d7d-86f1-4d0b3aed77f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50c3d394-c2a3-4c19-8505-ce8861c9fa01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/nav arrows for 9 or more vehicle selector color swatches</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45225ea3-cc75-4f51-8197-e32d25e0e051</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5b1830b-1987-4392-9c1d-59f8f4d4b7b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/tooltip displays vehicle selector offer details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04560770-55de-4cef-9cd6-683e1413848f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c47803bf-8439-44b2-b814-00a188caa3d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/vehicle selector offers display after entering zip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>077b8bc3-fb14-4e16-b134-9164699b216c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3856d93-bcef-4c17-9564-bd5573795cd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/vehicle selector offers match selected model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78f8802-bc8b-4d97-b702-11a09c44c627</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ea6f417-34c3-4716-955e-86129938ebd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomePage/Legacy/vehicle selector offers match zip code in hero module</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a8da24-fd8f-4415-bac2-04753a8f6931</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
