<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Gallery</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5829fb23-03ef-44b0-8d85-d32721ecafd6</testSuiteGuid>
   <testCaseLink>
      <guid>3919b546-1a68-40df-81cf-120706477ab2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Gallery/View Expanded Gallery Overlay - close expanded gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>639784c5-cdcc-4262-be6d-3876a5c900a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18bfd06a-b023-4ade-abe2-47a0cdb606be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Gallery/View Gallery - navigate to next-previous image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9ff2b8a-1fb4-4c58-9156-81cf9e61640b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43f6c193-7a83-49c3-93e5-72b51939ec31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Gallery/View Gallery - View Content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca034ffb-752a-4b95-bfec-4dbf55757c6f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
