<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hero</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bf5e5689-267c-43a6-a40d-3619b1180f23</testSuiteGuid>
   <testCaseLink>
      <guid>44a8f67c-5ca1-470b-997b-9f0ca179b3ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Hero/Social media overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2a3ad3-b4e3-4568-8079-ad99753e39cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ebb1609-886b-400f-81ec-2bdd5df0840c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Hero/Stay Informed button opens form overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c91849b1-1038-4e03-adce-9d273727c133</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af4121c2-3b9d-4623-b21b-2a5de1cf5454</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Hero/Press release text link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1547756-3594-4bd4-af38-7a2a0ab2703c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e4a010f-05b6-4c7f-8d7e-f574a2f9aa8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCV/LF-SA/Hero/Key information displayed in hero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c005786-55f1-43d1-bcfb-5c9c85141c6c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
