<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Accessibility</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>23d4a6f5-b0ef-4980-9da5-1b428063f66f</testSuiteGuid>
   <testCaseLink>
      <guid>0c7c195f-8dcb-4667-91d7-60031f9b0fb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/Accessibility/Copy Block/Headline</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>008294fa-5492-491a-bf74-1e8d40a4ca4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac382eb0-8744-4382-b9b8-66e087fcebaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/Accessibility/Copy Block/Paragraph</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b514d5a-7b00-44ac-b499-6d3392a4bbf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9148bf4-4b47-4c82-be3f-626c9475687b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/Accessibility/Hero Module/Hero Large Promo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c0f49ec-84a2-4e4d-bf01-fedd9cb53b37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0944503-1054-45a2-a59c-76c7280d4a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/Accessibility/Page/Title</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e1910a8-8f2c-45c9-bff2-8be2a0797903</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
