<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>allPages</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1a1cabb0-9328-4090-82ec-283b433b70d6</testSuiteGuid>
   <testCaseLink>
      <guid>993f4c32-9536-4265-b950-e190fa3cb5a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/CategoryPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a70e71c6-8328-423a-a182-0052c7001e71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e6d3cc4-b1fa-4479-9b64-1c1732389931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d4bef6a-62f9-45c4-b36d-8165844411fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed7a5db-03f9-4627-aad0-c10d5861a929</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a8e3e94-65dd-4d59-93bb-63db49510d63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ComparePages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d87ecab0-8a6f-4472-be22-8c1807c50eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d7d658-702d-4a50-8b74-a262bd33b28c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1493015a-db91-4eba-84cd-9b65aaaa38b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d542a5d2-c524-4e49-a5fe-d8170d892fab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be7377d7-920b-47ad-b271-fe71c16ed859</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/DealerPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d2e235-b103-460c-9fb5-bae0857def9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1212466d-3694-4fc2-b4f4-8f0d89364f34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8db085bd-afe9-45ae-b22c-73416806f234</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a0c13dc-2e39-43d5-bb73-097114459089</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48d40a0f-0634-4e5f-ad96-7bdf4bf681b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ErrorPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01308af9-c731-46fd-8167-2aca78d57c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e874cd13-b820-4f4c-94c2-f68edf843c42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eca0b41-4341-43db-b16b-b4bac498b2aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34afbf20-4a5f-4e9e-bd6a-f869e1288a80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbad7109-75ce-4e48-a147-9ada6fcc0fb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCVPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd6b1e14-bd2f-4eca-9e51-e460610aad11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2272d4d7-210c-4b8c-a8a7-bab7088f3e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af7d078f-8126-40ec-818c-f549ffd5e5e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cfdc537-36f9-4b28-9f6e-6da8bfc327d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7983dcfc-d946-4eaf-ad75-9383bd228e1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomeOffersPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecb5c2db-0770-403c-8f41-4eff2bcc5a07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151bd8d0-c29e-4a52-b7eb-8db10717ce0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>100b4af4-b5cc-49ac-b537-5ac291e7e7c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d67bb141-61b0-4db3-9cb7-191aa8f83533</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17f499c7-b4a8-49a4-906a-5abad1a5d72a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/LCertifiedPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2db299c4-be9b-4534-abcc-537d49e37b37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>207330cf-0e30-4e8c-82a3-b84a275b566e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a26b021-fe96-485c-b68f-10afe6695004</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4500f177-c070-41f8-a6df-571e4bc927f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b76e4d84-28a3-4393-bd12-fd2a5e154aeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesAccessories</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a23bab-9244-42f6-a4bb-1eec25f00081</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b2f374d-5dc8-4c42-a8c5-0813d2bf2efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3284a0e9-5dd3-42d2-8dd3-046f462e02fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5768c649-5608-4cc8-bdbf-2dab1c0499dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0c5a1b4-e8ac-49b1-afff-48b358cc1bff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesDesign</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4a17349-1eb2-4285-beef-4dcceae7b678</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b488918-160e-4f73-9c73-df877d39195e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48b61824-fca5-4e04-946e-6377acaec079</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a48d1318-b6ab-4375-b9e3-0827e58c2110</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cba86bfb-0fc3-4bc8-947c-2f64b2d37a12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesFeatures</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a21f00-d245-48b7-8534-e162fbf20e62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df67724-406e-4577-bd4d-96baa9b68643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ac4ec3e-af59-4d88-8239-cfd9e2ba7492</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58f6d77e-0438-4884-b943-c31dc4451a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ec828c4-4156-4014-ba5f-6e2d93c959cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesGallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c828b0a-8552-4ab6-9912-02fbf189939b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d10c7b-2b2c-4e14-a40b-7259838b41fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e928a98-735d-46ce-8011-71436ad789bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd23b0ea-0cc9-41c2-91a4-873ee722b83d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e338f68-9fa7-4c39-815f-583694a2c9bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOffers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c73bb94b-a668-43b1-909d-6017a73c51d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d364ad0-4943-4579-8dd3-50834e341945</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86635f22-e451-4484-aaca-8f58d2a5e3fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a200bae2-370f-4885-a5fa-6abe7b09339f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff06a3ae-cea7-49cb-bc63-04ab054f7685</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOverview</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07be0c1-2e9f-411a-9546-2341c94f821a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78fa11c6-abf2-434b-84b6-79ac60b28895</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b956ff7e-259b-419a-a251-3045fa1aeb4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3f5814f-7f4f-4334-83ea-bda70b8b2725</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52ef4352-451b-4828-8552-1f4300399ea2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOwners</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3eba74e-b26f-4f74-90e7-312b7bd8ffbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45550d0f-48c2-435d-9243-fdfcf9fa19ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6db8b09e-5d27-40af-bf8c-3e3fc1e38712</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3f7e8c-8cd8-46e3-b03d-fa6d458547af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7dd62eaa-b569-4d99-80ec-0d6ee3d22dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPackages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c7ebaab-d731-4f35-b636-ae3a39fcfd6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d338d944-1b8e-4d15-ab3b-76c5867d0752</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae7a5db-6b31-4377-ac26-d66182d27272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94291e63-d709-4c53-bcfe-1fb2d5b6ded1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efd61f92-3123-4d22-9f31-2967b64671e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPerformance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c89c147-5d14-4061-97ed-c042b84d790c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d67b79f7-3fd8-4521-b816-97b8733fc32b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e42a18d4-01f6-48c7-86a5-83541a8a79e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9596ba2d-d69f-4151-97d9-33016199746f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37e05e03-ba04-42b5-aee1-dcc581ef9fce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSafety</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95be0677-9333-45a5-8a1b-274ef9ab9227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5214d594-c73c-464d-a1d9-b50ae082b42c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56bab3f1-b12d-40e6-96f7-11ba23d029f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>518885da-4c56-4258-93f4-1eec11fd4b4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e35af069-3cdc-440a-b23f-a8085b1f1c09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSpecifications</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>747cd64f-cbfa-4bd5-bded-9b59381bede0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fc82f23-d74d-462b-9726-7b5e4e255d0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96fa34c5-13d9-4ef8-877a-09feb1c4e378</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721efdc3-ed11-4ce6-922b-588b192eacf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5aac283-bb0e-415b-9571-235b6a55455e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesTechnology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>212cab4f-6f83-467b-950e-691522ae9835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bc0c49b-ddc1-4ce7-86d6-f8f67500af23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d3666d9-6113-4b74-927f-e13541d88574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19571520-97d3-4c4a-ab59-e8d7ee7e1a14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ce820db-37f0-47ff-853a-087f1e4e958e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/SponsoredAthletes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24bb79c5-12a3-4a86-b86f-cbe1f35fa75b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b96bc7cf-41d1-463a-882e-d3211bf4d6fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de41a67a-27a1-4c0f-ada0-fe94cc56cc55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa624a4-8e3e-40cb-bc1b-9d09270bf077</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
