<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ES</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>807cfafb-c4bd-42f3-9351-da9bc0d28ede</testSuiteGuid>
   <testCaseLink>
      <guid>a608cbb4-d822-4b29-a4ed-af5c1432b1a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b0e87da-97fb-4878-bb62-d8ef8e7fe8b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e74332a4-00aa-49af-8cc8-fd43b1890176</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7b0023e-d232-453e-9c97-b8cfc5bfe3af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ef5939d-ba09-49c8-8db2-e6aaffd31edc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bccfccc3-7c91-45d6-91a5-d91c30a0ea7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0225f9f-adc1-4bba-b2ed-091ee2f31c6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c74f004-a561-4b79-9f41-fbc5a7452c4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7930dff-12cd-48e9-9f8f-dbc9df5903fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>750c1ca0-f847-4cbf-ba14-e80818838b53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fc823e0-892e-4697-a712-7353c61c6741</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15cdcacd-5d26-4805-a474-5c62aa7b0926</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>311cf6d8-b332-4890-ad9c-6e54a738bfa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead5e8cc-33ac-4e21-8dd9-68eaaf6026b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42877922-f9c5-4edb-993f-23862e8dade4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d59ffe-aa3d-4462-bbfe-e27a591cf0ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2ad7bc9-18a0-4cb9-b92b-8cebfad29bbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99941f78-386a-4918-ba51-c63448148f11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93f3d43e-bfcb-4455-ab8b-369d04bf8aff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49d504d9-b9d1-4868-8e5c-3af5cfc6a536</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7a87708-ec66-418b-a829-1fb60145c72d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78439974-a9be-4c58-a0e5-8946894419fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b5f0dff-8ce4-43be-8911-c477f1748ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc92bec-596f-4aa0-8827-96031b5966c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9f59c9a-186b-4f23-ace5-996ad664eefa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c95089d3-4ab2-412b-84b4-e68389968280</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41ebf3a7-7293-4ab6-9c3d-db7d042c1cbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54eca8f9-2b39-42c8-9119-77a5a181990b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfac025f-2449-4588-bd50-0752ce46fe26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2bf8032-7d31-43f0-93dc-d2ee96ef301e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af1b62cc-d8bc-4e0c-a8ba-7f314279740b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2e8ddb-1271-4cfa-895e-324f3b1da737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1e70a39-9782-42f5-a5e8-25ca3800d59a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7138cdf7-708c-4474-948f-b96298380569</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c64cca55-9f14-4f5a-9853-ecf084881c13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29863a99-1a83-4b1a-82a4-b78d7cb7c65e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34107ae5-061a-48f6-83f2-407de5be590c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddf4771d-0cd3-464c-99f2-323f4fe91cf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96624ad0-fb74-438f-a3b6-7af2cbeedd5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>935fc33a-5211-41f4-bdd9-69fa051e8e3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca309d01-4eb0-4a84-a6a8-55d720b95098</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/Correct MSRPs for each trim in both model picker tabs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14808426-6bc1-423e-b53f-c2de2b6316ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fa3652e-c3e7-4c7f-b8af-ad49f15b4110</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed568a1d-e64c-48fd-84f7-a1159f217faf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
