<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ES</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>807cfafb-c4bd-42f3-9351-da9bc0d28ede</testSuiteGuid>
   <testCaseLink>
      <guid>a608cbb4-d822-4b29-a4ed-af5c1432b1a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b0e87da-97fb-4878-bb62-d8ef8e7fe8b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e74332a4-00aa-49af-8cc8-fd43b1890176</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7b0023e-d232-453e-9c97-b8cfc5bfe3af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ef5939d-ba09-49c8-8db2-e6aaffd31edc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bccfccc3-7c91-45d6-91a5-d91c30a0ea7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0225f9f-adc1-4bba-b2ed-091ee2f31c6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c74f004-a561-4b79-9f41-fbc5a7452c4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7930dff-12cd-48e9-9f8f-dbc9df5903fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>750c1ca0-f847-4cbf-ba14-e80818838b53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fc823e0-892e-4697-a712-7353c61c6741</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15cdcacd-5d26-4805-a474-5c62aa7b0926</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>311cf6d8-b332-4890-ad9c-6e54a738bfa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead5e8cc-33ac-4e21-8dd9-68eaaf6026b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42877922-f9c5-4edb-993f-23862e8dade4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d59ffe-aa3d-4462-bbfe-e27a591cf0ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2ad7bc9-18a0-4cb9-b92b-8cebfad29bbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99941f78-386a-4918-ba51-c63448148f11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93f3d43e-bfcb-4455-ab8b-369d04bf8aff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49d504d9-b9d1-4868-8e5c-3af5cfc6a536</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7a87708-ec66-418b-a829-1fb60145c72d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78439974-a9be-4c58-a0e5-8946894419fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b5f0dff-8ce4-43be-8911-c477f1748ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc92bec-596f-4aa0-8827-96031b5966c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9f59c9a-186b-4f23-ace5-996ad664eefa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c95089d3-4ab2-412b-84b4-e68389968280</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41ebf3a7-7293-4ab6-9c3d-db7d042c1cbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54eca8f9-2b39-42c8-9119-77a5a181990b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfac025f-2449-4588-bd50-0752ce46fe26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2bf8032-7d31-43f0-93dc-d2ee96ef301e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af1b62cc-d8bc-4e0c-a8ba-7f314279740b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2e8ddb-1271-4cfa-895e-324f3b1da737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1e70a39-9782-42f5-a5e8-25ca3800d59a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7138cdf7-708c-4474-948f-b96298380569</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c64cca55-9f14-4f5a-9853-ecf084881c13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29863a99-1a83-4b1a-82a4-b78d7cb7c65e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34107ae5-061a-48f6-83f2-407de5be590c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddf4771d-0cd3-464c-99f2-323f4fe91cf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96624ad0-fb74-438f-a3b6-7af2cbeedd5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>935fc33a-5211-41f4-bdd9-69fa051e8e3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca309d01-4eb0-4a84-a6a8-55d720b95098</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/Correct MSRPs for each trim in both model picker tabs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14808426-6bc1-423e-b53f-c2de2b6316ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fa3652e-c3e7-4c7f-b8af-ad49f15b4110</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed568a1d-e64c-48fd-84f7-a1159f217faf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ea31f9f-c925-4a93-9d9a-dbc7c54e334b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c45960d-a20e-4441-a864-fc651a64fa7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62d45f7d-6d77-46d6-b329-aba3bae80cb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7376892e-2657-45b3-9511-610ac7cae0a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>934e3485-629a-4f1e-836e-1994f5552246</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02615a3d-13f1-4523-9293-9f76b6ac8b9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>186b6fc6-1f00-4a88-95fd-954beeb1ca99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd558212-86f4-49b9-ad43-5ed0aab717da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c66f5ce-29b1-40ac-b9b0-349c090ad72c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1ede78f-cb89-4dc8-8133-a7e222d806ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2b5caff-c083-457b-b884-0be51e4fa1f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96ea72e6-9e2b-4d91-8f5e-fa161b798a9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>253a6ac1-be0e-4ba0-8f01-7d114ed3d8f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bccdc954-0251-4c31-84da-2812518006ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b55d110-9b6f-4eaa-b8f7-fddadd789c1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Swatch carousel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13ddf59e-5f55-4911-8611-9bd36e61472f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff962856-da9b-4340-a67c-dfd5d16b30f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd613fb0-a7e2-4d68-a170-d107085210df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fa23ba5-1dad-4be8-8158-f8b9435a60d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a62cb025-ef4a-4f32-9b9f-d540fe6b3f63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a733382b-59f6-48a2-af75-cf2f1a1bfd10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6cd9c9a-c0e8-41f7-a8d5-c2385f1b2636</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e9cf68d-856b-44c2-9ca6-920980319a49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/Submit form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cef6658-686e-4fdc-8120-e4165f3d7af2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54db541f-94d1-462a-9c25-33c60b27e823</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/User opts in to be contacted</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5213ab-8422-4caf-89a0-b1d2f2f9976b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bccb892b-f001-4125-9c19-4d576523babc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Design</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff87cdf-32e1-4081-8b72-3283d5692d73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a6ec6ff-5556-43f3-a67f-e6c36b3a98eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35d1ae9-d68f-4779-86ae-ae8d1ce3e75c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b40869e-166a-4e28-a218-218fa6580f1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Info Layer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94132da1-4323-4dea-8b2d-ad3a18766b7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d552b9b-2aaf-43b7-a376-9a0950be7f38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03ee3cb5-2c4c-4ab0-ae05-9cdf9e58c14e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a53c45e4-fa64-4794-9558-85af1d865afc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c0fa704-5ed1-4ad0-b87c-a2a84f55c829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>131b10f9-1abf-495f-82e7-b7b7a8b9b498</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Safety</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bcbef54-0f5c-4ec2-ad81-32b8bd21279e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcfbed6e-896d-451e-8b04-395741da2e5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0837fb66-3c22-4cbf-8833-c68085539373</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4950c6e5-c281-4528-b9ea-6cd3b50164f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Technology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8eb006-9368-4974-ba69-bb0c6f03f51c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7809d958-adb0-4af0-a08b-3a7a7437dbb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Subnav/Deep link takes user to pre-determined location on page - Visualizer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d1c0d18-83ce-4366-a883-482b659935f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
