<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ESh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d617ff41-acd0-4e58-80d2-6988ae261225</testSuiteGuid>
   <testCaseLink>
      <guid>0f568528-e33c-4fad-933a-ec7dc3f4b8eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f7cad08-1ac2-4298-ba3c-582297a72025</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dba37850-3558-4de6-a5f3-b6aad6655bda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54df3019-1512-4664-8725-2a9c882edf5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca90d03e-91cf-484e-ac9a-c2a88c1f9c95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24897c15-f12c-4df2-967b-ec70acfd7e32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a781e2a-d30f-4d08-89f1-8df09bfd9863</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d97bc7b-88a2-45c3-bf50-e1f71354db28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70d809a5-bed0-4781-a88f-426b0b8b44c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f8828c9-3553-4edd-ad05-aed0b3ea6299</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e652d24-f71f-40bf-8380-3f1c0330ee5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc5f0aa6-13dc-4368-b4da-e7bebc594010</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e3ed5b7-3174-4ee6-b089-d83a6e4eb9ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e553efb4-305d-4fe9-905a-4a8c7c0107e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f98f1178-8149-4223-9ec7-ce5d71f412a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aadd585-e336-44a6-a42c-4f55f72e7169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19ef3864-6e4d-47a4-82aa-b5e42cb4d97f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca61d8af-9193-453f-879b-2f12a8dd9bbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5e08e83-86b6-41d6-bd16-c836edb101a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33771350-850b-4286-a114-ccc4c9b50cff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a6904df-9c4d-4da2-9849-c83833d77556</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742cea41-6119-45d1-9d23-b8ff292ebc01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79ed5cac-85a4-47c4-af19-c72b9ce60910</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa80ec2c-665e-4856-ba10-6718fa3b6071</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b35b2c5e-2931-4027-a6df-b674a6a49357</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58647b40-cceb-4a1c-aa48-7717c4cda8b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd1a06df-4cfa-4dbf-8f80-1baf80c47724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c169c50d-5a6d-4d78-a738-f6a026fe050a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b2ec13b-3e8c-4d28-ad48-1614aba39253</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c0ae583-f7bd-4971-9649-285dbf557a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6b0aa41-1763-4410-b3b9-e8c4b03d35b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1187b1a-cb11-40b5-abfd-54f8115383ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4aeb257b-c0b4-4e3a-a1bb-d47694487c51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1b546bd-24d8-4fd8-bd96-b12ce6424f6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c59dd4a-5641-410b-b06f-ec61cd21af3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab3fea28-7dc7-469c-ba9e-74e20ad4fcbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>141f02de-e363-4884-b862-49ac2bb44c40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57f5f173-9473-4c39-99ad-dca5ccc702fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>caa6330d-9ebd-47a9-bbe2-910352a0250a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b910ef4-f3be-448d-b3e5-507cbff2279d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f9588f9-aa2d-4713-acb9-a1f968e3a2b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Styles/Correct MSRPs for each trim in both model picker tabs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45800dc6-87ef-43dc-b03f-9ec25cddb890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b519095-3d0d-4781-b874-3c989f03a0cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48a9dd49-8a1c-4382-83ec-475fd90ecb68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61a2e64f-e7de-47eb-9ebe-3b09c7ff3bf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a761551-4540-4702-b286-b02020702868</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bec893c-4374-4a6d-842f-0627c6f76cc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adcff62d-df6b-4932-b5ee-f64c74faeb7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc8c6ec1-9eda-4991-aa4b-577b8136d22b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b1bc23-875e-4cb0-aed3-6acbcb02c94f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6e0996a-5d68-450e-ac94-4561b1b4f4e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ESh/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>268bc0ce-02b9-4e40-b779-4939c5fe8efc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
