<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6d9dc143-d7d8-4a4a-a94e-9124fc8b91e0</testSuiteGuid>
   <testCaseLink>
      <guid>86ba8102-1e10-440e-8b52-aa01df891c72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b862bd8c-3c6c-4816-ba8e-e3ecd771157a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2c067f3-49df-49b2-8b2c-64c8a388f204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9120c8c-a8f3-4900-9930-675ccf4d2825</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>600686d7-1b46-42e2-9857-b5a47c950f90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9364267d-e753-4bba-b3d1-3defe469c2d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>564c7fdd-d5df-4253-98ab-96a3b9e90bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64458309-f7b6-4d02-9990-f112fed0c10c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c0457e-bb77-49d7-b1f9-ba45c5363e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c23c6601-4ece-4cd2-b8ce-837d205c986f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f68eaec-7fd2-469e-8142-79344141726f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e3bbaa4-7b55-4cfe-8db4-9f1665e78f2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41c06956-cfd3-4d77-8b5d-ddc1b44433ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be4bc550-6b8a-4d55-a3e0-bbdad070d19e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6f8acbd-4804-4da8-9ffe-119334d98835</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>919ef464-1f22-4644-b4a6-86f64480b62e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>128ac38a-f8d2-4e95-a078-9121f8c16724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2683150e-0589-4ec3-a901-39eee41285f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c98261e-fa48-48b2-8279-ee5c9efcbdc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59735a3c-76ee-4fab-b5ac-d479b2f76619</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1053c8ae-6bed-4fc3-a1d7-346d177c39ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d79a2b9f-f6b3-477e-a9b5-0a791669d4ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7911129-db06-495b-8adf-6be7c09f3ed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d5fb25d-7c57-4981-a71e-5ce038633c0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0934ba44-eb42-4bd3-9c8d-a721dca5aa66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80eafad6-5caa-4ee7-9ff2-00b49909d3db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc4d6776-bf2e-4a1c-bc1a-21989f4a7552</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acafa395-3842-4085-be16-df40bb0ed58c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d87bc0a-0d02-4883-a09e-1ba36c867ec8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fcef3b-2c4f-48ff-bb37-f2fa4733ecbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1d70701-ef6b-4258-98d8-d5146c62a4f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d463e3f3-0ecb-41da-bcb1-287105ab5e46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f920ff53-d09c-417b-98c7-144bf6cd3d4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ff82562-5077-412f-a344-d3fc05a675bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68913c05-082e-4a13-94bb-226aa6ed7ac0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>385471bc-6df8-4a5b-917a-dd9457e497f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28d93559-9f9f-4ecd-8ad5-f19c98e42291</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7f87806-8afc-4a7f-9e0a-532839dad20e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75ae5086-f7ae-46ef-92f5-25b941993cdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aaeda67-0e45-4cc8-a1d0-cbdd11d4ed20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8ff4992-32fc-4424-b754-ff96c32aebe7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b38341c-5546-4356-87c2-4657f6d58ca1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02a2bdf5-aea3-438d-8149-4a393229f1b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145490cd-1f68-4936-ba7c-878997a4d3cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84f0dd6e-8ed8-4345-bb80-5dddce5c5814</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cda0b2a6-1907-4265-a14a-4f9b81a527a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7af481d1-529c-4a0d-a57a-2933bda16fa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d0b16c4-6966-4269-8eef-0b1015a614f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b6b065c-864f-405f-8cf4-366bae9a7534</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d05e1e11-1b95-4387-8f55-97f5422a38be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33d262ad-17d2-453f-a62d-619a54a0dbc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e79e0f50-2777-4f8e-9f57-318e0e29f420</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2480cf18-b644-4353-8b3a-6c700c5ce542</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb1d81b8-a651-4736-8f69-3d4a9e180d22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08894571-abcb-4ba9-a25b-d8260403ca5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>350864a3-2410-4830-af63-f5777bf32655</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca7701aa-bd5b-433a-a4d8-13dc6daf00ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0ed9ea8-865d-442a-9a39-bd8b88d8968a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>907d708a-bba5-44b2-b36e-f2a65f3a4154</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a74590e0-b070-4851-a555-37273543c073</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4482f8e-720c-463f-9a18-f6cbc5f0aa8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab816042-a43f-43ac-9247-9f6924a5c874</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
