<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>IS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5ddb9871-a51b-4403-b435-cf7ae5a6df89</testSuiteGuid>
   <testCaseLink>
      <guid>4e4aa441-4f96-4566-911c-c0409b18ae6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd12abd-ee80-4dfe-971f-f0a815c070bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5ee19b7-6050-4433-be1e-cc9b199e9fec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c380da3d-4d0d-4e79-b7c9-5ac0a0fd880a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd3aa6c9-7596-4036-acdf-91b7b29e162c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>427426dc-a8d0-49d9-93e3-89dcf385fdcf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d81fb92-05f0-4b31-845d-700e020f39d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25829137-dc9f-4335-9ef9-28bdf1480ad4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e898c056-c902-4ad6-ae5d-54c205686272</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89a41f5a-2a58-407d-8f6c-a5ff46d7887a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eccdcecb-74d0-4097-92ac-24f8fa0fabe4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>052e743a-f522-4777-8b7a-babbf9b82056</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73492111-26c8-4cbc-8c52-6e5b3398b8c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>404c1830-5646-4c5a-9524-4ba6521d4e94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>958cc2a4-d2a1-43e8-942c-05bbd2ed2633</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47d50f42-1a2f-4efb-8764-a928bdc43180</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39e5170c-c502-4728-80f6-06c09603daf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>180e6bc8-35c3-4b6f-8894-6d7f11d9428a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>610f3f01-439d-4081-9f7e-b45f78052004</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e9f07c-1b35-4d88-9fa7-215fa7592890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab6951dc-aab0-4fd3-9e4b-3ae38a34207f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>103ae694-8b6a-4350-918c-90a584db34b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7bc4d12-5494-4647-b75d-bbd7b09fd6e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7819ac61-e418-4610-92a8-d4855ad59561</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>475397ce-9612-4dda-9545-81e4ce2d29cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35bdd90-d90d-4c19-acc6-cac2b9b2f335</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68ed391f-6dc4-46ce-bccf-dbcaa14f7f83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ebfdcbd-6a74-44e4-b33b-94afe47de9b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a419706-8dc2-415a-b045-d92eae07b662</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ff5669e-0737-4753-9153-c96378a8c3d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e9c6389-b5fd-4bae-b94d-1ffa7990b799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15e6fe6f-eb48-4858-8eb7-1217fb333e60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d2407d9-f4e5-4b3b-96bb-a3cc6ee18531</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c9dcec0-a376-4cc0-8d15-78c6fe00eaa6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>379efd4f-dca1-4881-80e9-6c98a8a75bee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dde041a-70ea-45b2-b619-92be0db28a93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e279a239-aed8-4504-a251-0bef23754f84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b737d721-320f-41de-b113-60273b155039</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59e932cc-e73d-4fd4-a45a-7d1e8f4e4750</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1490910-224b-4975-abaa-ce98deed8ad3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3aee9ed1-d6f5-45b3-aabe-ab18f3db2d1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc129d3d-512a-4743-bf0f-bccea808d4ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10ec9a53-3119-412d-b3ee-684fbb166f80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4125224a-ab6c-4919-bdae-cfb588950968</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68681c37-2f3c-410c-90f1-4291e6a95392</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d27fd9fe-e949-4a9c-8b07-a9aa42ae5853</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f71cb8c-7d5f-43d4-8499-470d509e5b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37f9321f-8159-4587-ac53-2ff84967ca80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3274057e-a363-4d29-914e-28c8a07e0cac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5dd935e-2b50-42c1-8680-7d3cc19e7964</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8f89d40-5be0-4201-a446-d17496735d25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b25552c7-73d5-48d9-be38-59f8b1594ad2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f58f412-fa86-4ac0-b3aa-2f29b8d4956a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d976ba3b-a109-4515-bea8-0d052d0182ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fea63b65-fe84-411a-ab93-4e9119ae8545</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33ef2544-7173-42be-84c4-14085b464f29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27382480-9178-49e0-9146-5c95e8416362</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95e68116-6387-414d-ae56-72763e8a07b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>582e92d7-621a-42a4-879d-6fdd5bc5cc7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e42d8235-f0ef-4044-861d-83952f36d9f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e63078d-c86f-473a-a9b3-20c4a83f25b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec3ca4bc-f9cb-4644-9e5b-7cebdabb0c5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
