<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>48dd56df-02da-44ad-8e5f-1023b7d05c4a</testSuiteGuid>
   <testCaseLink>
      <guid>074b442a-c2ab-4be7-8e08-a152c2ffa26d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f833c409-7f41-4b56-b567-4c44b59b2bf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bb88f68-5fee-4f09-9ad1-de39db86f71c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7cf7f28-376a-457b-a9ac-f3aec2884739</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4408ef8b-1334-404b-9b88-13fdc34e0b84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>114ffaab-08bc-4eb1-9806-382a9fdefc63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3db755d6-7b82-4146-9cc5-0e7e9df36e40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d725cf5-2078-4c98-832b-4e1b5521b23d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bfa924e-f344-4de3-8ec4-36206cb870b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>233bd51a-6d8d-45f8-b478-65f176d4a654</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8552678-142f-4d02-8ecf-63eb59d2a308</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>068c14f6-6483-4487-b0c9-7f648bdcbcf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fb40684-788c-455d-9348-eb95a8813fd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88fa0df6-24e0-40e5-b684-81b58a6337bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af84ea93-58e0-4c20-a2a2-b7580f085af8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a4f25ff-97b5-4e20-88b5-198cbfd2b756</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e45ee97-3118-4b55-b3dc-df1c7fe41bd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a11314e1-313e-417d-9ad9-c80f7964bc26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1d6ce7e-7895-4536-b02d-a78cc15fdf7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e87338b8-5667-42da-ab9e-db69a9c5f9fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f96465b6-d701-4f3c-a68d-5240662e39c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd94eb58-ad10-4242-8b42-0f3f7ec04775</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16864416-e8f8-4dc8-aa2a-aaf2efe17ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddddf49e-1930-49cf-bfc1-0dd5160b5d85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>802a2118-5ecd-434a-9a5e-d2b439bc16b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cb0681a-8ac9-4bc0-83e8-ec41cef90e6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef20d3f3-1354-479d-a23e-59716935d988</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0bbd5a4-4524-4293-86f0-c2ed1e03ee99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bcbaf3d-8e1f-4550-b1f7-9e0a2d0573ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056438d0-af03-42a7-8f50-06653c8d300b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>165053cc-494c-4602-89de-6e2db6b21b15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c3755a2-6ca6-4098-a319-28f6df479099</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b34a2f27-527d-4862-945c-7528ff05e805</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2cf8192-bfc3-403c-a70b-676ca60d4d05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f650734-11b9-4ff4-acd5-8c0f2c681ae1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cde696b5-19a3-466c-a624-d103b84807ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>803e0ba4-3a01-4c81-842d-c24c3b390b22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83ba21db-2751-4656-97d1-2162feb958ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f67a6e1-1e01-4177-b1cd-6c7058258475</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c033ba95-0aee-4511-8e42-c0e6cc9c0142</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc61a621-75f6-44b7-aa67-0b012245c7c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0354bcd9-f5f7-497a-965e-c4ca8c76d445</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32bd009e-8a29-42b0-9234-28cfd65df4f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>307e6c53-ce69-4b5b-a3cd-9569c41ef7ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b58686-4c0f-4afb-b027-1cc8d73d81f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85b84a30-a0d4-4125-a4d3-0fe6a1b4a6c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0730f481-82ac-4176-88af-4540481fc345</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bca1c1e7-03c3-4b2f-adab-d5f677a398be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0b21aa1-2f72-4922-9f56-12a35c5d49ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96759bd7-9519-4fa5-ba66-98ee4478de95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3d18cee-d843-4ddd-bc40-5f54f8e24b19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa188d3-a5da-4e5a-9c37-b5f39971fe8e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
