<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LCC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3e3afb5f-9892-4ea4-835d-120dd96bf6cd</testSuiteGuid>
   <testCaseLink>
      <guid>83a479c2-f189-46de-a965-057ccb556fc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030a5085-1847-4a00-9686-e8949fd43078</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ddc0692-b100-4b6e-b329-162e103c022f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a327612d-b9c0-45b3-8589-74b168625df0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>955e6ee5-9a59-4eb8-bfc0-a63356837ba8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b3932a-f77c-41c8-97b8-9b5c7296ec59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb155801-468a-458b-b902-fcf06ae9a000</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcbeb1c7-5e6f-4f57-88de-c5894cadbbbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ecfeb62-af9b-4040-8735-fc067b098d0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c164456-76ec-48e5-9932-8ac26bbeebd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4b4280c-01b7-4fc5-833e-8cfb44ce391b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc9c06e0-394e-4720-a907-bbf946820644</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c3b37d-3144-47b6-8901-7e5589dacafe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6755ef-dea8-4ac5-a8c2-920b1b8da114</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ce9b32b-3a9e-40b4-8635-6b20ef1c873b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6588586c-f69f-499b-9005-f9eae7c8400a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da026f4e-9ed5-46ed-ba59-e0abd2eaab75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c80009-eb79-4cd0-9ce0-582912bd4fe2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>795a3b83-4701-4bdf-8fa3-16b990cf3e69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ee8d33-eb01-483b-bad6-7b8fbc302c46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e247792a-e6dd-48bc-8d45-5b888c8e76f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e369d07-dca5-48e3-aeea-28fa9f3f83ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74f82a01-e1a0-4bf0-a6d6-2ab7718af2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc9064b-afe5-47a2-946c-e63d971a528b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bec02f2-c89d-46d2-a4e0-0c91879170d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>814a1e89-081f-4079-82f1-10778ada89e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b76d9f6-b204-496c-b9d0-1d977a3b0c92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7fa8b66-fedd-4b35-855e-9d330119a18c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5be5acc5-ff78-4cf6-bd00-8aa79a6edb77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9af952d-4415-4407-9c1a-edd7e13e6156</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1736a979-7960-431f-b872-bc8c5ad0843d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c265c859-5879-449c-a3e8-73674027ca4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad838852-7fd3-4aaf-8b81-90733f82f1ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c54cb0-ab3b-4eb9-90d0-8c570508d6d1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
