<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LCC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3e3afb5f-9892-4ea4-835d-120dd96bf6cd</testSuiteGuid>
   <testCaseLink>
      <guid>83a479c2-f189-46de-a965-057ccb556fc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030a5085-1847-4a00-9686-e8949fd43078</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ddc0692-b100-4b6e-b329-162e103c022f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a327612d-b9c0-45b3-8589-74b168625df0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>955e6ee5-9a59-4eb8-bfc0-a63356837ba8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b3932a-f77c-41c8-97b8-9b5c7296ec59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb155801-468a-458b-b902-fcf06ae9a000</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcbeb1c7-5e6f-4f57-88de-c5894cadbbbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ecfeb62-af9b-4040-8735-fc067b098d0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c164456-76ec-48e5-9932-8ac26bbeebd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4b4280c-01b7-4fc5-833e-8cfb44ce391b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc9c06e0-394e-4720-a907-bbf946820644</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c3b37d-3144-47b6-8901-7e5589dacafe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6755ef-dea8-4ac5-a8c2-920b1b8da114</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ce9b32b-3a9e-40b4-8635-6b20ef1c873b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6588586c-f69f-499b-9005-f9eae7c8400a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da026f4e-9ed5-46ed-ba59-e0abd2eaab75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c80009-eb79-4cd0-9ce0-582912bd4fe2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>795a3b83-4701-4bdf-8fa3-16b990cf3e69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ee8d33-eb01-483b-bad6-7b8fbc302c46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e247792a-e6dd-48bc-8d45-5b888c8e76f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e369d07-dca5-48e3-aeea-28fa9f3f83ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74f82a01-e1a0-4bf0-a6d6-2ab7718af2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc9064b-afe5-47a2-946c-e63d971a528b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bec02f2-c89d-46d2-a4e0-0c91879170d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>814a1e89-081f-4079-82f1-10778ada89e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b76d9f6-b204-496c-b9d0-1d977a3b0c92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7fa8b66-fedd-4b35-855e-9d330119a18c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5be5acc5-ff78-4cf6-bd00-8aa79a6edb77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9af952d-4415-4407-9c1a-edd7e13e6156</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1736a979-7960-431f-b872-bc8c5ad0843d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c265c859-5879-449c-a3e8-73674027ca4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad838852-7fd3-4aaf-8b81-90733f82f1ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c54cb0-ab3b-4eb9-90d0-8c570508d6d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3def40fc-6929-478b-9157-f32a3a367185</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9259285-a7dc-4eba-8ba6-17c885200df8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44edcf4f-4669-418e-8567-442869f08964</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6434f192-6d7f-4e97-82ac-0f2a291a7ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77ca4d38-eccd-4516-bbce-8806789aa933</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02bed6c6-b3ee-45fb-82e5-cc220643f768</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4270a297-2f28-4572-ab1b-7f6e580130cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e106d04-dce8-41c7-8ada-1b540f3af98d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6936641-a627-45fa-90b0-05732a1f6af3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7474b5c9-48f7-4391-a50d-057f1d2431f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f8555c4-c86d-4bdc-8954-7fe94fd9c8b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05848298-f8e9-46fb-96a2-4802f59279a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e33076b6-653e-4dd4-a9f6-92e71b8b792a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f915f8fb-739f-4d5e-a403-bca405059fc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4bc6fb3-6da6-4497-a673-6c945045d0d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ea17c10-56c0-47bd-b884-066f781da111</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dbc8b10-20bb-40a8-b7ae-f1ea116ceeef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dd3b26a-765a-47ff-9a51-d105ec0e1d5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>627dc5e8-8fa6-4742-b127-9b015dbbf257</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452a2587-5eac-4eb0-acd6-8b84ff4c0948</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62179875-d515-425b-9a20-123dc4dbb6db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Convertible is preselected by default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b251f242-5ead-405a-825f-80fb44193d6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c74c2584-6714-42bb-99d1-fc729c74d884</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27be9154-1985-4b2a-8b55-ac40e12004f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4698e30a-4cf4-415b-9804-652e6e5f0ec3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8976684b-5364-48d0-bd17-07f71dc40172</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb379805-1684-4544-bbe7-d2e4c5677087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff91ed74-2d36-4364-8f04-bccca0ba14c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffeb7037-3010-4ead-b6a0-859da00b158b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Swatch carousel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7429c1cb-8294-45e0-a8d0-99a958cd99b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1805901b-eac5-4282-94ad-6290af015452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c271502-a5cf-42d5-bedc-0f750c88f9d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b336af1-4aa5-4497-98a4-da2c2a3d0133</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffd6f866-d120-4490-9a50-bb8835d6041a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cab6cdb-c5a1-45d8-b15f-5799b0666704</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8fe2c2b-c859-44eb-877c-28cb1d65cfca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a41ae148-60aa-4caf-9800-b8d81a334926</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/SignupForm/Submit form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a12ff0c-7a47-4817-a0cf-3eabc7b0bbd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df776cda-422a-44b0-8795-eb667ce39222</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/SignupForm/User opts in to be contacted</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7307ead9-de5d-4658-97f1-519bb1454714</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5d32493-b0c6-4b0c-a9a7-c8ea31e51b88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Design</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7441cf9-98a5-4394-9f63-f1fdcd4bb73a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fad797d5-e346-4c73-915f-1ac21d3bc1ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd7c7d0-f95e-4754-9dde-0030caeb5b62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebf0bad8-bf97-409d-9f41-eae342592738</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Info Layer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0823cb20-3664-43d4-80e9-3cb727c7f67e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49c8570f-a181-4a64-9522-ec408a81ac00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42fb82a2-f24c-4d97-9b64-5d2998aaf653</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64b23835-c717-4d3f-b0b0-4d7aa64001a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0013d8a-bf83-435c-9faa-bc92e4ef37b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7dcb11a-d0cb-41de-9e17-302dcd027795</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Safety</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>415c9d5e-58c4-4fb4-bfae-d88b5e4e78fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e474543-5dbd-471b-904d-357cd34e705a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82501747-f881-4769-8e2e-031247cc2e57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b5c16bf-fc59-4ba7-a814-30587e265d30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Technology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8273196-3747-457f-93b7-f543704e466a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6974d9d-2478-4651-93e4-52b540595079</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Subnav/Deep link takes user to pre-determined location on page - Visualizer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>917dbbd5-733d-4238-bc78-1c941e85659d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
