<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LCh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>84074992-2970-4178-998a-638fa4f9fdf7</testSuiteGuid>
   <testCaseLink>
      <guid>87228706-36a7-49cb-9aee-4f1580f1886a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79ae70c7-a590-4dbb-942a-84e281ea4095</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41a11539-82d7-473a-be57-75d06da16fea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f1e4968-0b43-48ea-bf07-4a03da49213c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7332524b-d6e3-46da-a6e1-ea108b3e6885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5e474ae-63e9-4d1a-99e0-968aab26741c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bdd1169-8bfb-4da0-8b35-760d66a182e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c55409a0-8923-4336-82bd-a085bbd68c52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11a6bf06-c856-466b-b5b0-cd570926845c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fd905f-6389-4e86-af7f-4b61a2721926</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d537c3fa-24b8-4120-a282-8b727f4641d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8ef0ad1-2dcf-430f-ba59-e9e12d482cb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b818589-1537-498b-83da-438e9d1c17bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecbd020b-a68c-4fb5-a641-f3193ca757fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3510af84-1793-4e76-8dfc-b6a246cb8100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4714cef1-33ec-41c5-a866-d386f0d55418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4b35bb4-6999-4e54-b34f-2b4e08fb0c8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb9708e-84b5-42b1-bac2-c208ea3cb3f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71ce9217-94b4-4b62-9b3e-71c7328e5b17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d2fb718-4b2f-4afa-95f6-b89184799dd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7f4adce-a7af-4a8e-9c69-0118203bf85b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>250e7532-20a6-4eab-814e-67ce0b1ccba2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a09b09d0-39f0-41fd-a9c9-93698dc93d6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f1115e8-7b13-459a-97f0-ce78dc6701ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09ccae2f-4c6b-4884-9b3f-89b27bb4cefc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cc57bea-278c-48a5-b75a-2cb7c10e9cb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ed80b74-a9bd-4c3e-9c05-fce972e703b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>491fbb52-798c-48bf-ba80-8455d847c10c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a127ed24-c13c-4e76-aecc-43de821d335a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ceffc56-fbfe-4804-94c3-81cc00c99910</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26c0c1d0-b602-46f8-8aec-d414d59fcfd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c023a5a-6321-4cde-8807-9533eb7ce88a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20024f07-23c7-4d7f-b0c6-15910629f934</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29b2232-7298-4722-a7d2-237c037d17d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b943206-5424-4371-8774-fbef1771d148</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f297a493-78f3-44b0-9dae-5b9f965b8264</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2411764-c82e-47fc-818c-8f227a1c26c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a67c566a-2469-4fbf-ac41-6e666cc7f0b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f4dbd8c-37b0-4d84-a3b8-37fad79ef96d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebce63d-5edb-4b0b-ae82-48270a8eec57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8441195-425b-4fb7-a7ee-1e4154fdd330</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ded5a20d-9d1d-47e1-9079-dd59c6c214af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9123c81-0ea5-4ef2-9b79-a01eb873f78c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c6e0f0c-6753-4102-b6db-33b6e40f881c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>306aadda-b10a-4410-ad36-4ae89c51c05b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ad1014-6b0d-49e1-a44e-cdcf918ffa3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c939fae-3204-48e8-9660-e65c3ce00519</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e81c04f-2e4b-4e22-a290-36e9688573aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>994bd468-7367-4a38-8a6e-dc0f0c2052ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7983d882-bc80-4816-8c87-7068a8ea7be8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>130cd778-176a-4842-97b2-53416a64242f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35e719dc-f9ae-420c-beb0-a5774878d5df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68f591c4-5d5b-41ed-9650-e8533c4c430c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a230addb-7f23-4a54-809f-6fe1ee69b22a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8b4595f-af56-41ee-a3cb-85f8b569b2b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Hybrid content is preselected by default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b0b6cf9-1125-4a9a-a7b7-c81d520502fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>debea3d0-ab4e-487f-9e57-5e974c629e69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72806fc7-4cde-4f52-9a0a-cd7b5ac9eb35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf50b838-14af-4276-a426-3f00b30d85ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b1e5391-c143-44e1-b7c3-c66ede242a1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7290b52c-32ec-4f38-bfff-e8e51c92b53b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91113929-6898-4535-9a26-eed97b3e6082</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c5049c4-2527-4d3f-9581-9a4e218023f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Swatch carousel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4c61728-ca69-46e2-872b-549b38f8ab12</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
