<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>25e64047-2c0d-40a2-8452-3b067c0ca926</testSuiteGuid>
   <testCaseLink>
      <guid>f5e73d2e-f5b3-42d6-a4f4-66b7805e9e24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>102b27e0-da5c-4c72-8d7e-80398e45b719</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fddf0a57-6a28-41af-8a02-2a4e045f1e99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be136e57-1a4e-42c6-8c19-bb8ebe55b960</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb4a33e4-6f58-48be-b990-0797b04dee76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb8235a-44b5-4fea-89ee-8a83d8746af9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89654773-ac33-4ced-9e63-b3f22711fd66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91a846cf-0908-445f-96f9-0d6544d8fa9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40409c22-4a1a-4fe1-b549-d93e9413482f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5a3d5e2-c99b-492b-b670-d351d01a5257</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df942429-c069-46d6-9c9d-ed973462ae12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c6a00b0-e072-4deb-ab2a-5aa27161bb7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a94371fd-a5ff-4067-8c2f-d16f0f4bddc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b11955b-d340-4e29-bccf-55ace710d348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb0fa3d0-9be4-42c2-b0b9-ef5d3d282120</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aff8e9d9-fb7b-4f43-b9d7-7ab17aa64346</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37ed36d9-9fd8-47fc-b745-8029c5a422df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9dcb12-cf3c-4721-a9ee-484dd98308b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d67db8f5-0b97-4332-bad0-64e5fc60b4bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>196b4ae9-5792-4c6c-9601-9b26233aff77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98e49fb5-fad6-4806-bf0a-619c39e1a08e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cda74615-d9aa-4842-9229-12c2ce99f339</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbe1861d-a8d0-45f1-b86e-3f18da676c7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84d13529-c84e-4dc1-a999-f910985365a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1890284e-f730-4b87-b935-841647587728</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c4cbf5c-f810-4fdf-96d8-746f811c9a91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24e4d437-5aa3-42d2-90ef-4a515f6fd32a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>857abd94-98ba-4ed4-ba07-999c45055518</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bffc4a9b-1052-4d41-a1ef-d5260eb1cc18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>914e6b49-9c0d-4460-9afd-b08592d88d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cfb85a5-dfdd-47c2-acc8-9f0c2bc17d31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>883ac3b2-086d-40ee-88c3-ce13afda787d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a85a1d4-6d9a-47c8-8a1f-08bb59c95ca3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1159914b-a9ad-481c-b161-514c4f4c4d7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>429a4b78-9a24-4835-a0ac-8c1a904485df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6de14106-c8a1-419e-bb3a-9c4561694e65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88a5c9af-eeef-493b-8226-fd5f02181c80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b0ffee0-83a5-458d-ade1-74bd79755253</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb6d8773-275b-4878-9c86-081adf9d1df5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9847d30-afe4-45a5-926c-fedf0697806d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7749a5af-cd72-4e33-be8d-5e1cfd0906ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/InfoLayer/Features - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc688a22-6355-46b5-bd90-a8cadd368699</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f43486f1-75e4-4e61-8867-b29f63d36047</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/InfoLayer/Specs - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>709f90b1-3c66-40c4-85d5-9b5800719cd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f1df62b-582f-47a2-b77c-716ddbe0fb38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8948bfe0-8e9e-4312-8857-b5c1c0d3d780</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>514a8483-b180-4c1e-aabe-d52aecc8b0c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ab93b0a-bd5a-4e46-85e7-d60c859dc5c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2f04367-d612-4779-883d-de07655f5770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LS/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fec5f9d0-1577-4350-8c10-2cdf7ebef69b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
