<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LSh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d4462cd5-fc28-4eae-88b0-58147fa59b52</testSuiteGuid>
   <testCaseLink>
      <guid>42387c5c-fb89-486f-859c-a01e55049dfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391b6fdb-ee79-4220-a0f0-f224111c2e10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49bd1ec4-03a9-4636-abaf-da0e4a3343a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3560775-7aaf-4f2f-a8bb-ad34a48a5b18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a748156-26aa-483c-ba42-921a30f752de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2e45909-e91b-4764-905b-3e96329d53c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3f52d3a-70e7-4a94-82a3-ba5548290d97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06ab85b0-733c-459a-a3cb-2f5af858f67e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c17c9cae-29e8-4200-8e8f-68625d1384a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d84a30c4-c751-4757-8dc7-cd9af18bd222</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f80d7b3-a900-46ae-8f72-2fd224808a74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fed3618-e646-4ffe-bb06-5ec6e432dd3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>843bdcf0-0945-4ff7-acc3-8f41a0a7bc9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29c6164-2eb6-4844-bc25-021d15514331</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2a367b6-cd54-446d-a52f-08f237324970</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffddc392-f86f-4ce4-b3b1-3567a4381a11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c199183-71ae-42e6-b258-58e48f5b4c87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fa67bd-7272-47bb-9d37-9673212b9ff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2aa23c79-004d-4935-bbba-2376158bd828</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>120520cf-53c4-4994-9c2e-c763e84526d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6e2f8df-9b59-4f0c-b77e-022df0a9215e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbb3364-9509-4aac-8b87-69b9038394b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>083588f6-9927-4402-90bb-c4e406a64384</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab10da01-3fad-4d5c-9d76-93163e5fcfab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>824b2d46-78ee-4385-9e76-788b3ecd60c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3e2d0ca-8f0c-4298-9605-b11cf34e159b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e0bdbaa-bbc2-4a0a-ad7c-b946bb0560cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f57731a-c91d-459d-be4d-1a2993daa3a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>597ee570-8d61-414c-aa6b-356bfc69e299</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de0be5c6-96b4-4c35-bfdf-8ec731134a9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2be13e2-86bd-4733-a2d6-c6ae9359665b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe13734d-1e37-4538-a057-f46c448e2b13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1545336a-e43d-4b59-836b-efa97a5a142b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63d7ebe2-05e0-44f7-b1ee-b629fa3d4f72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f124ba53-f200-4a90-872b-a904e12d1f61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6cca653-dbab-4622-9127-a7747f87df58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>745f76d1-5b24-46de-a999-1208093641a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b1746a7-08cb-499f-b990-f26773654cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7a7b57a-7419-49c9-b57e-3f5955803067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d2c91c3-e315-4e5c-92bd-08c0bfdefcfd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
