<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>75eafb47-be8c-42c0-8bd7-d0d3c9cf75b2</testSuiteGuid>
   <testCaseLink>
      <guid>4d2350a6-4c7e-4bcb-b9d2-3808164dd6fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ea7a1a3-f460-4d0b-be71-41de1753e707</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e53254e7-60ba-472b-a227-fe14117f116f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00e95bbd-f2bd-4bb2-aa75-db444d466a60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1818ac16-2ed6-4cb4-b20c-eb3b318c9f23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73ef7053-fec0-4a01-8970-dd9eafb260ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1799b0f1-08bb-4ecf-b268-6967990024af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9114cc2-f586-4d4d-862f-b1d81fb2b372</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cd125c3-c980-4081-9bf4-617ec369d32f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dac60a89-17d3-43e5-b672-a1656495350a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b67e22eb-fc9c-448e-9706-627026032c24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a3b7b3-7458-4b62-bb95-d7e7344d312f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12c518b9-e518-4c79-b098-7ecb1ccea5d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>014d56ee-33fa-47b2-82a5-0b4313512ad7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fcad3f0-5563-418b-bd7d-2d7f52e0fc29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c42d64d6-4781-47ef-b896-246b6e5e4d08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9982c97b-157f-492a-adcf-639dcd55cd58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>078f8407-ab1e-4fdb-8014-44d494779bca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2117a91a-568d-4e38-8a0f-fbaa517550fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4857225a-f306-40cf-ba76-99c2fbc40998</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4600504e-914c-4713-ad7a-ada3bb75882c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2159701-98ad-4acc-b011-0f3554fda9b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1901340a-6442-40df-a2a0-e3e22ec000b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2077305c-08b1-41ec-b846-2cc7b6dbd262</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9699aa61-69cf-42da-bdb3-b10dd2705b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73473f60-167a-4489-ab08-57049978991f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64008802-7de0-4543-9cdc-bccc601a6987</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ad9b440-3e84-45e5-9e1f-cee4dbdf65b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d33ffa3-962f-4e82-8ee5-c0de9248eb18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d1e6e20-147b-4816-8ef6-ef53345f05c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1cdddb7c-ddb7-471a-9ab2-94c3a6ddd655</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dae08021-1b77-419c-b539-0dcadb7f706b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40c49726-96ea-4f14-932b-5849f8f5258e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6405a4-dfba-46ac-90bd-098e46e7f217</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fab9ddd-f6fb-4e92-bfc8-b9718a4b0c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a959326-46ea-4447-8184-c25cd5eed4f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9be13f45-3201-47a6-8b5b-4f3e4385d135</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2927895a-e859-436d-adec-0d27b61ba3c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c137b7e-8ab8-434e-a5d9-7e0b24f4055f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eded7ed1-2583-4786-accb-042ead82a87f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d6bf539-90fc-4993-b8aa-231035da7584</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f29ce87b-7443-4dd6-a530-f235c50e04fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e5bd30e-f1f5-4290-a02f-74d509ebf5c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>716ee317-ace3-4516-80f0-21cccfbc1b6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c9d30e7-da9c-4ea8-b006-f1b0721ccf82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6653dd-6ad6-4e33-8fb4-e8749cc9ceee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67096bc6-47f2-472e-9412-bcb13c66847f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d2b43b0-c5a2-4815-bc9b-5c30da411a5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc647345-3e5f-4b6c-be43-355373de089b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2537e9d2-60e3-463e-af09-92967e7bed88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acaa196e-3b1b-4b21-b640-6c638d9c7f7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b222315-686f-4ea5-961b-872f2b906fe6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7bcdb7f-ab8e-4361-9a64-94cd28931171</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38b90eb9-6238-4cae-95ed-094cd6d33b95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92792dea-e8ca-4eda-af38-a9b08c5e84ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10756fd6-239b-4cc2-b134-6c398ba14baf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f59e198-47a6-45d6-adad-a55839969191</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f07c66c0-89a8-4aa3-b371-1e44ad4310e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8316339f-3a80-4132-9892-16cbe3bd8e24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63e3be6b-f33c-42f8-b228-8824773c5a8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22485d60-fb29-4c0c-8635-26abc02ed000</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9382afab-024e-44a8-adbc-e4291f5bdce2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f9195b3-1ea7-467c-910c-cc33af6a8e6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ac305f-ca1a-4ed3-a247-889ff669c2d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5152b6a2-93b3-4c4b-a046-5201ec137ad6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6838e346-6fe4-4ffa-9b0e-4b3252d10e21</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
