<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ModelPages - IE11</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5ed52ebd-86cc-4aaf-b226-fdbfd652ccc7</testSuiteGuid>
   <testCaseLink>
      <guid>fbc9eef1-f464-41ab-920e-6a982302942f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesAccessories/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9486d02a-6f50-46bc-a458-95bbc6675636</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35348ae1-b7a5-4a89-abc3-4d86e35698e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1631da5d-bad4-4e33-a948-bd75da294963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce04cfa-3ab4-4363-b255-f402af4f1b26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09ad6aa3-9d5b-45c0-93d1-6847e4c5fb78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesDesign/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aab24dbd-4a8c-4e06-87e2-e5af332b25f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b07340-9d67-4ae4-8566-ce5576656870</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>381eb476-7558-45c2-abdf-52e990c726c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b93da1d-37d5-4c51-917e-ebc5d856df69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f2a9849-f842-443b-8b92-24fb4c0fc9da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesFeatures/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bfa8972-c61d-4d08-ad66-3a8a5dc7793a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354c1ad0-2eb3-48db-a740-777f490f6824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54bdfc56-c648-4f11-97c2-93af3b401898</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>764a92d7-a268-4961-b485-a7523566bbab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>991ad0a1-aadc-4253-82c7-45e8eafaa904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesGallery/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a09d374-1d29-4a77-89d1-c8f021517b39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41796b72-9f05-4fa4-8699-bdf4d87ea0f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82545013-7eb3-4387-8a4c-73673d402c0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7db0eb26-d0f3-4e8c-a584-a6b64b93e0f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9322fb8-be12-4ad6-a00b-c72c22ba7b41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOffers/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da15f3af-2b0e-40a7-b58d-9f9b7f1a0e3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c67da9-67d3-4cdd-80f0-3e4760b7c176</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df1a155f-e591-4bf7-acfb-d3a76592be5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>251e6c5e-2090-41fc-b397-450b3ab1a794</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acb0cdb6-2efa-4f80-be65-4d5b828f8606</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOverview/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>334a8373-b681-41b2-bfe6-f3310598a9a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dbee4df-0c40-4f31-af49-cb047a01e591</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e85b7773-fa64-47db-932b-6386d6420222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96560705-af09-4d17-8e15-2656ba365d8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4623374a-fd0c-4fe5-93ec-e6d2b7e30b00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOwners/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ee7c0c7-ed91-44e3-b1c4-f77aee86adc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f1d80a-de98-4e3a-b7a8-b3708eeb3f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fec25612-d22a-431e-984d-97aca92095a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e088420-1532-413f-baf7-2920c4f98bb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62cf5f86-75aa-4dbe-977f-c3c8b1b14345</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPackages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c75820e1-2f38-46d9-b25f-42df6a7e9df6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43078721-d445-4d6a-86fb-e6abb6465277</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190d1b16-0075-4327-97f0-77f3b222ee08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>251c077c-5a92-4691-a367-fe7fb60c3f52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ff61104-58c4-45b2-b0bd-79ded58c8118</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPerformance/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162b51f9-a26c-4712-a33e-7bcd6182892b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>293f1e8e-02cd-4d4f-a529-76674c1593e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c717b298-87fd-4d8b-9eb5-3d87afe09285</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a23a55-9d08-4f5a-8f12-55b659a62edd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3115e2cd-ad95-450a-af8a-207123cba707</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSafety/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13a0db7b-b63c-4848-9894-d8e0a95a3611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5112d385-4706-42d6-abd2-6219d227f0b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ef73c8-5855-407e-ab02-09fb6a9b1c90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d86fe12d-1a50-47d0-b8aa-e9d3d0694602</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb9696e5-d6ab-4fc7-be67-7caca710f61d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSpecifications/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baac4c02-22d7-49b0-b75a-70c03c0050fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2b2dd07-1c4a-43d5-886e-c832c6750770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c8a852-21fc-40fc-bfd2-5411f37cd46a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee30328f-c43c-44b3-ba5f-ecde148c53d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>133a9f5d-6e43-409a-8392-014f5f6d0487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesTechnology/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8911653-416a-4ac8-972f-89b55dd0d48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb345e5-a4b4-4027-8aea-19b722abb474</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1af17724-db32-4a86-ab56-4e7199d2d453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbcca3cb-3c27-4eb8-b7b5-10efbb672a3f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
