<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NonModelPages - IE11</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>05bb9526-1e74-4b91-91ba-69147483091d</testSuiteGuid>
   <testCaseLink>
      <guid>ff25b2b9-f1a7-4994-88df-4536b346342b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/CategoryPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4aceed0-bf88-499f-8ba0-71e273831c4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaa7014a-ac2c-4c62-b79b-bbe301046a25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e4eee68-14ea-4507-8e78-81160f653867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ce317c-40d6-4a03-8a4c-04673d81d3f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7789287-1b6e-412e-920f-bec42fbc2502</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ComparePages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b541e0c-4697-4208-a89c-097fc92dff8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4add3df6-113e-42ce-87fa-b47bf1edee3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5402d182-17d5-41e1-8bef-e585cc8497cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55676f6b-51f7-42b8-98b0-4e20ee8955e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a76554a8-4ec6-4eab-9c40-3a2b595ee61e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/DealerPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>477a7572-3b02-4ae7-8a64-e6ddea7ec9d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1f1cc49-5c58-4489-9b53-2bdce6c9afde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30faaea7-1e21-4a81-a3ca-e7a05dc9d93b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e62ff4eb-ac24-48b5-b84b-1f264f8d4728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd67aabd-2534-45bf-a1c8-903be7ae621c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ErrorPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecca11f7-542a-4f82-976d-d43b51f5b406</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5044f184-83f9-46d9-bc28-c11ff29cfdcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7b60d0-a8a3-4ada-b93f-64151edc6fc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45e6ab56-083f-4bf1-b91c-490ffa19ced4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46736b45-3505-40cd-a11d-9edc51f3b5a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/FCVPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7554b92c-d03c-4710-97ec-8dce2a2c2f44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d69ddbf-6b45-4df8-90d5-e86f00ece1d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b9ca79-88ac-49c2-be98-dc5afd18a38b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>302e6b4e-6246-4383-aa59-854032c4a763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>201293e1-aed6-4660-9465-d25a0ba2c32b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/HomeOffersPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4433f3ff-1ad2-41fb-b422-5a1ac3be1c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe7248dd-897a-427b-8e63-62c12188e000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d255b4-c929-42b8-9b3b-1d721f561cdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fabf7c-baec-4080-9c09-2d3920e51839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>561fc33f-a51c-4222-91ea-ffc01d5b94bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/LCertifiedPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d5cd91-88cc-4336-a1b7-58f6193bc728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d21cb9ee-e36d-401f-a408-116c3e166d56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e8d959-52fe-42fc-8048-0ab443edbd41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5064a2-e132-41be-b9f2-9b1abe328705</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8cb8e27-83d8-4a96-b4df-d0fb4934dbb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MiscPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf789e6f-f3be-40e8-8071-5c7f19546c57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c236122-19a4-4322-8a21-f38e7db2684a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b48d6b9b-09eb-4865-aeed-6a393db5cdd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87316577-ecde-4945-bded-7f0880072dfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4ca1124-3f94-4602-8b84-39328d538b3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/SponsoredAthletes/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16d68ab6-6708-4092-9f84-15a9e121a841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79c8fd4f-2c1e-43df-88af-817cc39b3b4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>370178eb-41b5-476c-b212-8eeb1d27c2b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8595177b-92c8-465b-810b-341d319d35f0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
