<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b45af844-fa47-4be6-a12d-d4bed129daf0</testSuiteGuid>
   <testCaseLink>
      <guid>54115d2a-72b4-4c0b-a216-d82b2b57d438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee5690aa-0f1f-474d-b809-af7651252eef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2449e916-bb83-4027-85f1-b31975774513</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e500fd27-76a7-4c09-b99c-4cadfc9089a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c15912b1-97c2-4113-9fe6-f10cf128e99b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6065c58e-f1ae-43b1-b314-f27c96649cde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e106bf3-3854-4e7f-ac3b-9fc52feff26b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b47cbd2-9ad6-4e7e-9cd1-620ddd5e1129</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a7b1dbe-127a-441a-8ecd-614aa610d2a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb76f29-f7d7-4d45-9e1e-fef722e29193</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dce189e-695b-4002-a7aa-949f185a64d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60359717-b76b-45fd-8f0a-fc2d19ca9003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2d9431c-44c1-4e34-8666-dbc9de764cd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>674ea1d6-ffe8-4f6c-bb4a-f7885fe3fbf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85a2db5c-f7c5-4599-b932-3575a51ea8ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6248930a-9caf-4bef-8aef-6fb85ae0c520</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccedfd1a-4609-4e0f-a576-bb6bec28d7c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e1f116-586a-48e8-9c3b-0fe5f37f2d9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18d52f30-4c3c-438a-916c-b655b75c9d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f3e29cc-a81b-41e9-8689-3949b23fce85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58ed7d88-fb01-4acc-a610-5b85c2d885b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3edfef0-0f39-4f71-8b7a-e369b41e5a94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9da85b2-ef05-4517-b53a-ed8202ce91f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf8ca07-b3ff-43bd-a101-af3212ebec0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f179dc9e-ced7-4d00-886c-905bffd3c815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>322ea4e9-dba5-4acb-abf3-3efff6fbf067</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93c7a45b-2342-4ea4-9c0a-1865b76a1d02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57f57392-4bf5-48f2-9279-896134a87763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05714fb5-0286-4d9c-baea-197c791c1b7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ec281f9-2830-4af5-8ac5-baea2ba8ba3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60cf9b63-04c9-4817-986c-e1091e42379b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e0545b-1433-467f-8a24-b51db36a1e77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c48a244-e899-4307-95f1-9504ced1d5ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545de78b-640a-4caa-9fc9-07a46bd009d9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
