<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NXh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ceccafbc-ad99-4471-999c-fbf73a215a65</testSuiteGuid>
   <testCaseLink>
      <guid>4ac8cc33-130d-481b-b448-6496de3c1b00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f97f78e-9612-41dc-b5e3-533f247eb909</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>612104ba-061b-4a9e-a9f9-ecdc63fe9cda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>022705ee-99c7-46b8-8984-eea159f25b41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d123cdf4-3dda-4a8f-9d4a-04798b76ed79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361347fd-4e2b-4b29-ba16-0cdea7e75d21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d607d19-2117-4b37-8ab2-e2a3bd3b8244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e833979e-b124-4919-b244-ba39d6d2fea8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2259998-3dd4-498c-971f-244b8ae35acb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8acb228c-228a-4356-afdb-fa8a5d27be6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a91f455d-92d0-4627-a1c3-678fe9026daf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>965656b2-7f7e-47ad-ae21-4cb4ace5ab9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60731bdd-be16-45c4-9d61-974809eab254</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b04040cd-f872-4954-b72c-621547e345f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a5405a2-6945-42db-94c6-ddfb93be8a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a51e2e-fc52-4efd-8918-14bf2ac0f67a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d42559d-e8ff-4222-9480-b512a6f01cef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d830d66-1016-4c28-8f1f-c19f96abe0c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62ee21f4-267b-4529-a08c-7bcdac19f485</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b8e6f0c-afa3-4683-ac49-7ff8eb2c623c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea2f92c8-fcdd-48ee-ad2f-f4d28794679c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189cb393-c64e-44d3-9473-279c8a4277b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f636eb1e-47f0-43ae-8477-dacbb4e077f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6af5e5d-8c17-487f-87d0-3e88302b0eca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b262bf0-fa06-4872-bffd-89ab07bc21cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5eadad9-4e42-40ab-8f3e-cbb5b73d6be9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73e87083-20ec-419f-9f50-8d6835431706</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71860ded-440b-421e-8b0a-9cd03654d390</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb7ec299-c5bb-4db8-8cce-e09053453a13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3328c6e4-92f6-49de-8c3e-059473642f53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b77819a-d96d-4ddb-a93c-e5560b1868e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59116106-c5be-4d8d-84b8-940d25e27ec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e1aaa9a-a2f0-4682-a4b5-d4fee5e19ee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a68042e5-c33b-41c8-a078-93c5f9d52901</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5767211b-b09c-4ab6-a7c7-3b39e33aad9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28ef5fc-e9e5-4627-bfb0-89cfdb9dc2b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2159f87-80d2-4a82-833d-63a9f589702a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c13d50bf-57c7-457d-81c9-3edc42a5fbab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58aa5331-f6f6-4646-ba97-2cd9d6f550a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a453489a-d841-49cc-be93-71bd378ba9fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
