<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NXh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ceccafbc-ad99-4471-999c-fbf73a215a65</testSuiteGuid>
   <testCaseLink>
      <guid>4ac8cc33-130d-481b-b448-6496de3c1b00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f97f78e-9612-41dc-b5e3-533f247eb909</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>612104ba-061b-4a9e-a9f9-ecdc63fe9cda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>022705ee-99c7-46b8-8984-eea159f25b41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d123cdf4-3dda-4a8f-9d4a-04798b76ed79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361347fd-4e2b-4b29-ba16-0cdea7e75d21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d607d19-2117-4b37-8ab2-e2a3bd3b8244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e833979e-b124-4919-b244-ba39d6d2fea8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2259998-3dd4-498c-971f-244b8ae35acb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8acb228c-228a-4356-afdb-fa8a5d27be6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a91f455d-92d0-4627-a1c3-678fe9026daf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>965656b2-7f7e-47ad-ae21-4cb4ace5ab9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60731bdd-be16-45c4-9d61-974809eab254</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b04040cd-f872-4954-b72c-621547e345f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a5405a2-6945-42db-94c6-ddfb93be8a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a51e2e-fc52-4efd-8918-14bf2ac0f67a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d42559d-e8ff-4222-9480-b512a6f01cef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d830d66-1016-4c28-8f1f-c19f96abe0c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62ee21f4-267b-4529-a08c-7bcdac19f485</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b8e6f0c-afa3-4683-ac49-7ff8eb2c623c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea2f92c8-fcdd-48ee-ad2f-f4d28794679c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189cb393-c64e-44d3-9473-279c8a4277b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f636eb1e-47f0-43ae-8477-dacbb4e077f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6af5e5d-8c17-487f-87d0-3e88302b0eca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b262bf0-fa06-4872-bffd-89ab07bc21cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5eadad9-4e42-40ab-8f3e-cbb5b73d6be9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73e87083-20ec-419f-9f50-8d6835431706</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71860ded-440b-421e-8b0a-9cd03654d390</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb7ec299-c5bb-4db8-8cce-e09053453a13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3328c6e4-92f6-49de-8c3e-059473642f53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b77819a-d96d-4ddb-a93c-e5560b1868e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59116106-c5be-4d8d-84b8-940d25e27ec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e1aaa9a-a2f0-4682-a4b5-d4fee5e19ee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a68042e5-c33b-41c8-a078-93c5f9d52901</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5767211b-b09c-4ab6-a7c7-3b39e33aad9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28ef5fc-e9e5-4627-bfb0-89cfdb9dc2b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2159f87-80d2-4a82-833d-63a9f589702a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c13d50bf-57c7-457d-81c9-3edc42a5fbab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58aa5331-f6f6-4646-ba97-2cd9d6f550a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a453489a-d841-49cc-be93-71bd378ba9fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f255e143-c9b2-480b-9576-9cf3f4e32bb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Features - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7b6a87-0e9d-40fa-a0ac-1ebb256c0c6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6342a7d-9dc3-4365-a3a4-b0ea360842b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/InfoLayer/Specs - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cb14a76-f6a4-43bb-bf56-45bac4cf1b81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78e3d2e8-7eac-43c2-a919-ccb7d8b7cef8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e9ea888-a692-4e0c-abb2-805d3d4d01dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07b8bbc4-2759-41b8-9b2b-630af54077e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69d22b47-0a84-471a-ba1d-51ec9f94258c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d36eb29-ee45-40fa-925e-c2ac2f5e786e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45061dcf-b4e2-4f47-a424-d2ed4b9ff31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed3da148-1745-405f-9af8-95ae74a16d3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4387d4be-596b-4bfb-a082-5d0785ebc974</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9530ebfc-69cd-48da-817f-c6194873ad7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7c2068d-57d4-43f0-893d-c888bdd254e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44901588-0bdf-4140-8bd8-49191e1cd49c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21e71b90-b48d-46bd-a4df-a0575e528b31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67492eda-e62c-4278-ad82-98467cbb8237</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bee3587-2e88-4204-8ebe-ad3b5769c1ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df01e2e1-33ef-4afd-bf4b-c608e805cbe1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Hybrid content is preselected by default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e57baa-ebd7-4123-b4f8-4b10b015e53c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5453a0d1-bb42-4915-b131-2f597c4caa6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8834c045-3360-439c-8c79-7e8a98450a76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09e8c5b9-6178-47c8-a8d0-7a0b59fecdcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>703c78d0-8e6c-4872-b486-fbb69f905ee9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78c3bc08-4a30-4564-8694-b209d1a2d961</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b80ff2d7-ab02-407a-b020-ab28748175c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1a6140d-fcbf-467c-835a-7202396ac682</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8244f7-bd6f-4932-8579-a67330bfc70e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8eb528a-c4ea-473f-9d53-f82966231b3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63adad81-4e99-499e-8a83-ccb7ba41cc8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da811287-950a-4d03-a9aa-6106205588c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4782d2e-96d6-4112-bd39-c5b70f7e0d39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96e989b2-6001-4459-b3bc-c7f64dcf9644</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/SignupForm/Submit form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42be63e2-930b-486d-b7d6-1dbd1317082e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9450cefa-492f-40d7-ad6f-74026481bd37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/SignupForm/User opts in to be contacted</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78f69912-deb3-4d6e-9cc8-5d0df8b9e4fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d2115fb-d52c-4bca-8312-eeaad24f7c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Design</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eef64a9-01c2-40fb-a6eb-a02f0ae52be3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53da5f10-b4c2-471a-a041-842209bc30f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a6afe0b-bdf2-43cb-8777-b8cae4944c75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72f0bfcd-9f9a-4ea0-887a-69000496a042</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Info Layer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1d9e3b5-8b9c-459d-ba90-901c1fdc7c13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7eb56cd2-6ef4-4d15-acce-789444001249</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2ced43-a4cd-4d3a-81a1-49582eeabd42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc07f57b-5bd5-4a38-b41b-98167f552e86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Performance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0891d254-6a84-4c03-bf5a-d047d409ddf8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45c2bc58-71f6-42f1-bb79-94261e1099c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Safety</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b06ec9-e913-484a-8e2a-2425b35f76c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0d9c12f-53ae-459d-8f29-c333df3a78db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Styles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4254a8-de62-4778-95e0-0968c78875f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9996afdd-f497-431e-8144-bfd2ad4185cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Technology</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1138898-5cfd-4842-badc-328982e2686f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2533b2d2-b983-472f-b924-9e96a30b68ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Subnav/Deep link takes user to pre-determined location on page - Visualizer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a966a60-538e-46b4-be30-6cc4c23cb7b2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
