<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f90f2133-addb-4168-b89a-166ec8867778</testSuiteGuid>
   <testCaseLink>
      <guid>90499068-43b3-4ccf-9c94-4b59dae57a17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>482e0df5-7050-4260-8ccc-c4610ec368be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11189054-b90f-4a91-99b0-5609e5139ef0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>953b908a-d477-4071-af1b-9db1fe904813</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d031e01-6a2c-46c8-af49-c957ca38f0af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>797f65fd-ebe6-48b1-9dc7-97ee72d36fbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a9c8a26-7b28-40be-926e-a368a3c00b96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e55538-c88c-41ab-920f-cc33151ed0f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bf43973-acf0-4686-bd9e-f7411f1b5753</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f317998-bfc5-4cff-9577-f807b5fa2c95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>594d5a1f-0338-4edd-9ae1-8c70bd15bc72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40e54ff-55ee-4b36-a721-d9368634604d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ebd459-6b45-45f7-bc76-5f373b9d3731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bc6ba7d-6dda-494f-bfae-02357a2484ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3e2aad5-db03-4669-9e3f-08761a80745b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4dfa6ee-78a0-4678-93a6-c4cae7fc5572</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a539575d-53b3-40c4-8924-73d149be88e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>642a23cd-f26a-450e-95a7-22ef17d914c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5f93e4-9d70-4da9-bdf0-4ea3f89cc7f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e455639a-c9bb-4348-a650-89b645e3606c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27f0b725-277c-4642-af8d-7b3006165c37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817fbc08-9762-44f9-bb60-df8fb7838946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5b8e615-e1d2-4009-9e65-45342a093e3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cad7ab2-d6bb-438d-b8d1-6abf30c76fba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fe28fb2-abc6-4d25-b270-981f0b2bdd7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4750fa3-6fdb-45da-bd3e-644229997883</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec946d71-dd0f-4bff-ba14-91d6847fe5db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545f1d74-09b8-4429-9414-07cd20c3ed3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56885b58-ddfe-42a6-b5c6-9a55f0b9e1b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861fe62d-d163-41d5-ab49-bb27979d06a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40051edd-782e-4b43-bcb4-627970a7855d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74ed81f4-f1d6-41c7-b4f3-d3bd057a04fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89a84830-727d-451f-a6e7-7688c04b8af9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca69c374-6e57-4b1b-aec0-52e34eeeac38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00cbd8e1-3081-4ad5-8112-983a49c32691</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67041f6e-a0a1-4d76-9490-aaecdbe560e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec08d673-5253-45eb-bda4-16a0330bd7af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84642041-dd3d-47f4-ba76-bbcb37db66b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22acbdb4-ed6c-4386-b106-74c346d35293</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8176a643-1f0e-47a3-9a9a-bcd6bd4d7d30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c82a44a2-aca3-4271-8486-ca51071dc705</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/InfoLayer/Features - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a390d1b-4169-4b9a-aab4-1698e48da988</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>055537a0-965d-4e1e-b0bd-fe45d61c5150</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/InfoLayer/Specs - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bc60b6f-5405-41e8-820b-27dba8da7547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3772a833-fc3e-4fbd-90d8-eb00717d993e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b46db727-4bef-46e3-9e81-ddffdb826b96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd199472-b18d-4274-9b5f-adcd64e0e5f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de65549a-b254-4677-95ef-d0ca980c396c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe27f81a-2671-493b-ae1f-795fc93a9df0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20b1c13-67cd-492f-bb2e-3394668a2824</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74ca5bbd-82c2-41cc-aa02-96cd7da0e0fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189d2d68-d2aa-4bde-81ce-004b30dd2e68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>380f87bb-9c28-43d4-94c7-0b33b2f45d0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4aea31-6d36-4689-a30f-f90210935c3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e0be9f7-1781-4050-aaa1-498c198afbae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c48cab4-98ae-4cff-8a2e-bd63081cfb2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fde29c3-fe73-4e05-b10f-3813128e97da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ced7029-bc99-4637-9326-de21af4ec842</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96c0ef96-e71f-474f-83fa-caed7b61d41f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9e286b-dace-4099-9dda-b1611b1ba321</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b274d331-361a-4a61-9e31-9e941f4b106e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9468c92-7585-4f94-a493-2c3b688a8749</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a931d8aa-73ac-4596-9232-5df4ae4c089b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50209607-a480-4125-9d3d-e6a11a047a11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b5e61de-060d-4dde-ae1e-3cf28063f0a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20036735-a8e5-4e42-9736-3c0d6c133016</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cb0eade-d588-4202-8102-cfcc50777c28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22feebc3-c0ec-4d2a-bf1d-37cc93c972f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a24961d-c6ce-43f8-91c4-1a71091ba094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/SignupForm/Privacy Rights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a870fda3-f2de-4079-8526-2fd68140b3d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
