<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f90f2133-addb-4168-b89a-166ec8867778</testSuiteGuid>
   <testCaseLink>
      <guid>90499068-43b3-4ccf-9c94-4b59dae57a17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>482e0df5-7050-4260-8ccc-c4610ec368be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11189054-b90f-4a91-99b0-5609e5139ef0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>953b908a-d477-4071-af1b-9db1fe904813</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d031e01-6a2c-46c8-af49-c957ca38f0af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>797f65fd-ebe6-48b1-9dc7-97ee72d36fbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a9c8a26-7b28-40be-926e-a368a3c00b96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e55538-c88c-41ab-920f-cc33151ed0f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bf43973-acf0-4686-bd9e-f7411f1b5753</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f317998-bfc5-4cff-9577-f807b5fa2c95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>594d5a1f-0338-4edd-9ae1-8c70bd15bc72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40e54ff-55ee-4b36-a721-d9368634604d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ebd459-6b45-45f7-bc76-5f373b9d3731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bc6ba7d-6dda-494f-bfae-02357a2484ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3e2aad5-db03-4669-9e3f-08761a80745b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4dfa6ee-78a0-4678-93a6-c4cae7fc5572</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a539575d-53b3-40c4-8924-73d149be88e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>642a23cd-f26a-450e-95a7-22ef17d914c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5f93e4-9d70-4da9-bdf0-4ea3f89cc7f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e455639a-c9bb-4348-a650-89b645e3606c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27f0b725-277c-4642-af8d-7b3006165c37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817fbc08-9762-44f9-bb60-df8fb7838946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5b8e615-e1d2-4009-9e65-45342a093e3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cad7ab2-d6bb-438d-b8d1-6abf30c76fba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fe28fb2-abc6-4d25-b270-981f0b2bdd7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4750fa3-6fdb-45da-bd3e-644229997883</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec946d71-dd0f-4bff-ba14-91d6847fe5db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545f1d74-09b8-4429-9414-07cd20c3ed3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56885b58-ddfe-42a6-b5c6-9a55f0b9e1b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861fe62d-d163-41d5-ab49-bb27979d06a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40051edd-782e-4b43-bcb4-627970a7855d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74ed81f4-f1d6-41c7-b4f3-d3bd057a04fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89a84830-727d-451f-a6e7-7688c04b8af9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca69c374-6e57-4b1b-aec0-52e34eeeac38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00cbd8e1-3081-4ad5-8112-983a49c32691</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67041f6e-a0a1-4d76-9490-aaecdbe560e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
