<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RCF</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7077c4fd-2566-45c7-b974-6206038392af</testSuiteGuid>
   <testCaseLink>
      <guid>ad6ffa81-f8b3-4eed-91d9-b6b163cbf553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa119bd-a0a5-4f43-9b38-33e552a25b02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f480cc13-dfa6-4c55-956e-783ffb8d464d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a28775eb-7394-492b-82c1-236ab13a71c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7994c031-cb8e-473e-9f32-f50a5d7b655f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6894492b-e598-47f1-8391-02c4c3668a08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36a3a956-5cca-4317-9f07-30c2d564fbc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f73d924f-d0d3-4df3-84fc-88a6054c3a32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b557a4f8-3675-4107-9bda-e8b667055e5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11a17d1d-842b-4568-a7af-19993e05a05a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83daeb62-f47d-4077-a854-076ccb106591</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>343d90a2-1a80-4796-83ca-73fe76fc6f89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>409e590d-f88b-4d97-acd3-ce86459f0fc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be79d24c-d42e-46e0-aeba-1a5c561ab479</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78f957cc-93f8-4fd1-b383-8ef230822f3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91e5b5c5-3942-4498-9a96-89a86d731fa4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89d56510-ced8-4a4c-8c82-5dfffe6a8de2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5059a3c4-d1a8-4f75-b9f3-5e28638f9882</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08d40576-a596-4454-8810-4e9c1e7e5d4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7525e7d9-dbf9-4b03-8173-e271938b4455</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8450cd0-a446-4011-8faf-78180b2f72cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19d04209-dea8-44ec-8879-82ea32f2ab22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb4a12f4-314e-464b-ad20-bb3d6562ded0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0b834e-a2c9-450b-a49b-317e379157fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87cae029-047d-4f5a-ac3b-b544dbd56f03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97de381d-b95c-4e6f-b309-48a20866d91f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3ade31b-2840-4592-8d36-5ab5c59a3431</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee4548c-f91e-4cd1-b504-19f2dcbc14ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae7acd5c-89ae-43e6-a878-4142ba92cc56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91b116ec-6492-44da-9722-5a637bdb4938</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd43198c-b770-4fb8-bedd-0ba6ec5a101e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19324925-5fe9-48d0-bb34-181d658c20c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afefeae7-be6c-4490-bc41-e390dcb4effb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32ce6411-68b9-4363-ab91-04b9ea34d15c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
