<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f322447b-c672-4349-9114-138b79b8b7b1</testSuiteGuid>
   <testCaseLink>
      <guid>5d57a0ac-d7be-49fa-9c4b-f58b6b48a52e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1674f02d-1b7d-470b-a24a-962dd8fae6ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>613a3706-9625-4c04-985a-23b3d28062c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60402e0d-af68-4b2e-a5fe-4080d19077b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03f3394f-fb39-45cf-9e4a-ea439eef036a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caf7b210-7598-43bb-a71d-c8c0551c5d74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b2f920a-d1b2-427d-b86c-7b4c400cdc95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e8fd6fc-77e4-46de-8feb-620fc4038093</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24b52fb8-6d82-48d1-ae4b-be647c41ec2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55381262-3ae7-4d4d-8bc9-2365b8a1ff72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16537fda-482b-45e7-9cc4-4c999dffe2b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80afe95-e881-42db-a7ff-67cd0695bc65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dce46075-0167-4a25-a720-04aa3461af2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a143bfb9-4d63-4155-834e-4c467bda091e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6d96a1-c309-4160-913b-1f6a77cd9a7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf9a4b2a-bf4f-4e10-ab5f-9232d5377728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d33d6ab-a45f-4511-8127-8f99c8d37956</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6cb683-7d94-4948-a74b-1f8475f8e38f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1014d56d-21de-4c65-80af-dccd3bc6e02e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1221871b-7d52-4f28-8657-465f34176294</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f390ff9-393b-4232-928a-7fb80f847ff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95973f3-d25c-490e-95e5-b04b72b4ce54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41b9c267-9c79-4227-965b-35e8e7c0aa85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f59558c-0f84-4c6f-8546-082c8febcd0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53447212-c1ea-4516-9e0a-3bf3e1399902</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cf5b90-dfa3-4f53-ab01-d73d3ec969dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08bb14ee-4799-43ca-acea-36778f317087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60d1ee5e-cefc-442d-9f8c-d2d8924f9cea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5319379b-0be6-4e82-916c-72dc132e6597</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ee742f2-1c2e-49dd-93d5-739ec34edb88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07f44bbb-6e84-46ad-b037-adf94a42ea86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbb2f2c9-dc74-4c87-87e5-a4d943f582e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3c50e6-d7c5-4db6-a06c-0e772b78bc50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d8148b6-2950-4e7c-acc2-5676b52b0f6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c1de154-2e5d-4f19-82e0-810f200aab5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66611929-de0c-48be-9dd6-8cd4c0fdf6e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc4e91f-2828-4ce1-8ebb-96fd2e51567d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a8168d-a89e-4426-9696-b470595c020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f44d1c5f-a6c8-431c-9a29-bcc513cdca39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17456bc-cd0a-4116-b6e6-981abc2f41e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84bb6fd5-6fca-4720-bee1-ef2786059904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/InfoLayer/Features - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85650a8-e112-4703-be06-5b7222fcdba3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f339169d-def5-4b3a-b06c-834bfa6bb12c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/InfoLayer/Specs - Correct MSRPs for each AWD trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abfdc5ec-320d-4940-9f63-e24b1c3d21bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ba6d3d3-9683-4a75-be2a-ee2eb305e9b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cf8604f-44ac-4384-8c31-55a6f72d9119</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1897dc64-e189-416d-83b6-bda42c7aa28b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9441410d-edfe-4bba-95c6-00a9312c3c22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb2939d0-9478-4fd2-bc95-3c4809737bf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>316bcf27-190c-4568-a065-e836168b9355</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07d10b0e-a3ed-4ec7-949f-ebce1943359f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e80059f5-7a1a-4b1e-a5e7-d7650a92fb64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>317ab611-8f6c-4679-94be-fa22c18959a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8a77019-ce65-47ba-bd0b-20f905dca487</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fea8c706-2cde-4dbd-b79a-70b8203947b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/Learn More CTA leads to special edition overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99bfcf77-81e9-42ce-9859-ca663910d478</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5ec5667-72c2-4bbd-aa0d-258e5300ce8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25fd1537-4f6b-4436-900c-a271fcc2238f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
