<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f322447b-c672-4349-9114-138b79b8b7b1</testSuiteGuid>
   <testCaseLink>
      <guid>5d57a0ac-d7be-49fa-9c4b-f58b6b48a52e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1674f02d-1b7d-470b-a24a-962dd8fae6ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>613a3706-9625-4c04-985a-23b3d28062c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60402e0d-af68-4b2e-a5fe-4080d19077b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03f3394f-fb39-45cf-9e4a-ea439eef036a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caf7b210-7598-43bb-a71d-c8c0551c5d74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b2f920a-d1b2-427d-b86c-7b4c400cdc95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e8fd6fc-77e4-46de-8feb-620fc4038093</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24b52fb8-6d82-48d1-ae4b-be647c41ec2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55381262-3ae7-4d4d-8bc9-2365b8a1ff72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16537fda-482b-45e7-9cc4-4c999dffe2b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80afe95-e881-42db-a7ff-67cd0695bc65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dce46075-0167-4a25-a720-04aa3461af2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a143bfb9-4d63-4155-834e-4c467bda091e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6d96a1-c309-4160-913b-1f6a77cd9a7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf9a4b2a-bf4f-4e10-ab5f-9232d5377728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d33d6ab-a45f-4511-8127-8f99c8d37956</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6cb683-7d94-4948-a74b-1f8475f8e38f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1014d56d-21de-4c65-80af-dccd3bc6e02e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1221871b-7d52-4f28-8657-465f34176294</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f390ff9-393b-4232-928a-7fb80f847ff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95973f3-d25c-490e-95e5-b04b72b4ce54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41b9c267-9c79-4227-965b-35e8e7c0aa85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f59558c-0f84-4c6f-8546-082c8febcd0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53447212-c1ea-4516-9e0a-3bf3e1399902</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cf5b90-dfa3-4f53-ab01-d73d3ec969dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08bb14ee-4799-43ca-acea-36778f317087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60d1ee5e-cefc-442d-9f8c-d2d8924f9cea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5319379b-0be6-4e82-916c-72dc132e6597</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ee742f2-1c2e-49dd-93d5-739ec34edb88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07f44bbb-6e84-46ad-b037-adf94a42ea86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbb2f2c9-dc74-4c87-87e5-a4d943f582e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3c50e6-d7c5-4db6-a06c-0e772b78bc50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d8148b6-2950-4e7c-acc2-5676b52b0f6d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
