<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RXh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a9aef09b-17c8-4a8f-a0f8-8c6247355581</testSuiteGuid>
   <testCaseLink>
      <guid>23f7dc83-bb83-48ee-9af2-d019573938e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc7fccc7-a053-4e29-9402-37b0cfa157a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0a90195-1b1b-437e-a330-b0c6c8cd4470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b9560a3-ca1d-4c8b-91d0-22da003d5d78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b6d24f8-4cae-429d-b8d8-3e97e6afd85c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>625ec2d4-02fc-4bc1-957e-16f8528d5288</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6abe88ea-3366-4043-b627-776341b65d0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6bd9a5-d2b4-42b8-86ab-941c897a1fa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9537ace0-8703-4f51-9ce4-b17860707063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72465ead-2039-4f6f-a824-dacb9e163a45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a23fe0fc-b93e-4371-b506-378369f2d29c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b12741ed-48fa-40a9-8c13-4e15baa3ca7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30903b3e-000d-4427-b4fd-1cee921d2a5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1238bc58-07c3-4726-9271-55d69d5a3957</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec795ddf-c728-4edb-980c-d140b00b727e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77256859-e0ba-40e9-9616-cc0aa8862a0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d33b1408-851a-4e55-bd23-d371cbc0d327</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e49e7b78-09ac-49d2-a4e1-56336de75684</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d398354-8063-45b8-b1b4-25251adb27d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64832163-e05c-43eb-916a-3fe2be847509</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f525cf64-509a-474b-b2c1-54a27eabac95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>592bd304-56c9-4e4b-b8a1-5622ff861c9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>990a8bca-911b-4912-bc67-d442d221fe23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca6ab54d-94ec-4800-8e3b-4243c1a8fc3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19d85785-514a-4d66-98bb-c29da3ee908e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c74c68ec-a1a7-427e-86b4-69a78a0d24e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23925943-f69b-458d-bc0f-e6a1ba89dbcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e030556c-7a31-4e28-b464-88152b8b62d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c7769af-1497-4e40-9396-f6ce7921436b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61975363-83a2-4c28-9234-6c207555b57d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>856dd445-d885-4c4b-bfc0-116bc654cd30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc0b5abc-ec72-4821-9d36-152b956f7cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>889bc643-851b-4a7e-96d4-018ba3d1cae9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89044e59-e658-429f-aaca-160b5fc00e8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7c37a2b-3c72-421d-9704-e5af95589dde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c6031d6-0943-4988-8118-3a98066e4888</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
