<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Unsupported03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>14d1f0c8-dc79-480a-ab29-a22ca7b1473a</testSuiteGuid>
   <testCaseLink>
      <guid>4623374a-fd0c-4fe5-93ec-e6d2b7e30b00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesOwners/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ee7c0c7-ed91-44e3-b1c4-f77aee86adc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f1d80a-de98-4e3a-b7a8-b3708eeb3f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fec25612-d22a-431e-984d-97aca92095a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e088420-1532-413f-baf7-2920c4f98bb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62cf5f86-75aa-4dbe-977f-c3c8b1b14345</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPackages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c75820e1-2f38-46d9-b25f-42df6a7e9df6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43078721-d445-4d6a-86fb-e6abb6465277</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190d1b16-0075-4327-97f0-77f3b222ee08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>251c077c-5a92-4691-a367-fe7fb60c3f52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ff61104-58c4-45b2-b0bd-79ded58c8118</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesPerformance/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162b51f9-a26c-4712-a33e-7bcd6182892b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>293f1e8e-02cd-4d4f-a529-76674c1593e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c717b298-87fd-4d8b-9eb5-3d87afe09285</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a23a55-9d08-4f5a-8f12-55b659a62edd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
