<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Unsupported05</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bec264e0-0490-425b-80c8-7a9d7bc7d758</testSuiteGuid>
   <testCaseLink>
      <guid>ff25b2b9-f1a7-4994-88df-4536b346342b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/CategoryPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4aceed0-bf88-499f-8ba0-71e273831c4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaa7014a-ac2c-4c62-b79b-bbe301046a25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e4eee68-14ea-4507-8e78-81160f653867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ce317c-40d6-4a03-8a4c-04673d81d3f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7789287-1b6e-412e-920f-bec42fbc2502</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ComparePages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b541e0c-4697-4208-a89c-097fc92dff8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4add3df6-113e-42ce-87fa-b47bf1edee3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5402d182-17d5-41e1-8bef-e585cc8497cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55676f6b-51f7-42b8-98b0-4e20ee8955e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a76554a8-4ec6-4eab-9c40-3a2b595ee61e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/DealerPages/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>477a7572-3b02-4ae7-8a64-e6ddea7ec9d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1f1cc49-5c58-4489-9b53-2bdce6c9afde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30faaea7-1e21-4a81-a3ca-e7a05dc9d93b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e62ff4eb-ac24-48b5-b84b-1f264f8d4728</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
