<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Unsupported04</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9c6b92f9-45ac-4a23-b8e8-aee9c6c4a4ac</testSuiteGuid>
   <testCaseLink>
      <guid>3115e2cd-ad95-450a-af8a-207123cba707</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSafety/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13a0db7b-b63c-4848-9894-d8e0a95a3611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5112d385-4706-42d6-abd2-6219d227f0b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ef73c8-5855-407e-ab02-09fb6a9b1c90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d86fe12d-1a50-47d0-b8aa-e9d3d0694602</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb9696e5-d6ab-4fc7-be67-7caca710f61d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesSpecifications/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baac4c02-22d7-49b0-b75a-70c03c0050fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2b2dd07-1c4a-43d5-886e-c832c6750770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c8a852-21fc-40fc-bfd2-5411f37cd46a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee30328f-c43c-44b3-ba5f-ecde148c53d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>133a9f5d-6e43-409a-8392-014f5f6d0487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPagesTechnology/no longer supported message appears</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8911653-416a-4ac8-972f-89b55dd0d48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb345e5-a4b4-4027-8aea-19b722abb474</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1af17724-db32-4a86-ab56-4e7199d2d453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbcca3cb-3c27-4eb8-b7b5-10efbb672a3f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
