<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a180c3de-d766-4080-9119-8f43e4fe12e1</testSuiteGuid>
   <testCaseLink>
      <guid>c9c9a2c4-046a-4290-8ac3-0ccb702e9353</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd52d5db-4210-4b03-af96-d6a425ce789c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2f65c14-ac6c-442a-8784-8d83b8cac562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f7b1bd-fd37-48fe-b1f4-1632cfeea5dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95465c9d-b6fc-40cd-a9c9-b0b8516e7d1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d166b54c-3ce1-4e4e-a822-d0829d10973f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0ba0b86-0423-4852-8503-eb9ba98aa19d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1c4fed2-de0c-4f08-a622-f1a54351f00e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cf2962c-3e10-4b8e-8e38-49877d293e55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e729366-73f3-4092-accd-34d27175c6fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>077efc0a-34b9-4aeb-ab41-e1436bf29033</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93fbbd8b-c737-4929-9e5e-66e27595dbd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3493425-3da7-4759-864d-0a5c05e3e1a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c7b4715-b4ba-4c0d-83ab-3aad28462ad6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e3a611e-6fd2-4cf3-8228-798eb0cb5e2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3aec93b-c0e9-4a0a-9fb3-efbc6df8ed7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce47a699-11f9-4ffb-a12a-d6e7c62e1a56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb11ffa6-a188-4c16-af82-be2f0177f9f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fa61d44-eae6-4421-b118-a259a7a5aeb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b36a9eaf-885c-4cad-aee0-d4dba995b813</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dc8c40b-0c3f-4b0c-a1e3-639ce3dd0f78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e372f6e-4ed1-4ca3-bfff-52caf4ebdaee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce88d10b-bc17-48be-ab42-9f2fd7917ca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39f38c7c-b7db-43b0-ac72-98a122c6715a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91a0babf-7e1b-4a7c-b7ac-9e60da0adcff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19934a2f-7cc2-4b6d-af06-d65ab8308df1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18b13b7b-42fd-46d2-8e79-dabd2d451448</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aadbf458-914f-4ff5-9e30-8b1bc7c8b8ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7cbdcc58-6957-474b-bcb7-b2d44fc959ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ca3cc1f-055b-452e-a861-a886ce98f28e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ad9697f-7b98-43fa-928c-d8e5657e04ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e678928-a354-4ac5-930d-04d2c9c21c19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65230914-aa8d-4e0e-8225-af42f2ce8d39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee40c82-5bcc-4fb6-b309-48eaec14145f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25b8435c-a7f1-4b4a-8da4-88a08a6cde36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b8f5623-c470-469a-ad12-3701cc5b3cd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26a9a23b-c60e-43cb-9a8d-6e131b62aea3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/InfoLayer/Features - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49c94622-992a-4915-991e-70ac5f581bfe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>225042e0-af95-4834-9585-fb878728923c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/InfoLayer/Specs - Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25bfe438-851d-44c7-9070-93c39920c1f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f798ac8d-e079-4af6-b140-a711fce2ed7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Styles/Correct MSRPs for each trim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfb15e75-899e-48d5-af9f-2be69a018de9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60dbf6aa-e2da-4bc0-af02-fbc4f27383a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Promo/Correct MSRPs in overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc0ad99c-1193-44b5-925e-36bd8129dccf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b6c36c3-f19f-45db-83e4-c777b2c081ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Styles/BYL-Accessories CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb9dab58-b95f-4855-87ae-4b91a6ca47a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a663d0d3-0964-4dcb-838b-756e77d6f763</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/AdditionalInfo/FAD-Owners-Brochure CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>416f354d-3e6c-4b73-ac3a-8401b9477c20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0379f4af-d678-4ae0-84d0-65dd63a2a0cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Global/External links should open in a new tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c749ec-59e6-4a85-a78b-c114428b372f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea65ff85-206b-4c17-9627-4795f215d6ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/Select Visualizer Model-Style</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d6a9e0-b08c-4e17-a10f-79151cbc874c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53f609e6-1957-40cd-8e59-d3447a4d4af6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/Set Exterior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>075a6378-b6f9-456c-97aa-209d3d1f2537</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6547b0f-f34d-4f77-bd68-8c98badb78cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/Set Interior Color</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bac8b880-ebb4-4508-b95c-75a7c10505b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe51ac17-4549-405e-8e7a-717196003c22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/Set Wheels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c810b17-61e6-4ffb-a231-81789f45333e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60758fca-6943-4230-a636-e4ea71bed2a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/MessageBar/Module has rollover state, and links to signup form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb569bb6-791e-4610-8331-5f8e67a17482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eacd64be-54c5-4a9d-b2cc-1cacd836ad2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/SignupForm/Model Newsletter registration info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56d079ff-134e-4a30-8aeb-ac390c2e511d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
