<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UXh</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b7ac27e4-609d-4f00-bb6b-f2c7270620d2</testSuiteGuid>
   <testCaseLink>
      <guid>30bf8b4a-8f1d-4884-9ee4-275a3de9e5ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/All Features CTA - Access all Design features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b325d9b7-eb17-4d9e-83de-7308bcbda4a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86fbd73e-d4f5-4fdf-a25a-b540d63084f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fbc8f41-8bbb-48cc-ba3f-65ffa52e5b23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c7093af-2cd9-419b-b0fe-898c3c7cb107</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Gallery/View Expanded Gallery Overlay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>461492ed-6266-4266-848f-67d7aac24055</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c102986-2740-4eab-ae22-9acfa6894e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Gallery/View Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcd2ccb4-b641-4222-975e-a09c43d0ea26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eab7d77d-ffcf-4127-a8d4-5eb826695f89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Hero/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8b62e50-14e7-495a-a2d5-6003c174539c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09ba73b7-d182-4dfb-8f52-617649f01010</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Hero/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eee76d55-d099-45b4-8a66-fdff0d424844</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>721733b3-c3cf-4e3d-b630-806ffd6a502d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Hero/View hero content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c1800e4-bc50-47b8-bf46-7888faeca971</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55328b97-e0d2-446b-954a-6512d3f3ace1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Offers/Browse Offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f6e5c7f-1ed8-4daf-aa25-9d2569c96759</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c783b98-d841-4246-a9d9-d2a40c61b8dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/All Features CTA - Access all Performance features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9d755a1-6655-4ca9-9b58-5473b3646a7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bcc342b-d280-4f20-a4d2-2b785d6a9ade</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb7cba92-cbd2-4b10-9d81-895579c25702</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>567fdab3-e71e-4d00-a800-89263e57e9da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Safety/All Features CTA - Access all Safety features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb22489-e66b-49d3-851d-6f1285faa8ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d09b221-5bd8-4e11-be57-d655b65e6ef2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Safety/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf16f642-81e2-4cae-941f-16b617f55d97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>578889f1-ee77-4eb1-bbe8-44cd8d389240</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Styles/Styles-Specs-Packages CTAs lead to target URLs in IL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73941c72-0626-4348-a291-ba19ff6fd988</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>589da3bc-db8a-410b-9541-7fc6fb0d210f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Styles/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af28f1fd-86ef-459b-ab7b-74910ed589b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5627e149-a4ae-47f0-8acf-07f3b8a74aef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Technology/All Features CTA - Access all Technology features</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c2d1dc1-a858-4d61-8ca1-fc84e540eaa2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9886239f-05c7-4fb7-9247-27de53d980aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Technology/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b380e55e-d442-4445-bf4c-025f487a721b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c51c1f2-006e-4fc1-b700-65cd2b314d47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Visualizer/View Disclaimers on Tap-Click</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ddd486-47ad-4cdc-93cc-cd9519d9a4b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bde3906-0260-4d9c-a05b-e32243d488e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Subnav/Deep link takes user to pre-determined location on page - Signup Form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c456db56-d6f9-4767-8a5d-0bd68c92856b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
