<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>map</name>
   <tag></tag>
   <elementGuidId>0308d139-fa00-4b54-98ff-61979a98812e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[style*=&quot;maps.gstatic.com&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
