<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ES - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9671f61f-3895-4c49-8cad-1066f6b58b74</testSuiteGuid>
   <testCaseLink>
      <guid>5913255e-330d-4edb-9e75-ccbd46fb6f0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbaa9ef7-7d42-44ca-a89e-4a84a0c18960</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1c03020-ea3f-4028-b235-dd952ad28735</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>589f4fbc-e1f8-4aa8-a3be-160fa7b334b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0184e24-cd8e-4b0c-8ff5-574287cf82c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9293c71f-b7a8-4b55-a315-5e35f89b1eca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2eb736e5-13e8-4315-ac97-387031a36b60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faf83533-fa25-4f2e-ba7e-805386984a1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f80d4be-b8fa-47c7-8d89-22b424c4cafc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340c326-cdc6-4d87-9a58-e993d71e8634</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fc92bda-ec1e-4c90-a6f7-fcc4f60ae1dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41418067-dcfb-469d-802c-af83534f5e9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68088e93-949c-45b0-a8e1-6a8e6bf05e40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d4c79eb-88d3-4978-8b03-30ea8c0725ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2115eaaf-e8bb-465a-9644-956ba395c357</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7600614b-219f-4d0f-9b0d-23a14e508d3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d88da2c4-4125-40b1-bcd3-416b7977909c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>168dd2ec-3bd6-44be-ad66-c643037fc1de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c10f5541-6e14-4a1e-9987-351ff5d7c204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4622e2e6-c435-45ce-be47-97a82d6bdb1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfd9b199-0622-4c62-844b-68266e2baeff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29cfe943-e555-452b-b5cd-a31e1b450a43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1f14cc1-d68c-4473-809d-34be581dd346</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/ES/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03e50d2-4d52-429f-b3c2-8702d2fc37da</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
