<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GX - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bb0072d7-ec14-4f78-a10b-bef76e3195f9</testSuiteGuid>
   <testCaseLink>
      <guid>2fcea83e-2cd6-4c37-a211-e248e0dca856</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcd2fed0-4b25-4de4-a435-12b5a09a4c2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d95770e-4c4c-451d-9261-2cceecc1d4fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18228dc-574e-427c-88cc-e114da97c1c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd4df135-c6ba-484b-8501-6695e7805ebc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3d62afc-d984-4fc6-978e-fdae459d0c0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0d50f89-0056-4f42-9fc0-3281b039c87a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>442af59d-8d78-4548-bea8-c3f075bbd7ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dcccc23-2057-48b5-980b-85b0bfcdf7bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6f59065-06d0-40ab-b2e2-479c5ff25c54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfb4b0c3-7c93-49a1-8a30-2cfdc6d12bd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c93636d-5039-4115-84d5-2e1e5b6babd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0e11a94-f3ed-4444-9cd3-274ae7b1f343</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b56bc4f-9644-4ed3-830d-99f32b073e0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33be82ab-708c-4c82-baed-0687b2abefb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41af0865-2af2-4c0f-9215-7cefd37e86e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68e9fe01-abb2-4db8-9ae0-83b59389a8b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0dbb979-6e4a-4a3e-b3f9-1d2284d4372c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3e24642-eec4-4b2d-b5a1-e7debfdb28d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a328152a-9169-4a7f-b402-4333255d0976</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71908019-0ba0-4a98-85d2-2a77e20084ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce85efe-21e0-4727-a23d-88a46fea2fc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f110fa0-0e62-4c98-9403-dfeb474eaa5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/GX/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a12b1ce-9907-439a-adb3-cf46d565abe9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
