<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>IS - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4a819d3e-25ad-4945-a3e3-15994156824d</testSuiteGuid>
   <testCaseLink>
      <guid>79b9469c-574a-4173-89e4-82434970e53b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec7d379-9f91-4ce7-a63c-9f7ad46f21ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a87136b-5143-487b-9791-db4711d21688</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dfb0ed6-25f4-4931-9382-7274df6b5339</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d073141a-f514-4af7-a0df-8d80c2366cf0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d2e841-e82a-4d83-8071-34c0e1a93ebc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>443ee784-2df9-45eb-972f-e4352eb202a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2410370b-442d-452b-b140-e28ef9b54513</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7de55164-adf3-40ee-ac4f-e45cab8f69cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef2bf51c-6cec-4c9d-9337-e4971cede4a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08d2551b-191e-4b19-a6e9-9583997ce88d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4843f79-0ba6-4136-ac8b-acfbed0d2d44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b47e327-9100-47ac-bf84-1249e4c811a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ecbc3f0-114c-446f-bc76-b95dad95c43d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ee1641-3e8f-4e1b-b61f-11e5e31b5a46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fccf1b37-ff7e-4c61-a9c1-f632644356e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>464e1f08-c22e-4731-8ea2-9d2bd513437d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68234b1a-eebb-4334-9c79-a75f140d5729</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b27c65b9-507b-4edd-95ff-9325f444c0e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d099da8-e9b9-462e-9995-7af666831330</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbff3809-0e0e-453a-892e-50ae36601c5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30a213fc-0ff7-4ed3-917f-55a5d81cd929</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b2a58ce-d6be-4920-8fde-3fac31ce2384</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/IS/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e025df9-db15-4e58-872d-d20705d806e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
