<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LC - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b2e013ef-a009-49cb-a139-b1d37592fc32</testSuiteGuid>
   <testCaseLink>
      <guid>198ad639-5cf3-46ee-87e5-159b7ca36cf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7a65fe1-ff08-4302-9f5d-f651b8faed73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fdacc54-0f71-4faa-8297-7e0e4f325bc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fff29e78-1a5e-4b85-a452-1a1f750966bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38648848-01d0-4c08-81e5-97428042564c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89edf94f-25ec-4189-9b16-4ec040a75e42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0db513b5-68c7-4927-9dda-6865d7fa6ea5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ee2dfa-c663-45a1-9006-27054298b091</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4eb518f-1cb4-4856-8df9-45fc74d9ea95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acb4df93-4652-4d1e-b7b4-921ad8512bc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fd4de47-ea19-4aa3-8b0d-271d2af97150</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b368e906-63fb-45ba-b84f-99d50cefb3f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90535500-cc54-4c01-97c4-5b3566ec967e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a713a66-0244-42f1-a3c6-854dbb552dfd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6856f140-2eca-4b36-911e-baf79ec47450</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3453d3c-1b73-4cbb-9410-1e7b269f1070</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e943520-6763-4663-9baf-e18026467afd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5de476d6-57ae-4c61-afd6-80fff35ee847</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa8f3c67-66ed-4307-9607-4b288e191d64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e4755bd-cf1a-40cd-b4f7-e3b099e876ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd3111a5-cd3a-40f1-b78e-bd7a51b6761a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c2d155a-0940-4bc7-a4af-cc1b1603e9b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecf2b5a7-d456-4049-aa1c-7d1e8730ea4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LC/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a895dd7-281c-4512-9f5f-a8b5da448548</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
