<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LCC - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2fd1e136-0d82-4448-bd23-d812bbeae0ab</testSuiteGuid>
   <testCaseLink>
      <guid>3167af5f-868f-4be1-a6f6-0c9882631b30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe905c-1ed3-4c8d-8868-51c83d30fff3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31f0b3f5-d2b6-4f33-8e3f-493bac43f3b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43ac772a-1788-4e68-92a3-6be933ea594a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f768dcfb-f6fe-4e3e-bf63-b1349a3d2b66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0abb9782-bbfd-4038-871f-7b4201e37ae7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6589b466-9e03-4e1c-b23a-939b2ed97371</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0030734a-7a13-4b75-b3bb-af086ebddc24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba570d60-c5e7-451e-b7c9-ddb9c759ae03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e094e6a-5cfa-4c0e-9c7a-877b59b316ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7c4a770-5b66-4b62-9ddc-1f74f8bc99ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6278ac84-207b-40fc-9370-07bff87eb8af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0920caf4-bbd7-494a-9878-3ccbf73737f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e50616-9479-4dc7-b7ad-61738d9c2817</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb97e25f-856e-4ff5-8dbe-7d80894a53aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea284a14-7dfc-4b3d-8f42-3dce6591094b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95147b26-37e1-453c-b86b-5acef7914b36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9abddcd-5777-4ac6-8dcd-ac4f8ff5b193</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a92c24ed-aa7a-4970-9b1b-192b0b670bb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6d0ea8-b12a-4414-99f6-6eff750644dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae0414a9-4149-4ae3-b316-7198fa6ab7f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32b5e000-ed78-46b8-a1c2-10aec70716cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47a8be1d-975d-4067-9e10-572e249ffb1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCC/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd9e45ba-633a-4d35-851c-3be031bf48ae</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
