<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LCh - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2d220ef9-df37-4977-8759-efad1f455a34</testSuiteGuid>
   <testCaseLink>
      <guid>affaeeee-adb5-4b02-a6cb-57621e33a3eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf76a076-e088-4367-8a5c-9525f6aaa6e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d16c6d68-5a6f-4915-812c-954e3e8744de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93b1570a-05b5-4860-a497-c8f81d86831e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdfec411-6ec6-4b58-a788-258d050dd330</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4cbe616-8995-4149-87be-1a7df43e19eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a648a0e-20a2-45cf-a115-cc19e96fc852</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9e75479-7d6a-405c-8229-f1c0ed249359</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af8f61a8-3c8f-41d7-b337-f707b673e7f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd113f19-a3d7-4f0f-ae09-519f1b487127</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cff23f9e-14b0-4f82-9272-54527392c3e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f46b21b4-6650-4006-bd4b-a3262c314780</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c25b2c7-5d57-4dc9-bb03-b820b5b790c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b30a26c8-9296-42f8-a58d-c7f30511c0e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88b51467-4cf1-48da-b9d4-d892289a3ad8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67fe9b0f-ff6d-4ece-bbef-03b668b79080</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec363e2b-5bfb-4768-9540-5b736bfba5c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30950bb6-ffa9-4e03-b467-0bb62c3bbd06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>399f7b7a-8327-4b61-941e-6be1fac6a0bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdcc46a1-4139-4a34-a9b3-07b7084d138a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>091acbf1-a0d6-4782-916c-4e8674ab786e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b59ae7-6679-4d99-bca4-8ae0281babaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b19afe06-2e88-4efe-a4c0-c29d0d064e58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LCh/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc33e870-ab32-406c-935c-f6e6ee784ef9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
