<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LSh - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>af8823ef-1823-44ec-9643-dda87b174e6a</testSuiteGuid>
   <testCaseLink>
      <guid>58e12168-d9a9-4e37-84e0-e37541357209</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faff9abd-f03a-4fe1-a4e5-c86dd04c4232</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffd6cdd4-dca6-4a17-be6c-b9bfbaf8c153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e45f138-f54a-4479-80ea-b94ceb8bafde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebb587aa-54a2-4eff-9c2b-36246b328094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>979d01c8-1dde-41c3-a0d4-83457d4f6db3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45f3950c-50c0-47f7-b1a4-d4a8380f1798</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee96c115-35f3-4a69-ae86-a86c7269a8d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc1addf5-454a-4b0f-b224-77a52bdea5ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50283f9e-01ad-4ada-8f09-c89ae35afe9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a68aa3f0-17ee-4aa2-8547-6d85d0ecfb6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>272d5b7c-b6bc-4f93-93b1-cfa5460206f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df65cec2-9f14-426e-8c42-56efde9e5507</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30fd0a47-f3f0-47f7-8006-54291a5f2cfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0214af86-56de-4198-a546-91ea54e2ccd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>401d6ba6-ee6d-405a-8157-0f0e685b5cd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac405f87-28f0-4f29-a02a-6bd4122933c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>373a44ca-c82f-4c08-9d76-f329dab62f38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb4e4b2c-0ff7-4db4-9928-2ab67ede17fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf06eb6-b461-4e66-8d73-72280ae32106</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de8243af-2e6e-439f-9631-ac8c0e771bf2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acc073d4-e5ca-4c3f-ac91-f6c5d4b0c60c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f72f197-da0e-4bfd-96ca-c4749ee9dddc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LSh/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f2ee5e-8ee9-4123-ad9a-aab5f022f2df</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
