<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LX - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>432359e3-220d-44c6-bf65-7f69589ecf73</testSuiteGuid>
   <testCaseLink>
      <guid>2b5538c9-7973-4985-9b7e-43a4995a1255</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18a381e8-c9b0-4f71-b4e1-745d39967ed2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f8bf3e4-1b54-4dfd-ae4d-8b056d3d1da4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ddfdf77-cb4b-4037-9e95-1739b747995c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b56fc8d-baa0-41d5-ab05-f5e968defba2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f42d22f-f912-438e-9363-9ea6775f7fd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>450db862-64e5-4e75-acb8-466c28e970ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a93ab16-5a40-4302-acb9-c6ea67260bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b355ec17-612d-4592-a3d0-bd610ca3b616</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7665ac6b-2f73-47dc-93ba-6642e4a418b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bff4f94-6818-4e01-b62f-71cb4e6e0ac6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63776fd9-cbcc-4a47-87fd-cdd5bb8b0196</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f67dfb1-0fb4-4c33-aac3-4d15d2377ddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dec7e55-0b7b-43fd-a1c5-29344fc287fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90b155eb-a181-44df-9c5d-0ad3bf19d540</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc0ff056-c37e-4bfc-bfc4-f087b17742eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eba60cce-5f23-4ccf-a2eb-7b3eff39cc6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>801532c3-08fa-4f68-9bf7-92a156de9ac2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fe8f6d7-3bfb-485f-afc5-87c02a811f16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a761073-f9a7-4ef6-bfb2-c23d139d8152</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e55eb79-8adc-4c4f-b616-d629ceef8c9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1060b836-444b-4cb7-b804-4bc4759d1ec4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d0ca591-a2d6-42ef-a50b-ff17d6e8fc50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/LX/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e0371a-006a-49e8-96a3-9047e0c7ac20</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
