<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NX - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>84a48a43-46b9-4514-ae17-0a7a88406a2c</testSuiteGuid>
   <testCaseLink>
      <guid>d30fcf97-a9ba-41c8-89dd-189e49b3d6e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>110d602f-1e40-4f69-a7df-70c93089db90</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92ba1095-4262-44e6-b3a4-af572483e611</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0668b092-05b1-4ee5-842a-faf25607f3c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2068ca3-acc5-42c7-988a-5da0d9554891</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ecad693-31ac-401a-b4f2-009142a1415b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a04335f-a2e7-4017-9cd0-a9224f749825</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af6a9507-552d-4263-b5d5-b0560113c331</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aafc1ab1-71bd-4548-bef5-90b9d719c501</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>832b961a-c910-4b6e-b0ae-e3592aa21c49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c60406da-38c9-4fd4-8258-104b5356ac10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5371cbe-05a6-4430-be05-27d36fdeb4ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9988bdfe-f4a7-44b0-bb46-302317972d5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f62df8d9-d990-4641-b80d-55cc88321c54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0676700c-1ce5-4527-8ce1-6f34e37dc7c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d61eb5-d6ff-469e-8936-0a8b972d60ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>282b5533-97a4-4569-9d5d-850c9904db59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f68ca9ef-c072-48c8-acd7-0cd97fde7f6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f40e284f-1356-4524-9fdd-fadbd95ed4a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f26de5aa-7878-4536-acde-7216937e8e11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>687caa40-d455-4ba6-b133-654b68dabe2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab6f25c0-f18b-494a-bd3d-8c45aad273a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6d722c1-f313-4013-939c-41162c625f3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NX/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e3b27dc-34d2-429e-83ed-93e68151a58b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
