<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NXh - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3703df40-8e6b-4161-8256-ed1a7f6980f8</testSuiteGuid>
   <testCaseLink>
      <guid>2bdef8a4-1ba3-42e4-95db-0b3b7a16380c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>369be983-f15b-4338-a590-e7c1e7e72ce9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b659897-0ee7-4034-9e6a-5dbe5dbf72cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dd53254-55a1-4dba-9350-df332708af0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d628710-e915-4093-a79d-1e66eb3d9c14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2995f3c7-5440-4889-ba48-9332b132aca3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fccb5737-6d8b-4b62-ac11-1fe36dfeafa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbb5980-5e8c-4296-be93-1fe795a578e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>728a87f4-d95d-446a-a72c-73413e123bd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65681b19-ff66-4e65-9c17-ba23f2ce04bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0192cdb2-d719-4beb-a528-deea5261864c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f786ddd1-fcb9-4456-bb53-e0cdf4b78e48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccbfdf9a-0ebb-48b6-b457-229523fd515b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54c441c7-d883-4e7c-8afe-250a13f76a12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da85292e-bbd3-4a45-a7c3-5b11bbd99547</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e30257e-fd5b-4ed5-982b-fb46241d2497</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97bc1ca0-63ba-4e69-bb20-2327813ada83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f60f1baa-7d4b-4a32-9d5e-249e83b4e811</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67bda3db-6c86-422f-8637-64ebde110f66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f1c6321-34ef-4924-b6a8-54c2ef15733b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>647152f3-5c0f-4d8c-b09e-5acc2a5cf1c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3c33499-e371-407e-912f-77bb24f119b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e855410-ed12-4cdb-8d20-fbc840cd2e59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/NXh/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>184b3989-a236-4a24-b1c6-6216dc5dee84</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
