<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RC - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9ec5fd4e-1bd0-4bf6-981f-ddca77ec4fbf</testSuiteGuid>
   <testCaseLink>
      <guid>6058012e-5d7b-4ce6-a230-a9007cd1215f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>052ae4b3-aa57-4bff-af60-0cb0f63c9829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2760b8f9-78a2-470d-9783-983358345d88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58cab2d5-a9c2-4e33-966a-6afaa6c42ccf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd818273-e17b-48de-87bf-65e88dd84f48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e0a9708-dbb4-4a1c-ad4d-beadfdea9a44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54a9a9d9-a260-4ae5-8f20-c8b277c06680</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d0359d3-bf53-4fc6-91fe-abfb3350d21b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6383b00a-5e41-444d-89fb-f60939cbd94d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18889585-8e26-4f3e-9927-58dbe9aec7d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7137f0e0-a11c-444a-ba1a-84f17fd9972e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb327989-6691-477f-9566-eff84728e515</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>530b849b-34aa-439e-9d71-636aa302a6eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15455739-e913-4af6-ba1d-46a0e59a5bfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>345d762a-0d68-4d84-96e2-dc905f78bb6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b35cbcc-12d3-4a71-82ed-85050ccc7a4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63342f28-055b-4812-9709-f9bdeaaa63cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8700d583-e373-4b72-adef-e3f2f7e11252</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f6610c2-7ea2-47f5-9a3d-721b560493f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bfa524c-cde5-478c-a652-a83845f1c727</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d70476c-3762-439a-91b3-c49d90f8313b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bb7e207-6c56-4ed3-a86b-0b0d9396d01d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ef7ef36-22bc-4acb-9c0d-35b1f0ac726b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RC/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b514224-fb33-4bff-8b93-ba433c77d47c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
