<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RCF - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8d9c6b25-b645-4f47-ae01-820d1f42e47d</testSuiteGuid>
   <testCaseLink>
      <guid>4dde446c-c06a-44b1-8dba-f4d5fa980977</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee6b0edf-cc95-41f4-8c44-7546d46a8653</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb73397e-1ca1-4c4b-b41e-cc420a7f79db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>660daf8d-e6a2-4226-98cc-816c69d29906</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b381b252-ccde-4bba-aa11-ee168c6f154c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97e84d5-5026-452c-b05b-e9b84c879067</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d57f7c5-3d88-4451-9a2a-9c923d0f99a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da49c21-23f0-47b6-831e-eedc9c11efd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca2e0888-8755-4d0a-b6df-fd4b58ee77cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817148c8-ee61-4180-9efd-c3d5e2af6c81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5095b572-099f-464e-abe0-67eb45bb7fc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aabfeba-15a8-4a64-95cd-fba67b91bcc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ecabe55-1882-48ab-92a2-4a3f17b5c727</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d109a770-cb90-47e6-a30a-136ac78bb01f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e846e00c-5eae-41b6-8495-09e20bc8d610</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba72920-17eb-4d5f-8477-7cc4fae2cef6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2108ed86-9dcb-487c-ab38-daebb4325c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26db1d0-a8e3-4a50-9702-22f2f1121634</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>518bea8b-d65d-4ef5-81b7-8af54c36074f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a528e73-6588-4877-81a9-105f42ec6f0a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e91bd824-79a3-4c5f-b870-71a1624a3eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25f44349-0623-4476-b849-0ff38ceb666c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c600290c-b664-43ea-8800-aa864747261a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RCF/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c92beb5-d91b-4629-a9c5-5536e985e93c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
