<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RX - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>26aeb7d4-01f5-48e9-acb3-c8ce682a9316</testSuiteGuid>
   <testCaseLink>
      <guid>f20dc136-ddc6-4965-85bf-1b22b255b376</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fe490eb-3a8e-4532-abf0-45a23cf96d66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64289482-dd93-4362-baec-d7a4ca119ed7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3538daa5-e58b-4f28-9070-2f803c5881cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9166e151-84f1-407f-a7bd-528129e57f6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>621642f9-2749-4e57-9c79-b4b675d3a4da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cde46d8d-33ca-4620-842c-9fe58b474801</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a638795-e85b-4e6c-8976-1d96632703f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29626e8c-abb2-4557-83b3-484648313ffd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1f24f5f-1d07-4660-8379-746b695b32ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>112f9440-e287-473b-b071-ed61da151ccf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd2d5831-acf2-49c5-b0c9-2aa506324549</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f82c9ca-2881-4a09-92bf-61cccf29bf32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c806cd8-ada6-4028-b6bf-ef5a0e752bb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>723f8b6c-17c3-4e49-8f75-98a13980648e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e8e8bd-10cc-4162-8c47-404ecda81fe1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14f8689a-e498-4c76-820d-81b7d80903cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b2c00a-0d2e-41ab-a021-a8c7aaa57d62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acf536d3-dc6b-4f26-94db-f04ef62a8637</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a04b465b-6300-4910-97f5-abb13d239fbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>356610fa-8a2f-418a-bc8a-e44b3b89297c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f850c36-0d0f-40d2-b5c6-110f2e785020</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d523b5d2-cc3c-4d10-ad71-762bb914ef89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RX/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d025ec7-8c9e-4dca-a717-fe8c1ebe2445</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
