<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RXh - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d3251841-9fa9-4939-b174-1de21edbace8</testSuiteGuid>
   <testCaseLink>
      <guid>655e21b0-f175-4476-a822-595019cc6b69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7db2fd7d-274a-40a7-9146-76e0b05ad5a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb35b924-b0bd-419b-867b-aa46b44f58d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51fd4bd1-a49f-405c-814b-f36f738763c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e1d00b8-c9d5-47db-90a5-6ed47ef7687a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36294e4a-a0a1-45a6-945e-9f7f2874baa6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42b4efd4-0388-4e32-a70b-72b9fa461503</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d679050-8b55-4651-bff4-b364bf5155e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37f449d2-0eae-418d-ab4c-eb81165a90ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c45655e4-8027-45ea-97da-810981c52848</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66c4c3ec-710a-4a2a-b258-35df737a9cd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e7093c-8244-4a5d-86db-47f619ed5124</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cad25119-5df4-4050-9449-b82cdb313f95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b99989-f5c7-4d0f-9d71-0d0fa30b6003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>601ff3a7-b4be-4bad-ab7c-774f631d8600</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78b1e7d9-c1bd-4b06-bf38-830e9dba3722</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54272000-f306-4f07-8d3c-8e4779560fc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6d78a48-d5a2-496b-b701-aa185dfaaf11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9569941-1f78-46d1-8480-6d2cb05903a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f887a5-7f98-4741-9ca8-96ead397b1b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87617e67-27e9-4cec-b4ab-96f2d523ed02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bc4b314-a04b-4fc5-a313-f4a15f9e8446</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>001c8c8c-d803-4af6-90f4-d6bd6c976ad8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/RXh/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef3d4559-41ba-46d3-846c-5b1cac5286c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
