<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UX - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d4eb8e9c-b6eb-43b7-9e8b-a2605b94d796</testSuiteGuid>
   <testCaseLink>
      <guid>47cb2cd1-54ed-43ec-a5e7-9fd8818c81ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8552fcc7-af8d-4111-9ce7-b2b4969bf118</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad7b819c-ba08-4961-b2cc-ca99a305c822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>546eb3d1-30f6-4c1c-b1a6-c3575023fb9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ae40090-5c7e-4215-af14-477c4b2203ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f915bb-1b36-421a-8d44-a0fc0d806b38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fede9940-4cf4-4e23-b545-da725e74d22e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93ff72c1-7678-4a9e-a609-221bfdb3467c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f1cc74f-9edc-4590-a656-98330dc6af40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d3725b0-c190-4d5c-ac85-b0061a75afbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>996c9cd6-38a5-455e-9398-243743b287b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed213b71-76b4-451b-9a4b-59a4135cfef9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6585bf0-dd2f-4fa6-8989-3b567d904348</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c849bc1-b564-455f-9fe1-00867b8ad0f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d6d0c36-a1da-4cec-8088-ea259bb84fdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5cc5993-63aa-41ae-a160-0942bacddec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f231bca2-8f17-4c88-afb6-9d9922fac66d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ef096c8-3214-433f-b5a2-27bb2c98e005</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e60f0b9-5a83-4bae-83f5-eae8032c6b22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10e32ac-87fb-441d-8e6d-7e1b0c3184d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93579724-ea29-4707-b5c2-edbd3f1c79f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>874926ff-ede1-42c3-9a08-abc0c80f5a79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>413ce51f-5a4a-4954-8cc9-ebec46892f23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UX/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b9d0b5f-007f-4b69-9022-ff0ee1788ae3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
