<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UXh - mobile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>aeeaca05-0644-4b36-ac07-ed0128d1123c</testSuiteGuid>
   <testCaseLink>
      <guid>7e13f81a-3f23-4f50-b5c9-250f88db1a7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Hero/View hero content - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e1d8a46-f5e4-4fd3-bf7b-7f9bd14800fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae5b5b49-e58e-4aa8-9027-b3339d7033a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Technology/All Features CTA - Access all Technology features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90cedaec-fc23-4c75-a740-d43ee6d821e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c06e44ad-c000-4cf8-8d6e-bd304b782862</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Visualizer/View Disclaimers on Tap-Click - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab0ac3a2-86fe-4745-a86d-28997646fd65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b5619ae-41e0-43e2-95fb-cff3d636561f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/AdditionalInfo/FAD-Owners-Brochure CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff1d4c52-b4bb-4728-b348-14d41343730a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e08eb06-6b97-4a99-8ceb-7b7c2ce69176</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Design/All Features CTA - Access all Design features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f1d41c6-35f4-433d-8240-260ee0878e05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1df612f-7761-46e5-9101-3ceb7be4197c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Gallery/View Expanded Gallery Overlay - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5af0b47-765a-4dda-bc90-71e96a9f82a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ae3612e-8afc-4405-8df9-c84f887e1962</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Offers/Browse Offers - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4025fd6-0dfc-44da-8747-c349d34b4d65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f98153e-1f15-4506-8206-219a00f567ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Performance/All Features CTA - Access all Performance features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f6e3d6-c5e9-4e2c-babc-90df2defec8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2cd8b11-f974-4657-b09e-72c8aca93c1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Safety/All Features CTA - Access all Safety features - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16193476-642d-4537-a51d-87844e8638b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>525fa07c-2f46-4e78-ad49-c503a7c5d4a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/SignupForm/User opts in to be contacted - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f36fb58-4a34-4461-ab05-a920d6a654fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14cff374-5517-46af-b4be-b2d347d7796f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Visualizer/Select Visualizer Model-Style - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbebb0a6-172f-479a-8ff6-a905dcac4db4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84b91f66-a04f-4c24-a66b-4288f5ca6aca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/ModelPages/UXh/Styles/BYL-Accessories CTAs - mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f09d746-d9d3-426b-acc2-d9952009907a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
