<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DeepLink</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>092c7e1b-b00f-499f-a6a2-1e95be20e549</testSuiteGuid>
   <testCaseLink>
      <guid>bd5fa9b0-c77d-4e9b-94a1-6ee63072e5e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - model and offer type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bda0604-2997-47fb-b23f-ae3e3e15d3c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34eba7ba-fa4c-4e4c-b86a-759c2d139417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8a6b67e-5821-4c9c-9c61-58e83c2ee161</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2737bb8-aa6d-4d94-9134-6721a36e12e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - multiple models</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe93688-ecdf-40d0-bde5-cddf75a7b059</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c94d8f96-b8e9-4ba1-b3d0-02d021d74e44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - offer type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b2bc110-b880-4c46-ab3a-e4df3e6bfa19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44b8445e-94cf-4f87-9795-2323506ad7f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - specific offer details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a75ed20-e47a-4e0c-9268-87c97528e23a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23514653-88bf-4420-9c6c-c8718c99b7e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - ZIP code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>480051df-b6b8-4d4a-8288-fa8812ef695d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfb741bc-ebbb-4b0f-a536-11f8d09af3e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - shared ZIP code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>919b95af-cc9f-41fa-bfa2-20f0a4557b87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1775b8c9-68c0-4d79-a365-9ae8a9becbad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/DeepLink/Deep linking parameters - ZIP code cookie is created</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3f94f6d-7a1d-4f4a-9d30-a0979d6aa157</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
