<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>FilterBar</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cfc8b82a-cd46-4bab-a2f0-94bca7b8a720</testSuiteGuid>
   <testCaseLink>
      <guid>7e9f8e8e-f4ce-447f-aeca-7785906751ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Click filter bar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab99ee32-a3eb-4a7b-978a-a4427e3b0679</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9fa5595-16b7-43c8-b18f-46b28c844cd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Click submit offer filters</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ece9152-1837-434a-8afb-015077a79f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4d6b721-ba42-4fca-ac6d-19ef6a3081da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>127433fe-88ea-4f05-8ded-a25c90d37493</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ce2c44d-ef72-4bb1-b960-047c0584a5a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/ALL offer type preselected, models unselected</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad461d2-e842-40ae-aa5f-8ad5d31dbabd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>753304bb-88e2-4721-9310-b017613bb8c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Filters remain even if apply button is not clicked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>517817ef-f811-43c9-af13-10e7923bd41d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cdace372-c3fc-411f-927f-248c7cd703fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Select offer type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7207e2-f823-4201-a541-520be1212081</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
