<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>FilterBar</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cfc8b82a-cd46-4bab-a2f0-94bca7b8a720</testSuiteGuid>
   <testCaseLink>
      <guid>7e9f8e8e-f4ce-447f-aeca-7785906751ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Click filter bar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab99ee32-a3eb-4a7b-978a-a4427e3b0679</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9fa5595-16b7-43c8-b18f-46b28c844cd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Click submit offer filters</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ece9152-1837-434a-8afb-015077a79f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4d6b721-ba42-4fca-ac6d-19ef6a3081da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/FilterBar/Default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>127433fe-88ea-4f05-8ded-a25c90d37493</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
