<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OfDe-SMO-ZiBa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a7e1a246-5cc7-4c05-b6f4-f70a39d6d68c</testSuiteGuid>
   <testCaseLink>
      <guid>887b5dc3-8d8a-49d2-8f87-ceffadac680e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7b91a6-7d39-4b3d-b774-8e51c782cdd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7460734a-c769-4db9-82c2-87a57743f8d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Dealer card</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c48220c-db9b-4286-bf2c-fc35973739cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26c08408-a363-4b4d-b5a4-1a0dc21ac57e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Key information is displayed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a2cf8e1-0eb5-4564-b3dd-8a255f1295d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81368d7a-1acd-43dc-bfab-aa18a97321c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Offer-Data</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50cd5805-921e-46cc-b43b-f6e2cbebda51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f8fda57-e6c6-43de-b3d6-f7fcfb41ac97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Change ZIP code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6047b8-991e-45c3-a86c-09e6af9721ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>815bcaa2-7fca-4926-a07f-ee7c65aec0ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Click X or Press Esc key</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67835f62-45f6-4d22-a49a-1d9200576699</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>526b0f10-b530-4a8c-b33f-0758d3035f35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Enter shared market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce355d6c-3079-450a-9fbd-326cde0a3d0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71922d91-65fc-4037-9e93-b1e8316107a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Hover over options - desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4951f737-3e03-43a8-a047-ab502286c3c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91040002-286e-4eb4-8c86-0502a1aeb931</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Select Market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4c6b3c9-5ab6-42ea-917b-89cf6a04887a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5abf0193-7a99-4e35-ac8e-5d3ede9a8154</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/ZipBar/Enter-Submit ZIP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec24fe10-3ae9-487f-b393-bd5491ca5040</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27529bfc-11d2-49c8-bfdc-51e30c1dae4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/ZipBar/Location Known - Default State</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d65734e-7cbd-46bc-a094-584c06a7607d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f32e1ed-3e53-488b-9bb7-6a9827f76942</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/ZipBar/Tap-Click CHANGE CTA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a519ccc6-0450-4535-bfd4-59e11daf8186</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
