<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OfferCards</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a1590b13-7bd1-4752-a5b0-3479530062b9</testSuiteGuid>
   <testCaseLink>
      <guid>ce4d2c66-e1e8-41cf-ad6f-f76f9b9ba93c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferCards/Carousel navigation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec445518-a3bf-4528-b202-4998d9a2c0ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc61b556-0c66-4cc8-9c13-8079da491ce6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferCards/Offer details drawer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9eb0793-bbe7-46e8-85aa-266733304daa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>268944ab-3338-495a-97f7-e2b8f748a19c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferCards/Title placement</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59e19bf0-a3d2-4690-9741-616fd3aff72b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
