<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OfferRowB</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ac0a255d-ab34-4413-9832-8cca9d16cdbf</testSuiteGuid>
   <testCaseLink>
      <guid>7b387e85-147d-4921-b85f-e0ca32e66bac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Build</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15b122e0-388b-4f9f-b8ee-0410acd42858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3080bc6d-0c04-469a-80db-23d0bd6dc85e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Build - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81807cf6-1e4e-477c-af97-9b6aab77e457</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2977eb94-a219-4a0c-b8ea-bf919710e38f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Build - sedans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd2b04b5-01a4-4cba-970f-c9c5d7bfd173</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ba62fb1-1664-49f1-9550-40348d8de72c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Build - SUVs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7408dd9-6f99-4b17-845f-034288a65189</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8880b5d3-7c48-477c-8968-f55cad6c9ffc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Dropdown functionality</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab0c12b2-2ad7-4b1b-91c4-00af7c7a6ca7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fea03be1-f90f-4e40-9ca3-11a5428e32da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Dropdown functionality - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4080fe8-46b4-4123-a105-3677eeb502e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca8344eb-eda5-4bff-85fe-1c2c653b5fb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Dropdown functionality - sedans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e426d1a-1868-4bb4-b62e-2b5feb5c0692</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d2b8a4f-dd83-4a87-9729-d4b556f1db4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Dropdown functionality - SUVs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbcf49a-b3db-4ca7-a493-50871bac6ec6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
