<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OfferRowA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b10fb1f3-7377-484a-b91d-36ede0139339</testSuiteGuid>
   <testCaseLink>
      <guid>51ae3862-83e4-4319-9d6f-fd69d0343db9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Explore - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a2b844-409d-4076-845e-59247f52cd3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0157001-d381-4226-a4de-d6cc044d9bd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Explore - sedans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b42692ee-e5a9-40ab-8bda-9df3978a0eea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7988e7c8-5a24-46c9-9513-0eb4c37f4a3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Explore - SUVs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b93b3531-1b65-4a70-808e-c6a034b95943</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0beb8c71-bef0-4c7d-a21c-2e1e4181f079</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Explore</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4e80729-cd7a-4cc6-af61-323913ba6f9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0da5a8d8-e0d2-4a63-a316-b100d109dbcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/General rules</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f60d344-4c7f-4ab4-9fd2-a09fc8c70d98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>352163a2-6947-40e9-92ed-abea6e6515b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Inventory - Dealer eProcess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a2419ab-ff06-4246-9731-9c529946ded7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>864b32c0-1f2c-4096-960b-94ae8896255d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Inventory - Dealer Inspire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c32210f-54c1-4c2a-8947-3c46ed373f1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>277e3076-0ccb-415c-a2d7-617612cb124f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Inventory - Dealer.com</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bf472e9-ffc6-4ee0-b2fc-19bd675d742a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c86b3de-74f2-482a-a0f2-70585c4a01f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Inventory - DealerOn</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55def867-c9c8-40e5-9f65-ba47a4203aa2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69336c2c-8c44-4464-aa84-5d5988701dfa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Inventory map</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5eaee20-560d-4a26-bfaf-cc956e816643</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>065f56f3-ef67-4af7-95d0-ed44976b3b5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/No available offers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a909577-12ad-4378-962a-33781b10cf99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>553aa975-4514-4a8b-a866-2d98456e999b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferRow/Dropdown functionality - coupes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4080fe8-46b4-4123-a105-3677eeb502e7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
