<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OfferDetails</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1e574285-ab4b-4808-bd1c-8162069cd178</testSuiteGuid>
   <testCaseLink>
      <guid>e30b2884-d837-4754-9b11-3271f2837aa4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/CTAs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7b91a6-7d39-4b3d-b774-8e51c782cdd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da51cee5-e510-4d90-af1d-d4e061d34c88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Dealer card</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c48220c-db9b-4286-bf2c-fc35973739cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05db2483-04fb-432c-b2d3-6d72154b9cf0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Key information is displayed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a2cf8e1-0eb5-4564-b3dd-8a255f1295d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92bf4767-0a83-4015-8a28-83db64367e47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/OfferDetails/Offer-Data</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50cd5805-921e-46cc-b43b-f6e2cbebda51</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
