<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SharedMarketOverlay</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b2e3bc0f-01a3-40cb-ba02-2183580dabef</testSuiteGuid>
   <testCaseLink>
      <guid>d9826b4f-a563-434d-86e0-8294274275ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Change ZIP code</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6047b8-991e-45c3-a86c-09e6af9721ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e773254c-2392-448b-a1cb-55aa8cc4cbcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Click X or Press Esc key</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67835f62-45f6-4d22-a49a-1d9200576699</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5165960-e398-46ad-8471-95c7dfd7cfba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Enter shared market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce355d6c-3079-450a-9fbd-326cde0a3d0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9993514-5c95-4ed3-8c53-3b67ec95598c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Hover over options - desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4951f737-3e03-43a8-a047-ab502286c3c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3628107-d1b4-4265-ac49-5d516809af05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/OffersPage/SharedMarketOverlay/Select Market</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4c6b3c9-5ab6-42ea-917b-89cf6a04887a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
