<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vehicle selector - hybrids - LCh starting at price</name>
   <tag></tag>
   <elementGuidId>79a91fc8-8b7e-4728-aba0-07f45af20f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-category = 'Hybrids' and @data-model = 'LCh']//span[@class = 'price']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-category = 'Hybrids' and (contains(text(), '$97,510') or contains(., '$97,510')) and @data-model = 'LCh']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Hybrids</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$97,510</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model</name>
      <type>Main</type>
      <value>LCh</value>
   </webElementProperties>
</WebElementEntity>
