<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorSUVs_GX_LX_NX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>75185a00-0ddb-49fe-8524-4bd458f94dda</testSuiteGuid>
   <testCaseLink>
      <guid>f349780c-a8b1-4844-aa33-d2a09626b136</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460 Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695e3e83-e9fe-4bcf-b593-22def931cfc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7499caea-06df-4185-8c71-ef8395ca7bfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460 Premium</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>942784df-18ca-4cbd-8aa5-d3c5e74e5b64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b6667b4-2c08-4fbd-8f2f-fcfd132a6185</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b320647-9042-484f-a35b-336c139ac7bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad60cae3-e620-47ae-bb9c-ce58e3eed963</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/LX/570 Three-Row</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb65bc3-40e1-4861-bcf2-3940bb18f59b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65d6d12d-ffa4-44e0-ba12-398df9fbed77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/LX/570 Two-Row</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b3eb89a-5e1f-443c-9515-f049fef87051</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54d2d064-a15d-45c7-82ae-6685d18129bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b9d951d-83aa-4a0a-94fe-ddaa6e74b164</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d855bf56-a367-4072-877c-94d9a0b0b301</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c8185c-ad04-4ba2-a751-dbf08d38903b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>471656c6-0e1d-4ee6-b600-1ec827767019</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fab54be-f381-4a7e-8ae2-57b28a64b885</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2565a1ee-ec65-4400-8241-e612669fa095</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d632d98-1859-4c64-a3e3-50f2e3e43d59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1dc37b2-2d8d-4b9a-bf72-50a52b20d389</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4ba8058-2674-4268-98c4-d033c95a10aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d75b2b3d-df1f-4194-901c-6f1d0606b329</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 Luxury FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc11103f-7053-4091-9649-7c675dba933b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>276278f8-d6d4-4a0e-985d-06318677e515</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9545a87-e20e-4218-96b6-e25c6c1d6e0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06ea46c5-5e96-461e-9fbb-acf4f3c628da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300h Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57340fa5-6061-4bec-8358-614e49b624fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
