<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorSUVs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a340ffd7-0361-453f-9cfb-a3c8a5dbf48e</testSuiteGuid>
   <testCaseLink>
      <guid>f349780c-a8b1-4844-aa33-d2a09626b136</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460 Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695e3e83-e9fe-4bcf-b593-22def931cfc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7499caea-06df-4185-8c71-ef8395ca7bfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460 Premium</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>942784df-18ca-4cbd-8aa5-d3c5e74e5b64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b6667b4-2c08-4fbd-8f2f-fcfd132a6185</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/GX/460</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b320647-9042-484f-a35b-336c139ac7bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad60cae3-e620-47ae-bb9c-ce58e3eed963</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/LX/570 Three-Row</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb65bc3-40e1-4861-bcf2-3940bb18f59b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65d6d12d-ffa4-44e0-ba12-398df9fbed77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/LX/570 Two-Row</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b3eb89a-5e1f-443c-9515-f049fef87051</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54d2d064-a15d-45c7-82ae-6685d18129bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b9d951d-83aa-4a0a-94fe-ddaa6e74b164</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d855bf56-a367-4072-877c-94d9a0b0b301</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c8185c-ad04-4ba2-a751-dbf08d38903b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>471656c6-0e1d-4ee6-b600-1ec827767019</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fab54be-f381-4a7e-8ae2-57b28a64b885</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2565a1ee-ec65-4400-8241-e612669fa095</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d632d98-1859-4c64-a3e3-50f2e3e43d59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1dc37b2-2d8d-4b9a-bf72-50a52b20d389</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4ba8058-2674-4268-98c4-d033c95a10aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d75b2b3d-df1f-4194-901c-6f1d0606b329</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300 Luxury FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc11103f-7053-4091-9649-7c675dba933b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>276278f8-d6d4-4a0e-985d-06318677e515</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9545a87-e20e-4218-96b6-e25c6c1d6e0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06ea46c5-5e96-461e-9fbb-acf4f3c628da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/NX/300h Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57340fa5-6061-4bec-8358-614e49b624fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac89bc99-2241-4739-b3dd-cd9e385b4687</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce0ef2b-ce78-48ee-8e93-404486bb473c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>122ce456-d0e3-49a8-8ea6-cf7ba3e24706</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28216b82-ad97-4b51-8f52-e3ad7f5f0d43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fcc3b28-ec12-4182-be47-8ec3483dcfd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f83c809b-56e6-43c2-b5b8-098b54ab1f01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95a96266-56bd-4643-8467-b8810f94f20b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3d29b21-2a91-43a6-8d0f-69e5184ea24b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d773b0b-6cb5-417a-86a8-f4e00b624c4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350L AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22872797-61d9-4cac-ba68-34e2ffa2017f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88b65ad2-bdae-49c8-b113-571b67fe1f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/350L FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b623cad8-8960-447c-9efe-01555151deed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>355bfde8-1c6d-4f8a-a11c-9336bac62087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/450h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8501eb93-1d39-4dda-b8cb-7777c88f632c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33c356ca-8e3c-4d52-a788-2db30e4be758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/450h F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea816a6-7359-4351-a67e-3907dac63390</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ce694e-0917-407e-95df-3acdad811472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/RX/450hL AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e34a5eb2-c404-4034-a07e-4809cffd633f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6959f462-6ae4-4264-8598-4ac5c687cb29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/200 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b731ab59-c192-4a19-adf2-216863e98dfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0db02237-1203-410b-ba94-44d9bd425f8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/200 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cec3522b-e5d9-4402-aba5-1e7cf3823efd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a3ba5a-a10f-4395-baa9-539848679376</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/200 Luxury FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0693f5c3-4a95-425b-9f9e-084c2dadce26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a42e8282-cb9c-4ded-8ebe-240d6590a0e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/250h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d70106f-bf9a-450c-87f5-140adc313d1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d917bf08-309a-464c-88a5-13177e22f791</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/250h F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f28a1377-5963-4f65-99f8-dd9cd9ab0c4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b5d45f-6ed3-42a8-addb-62ae9d1c5e62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/SUVs/UX/250h Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da4d318-2374-48f0-b544-ee31d77b42b4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
