<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareReport</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>83457e67-4ff0-4944-8f96-99d3ca765fc3</testSuiteGuid>
   <testCaseLink>
      <guid>80ce59ce-9c1b-465d-95a1-b158cf705c9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/ES/300h Luxury-Ultra Luxury-350 Luxury-Ultra Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa4a827-de5b-4001-a642-33cf1d671db0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>881f2528-487a-4108-8dbc-cd1fedb6d60b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/ES/300h-350-F Sport</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5288f1f-ec45-4ce1-a60f-f638a72a5503</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8df04ebb-ac45-400f-b3a1-445e6932c710</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/GS/350 F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f2339fe-755d-4d59-8366-c901761b87b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46160c07-3d71-45d9-b6bc-642406fb0fd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/GS/350 RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03544dc9-11f0-4396-80db-3a2a7ca71583</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>922d2964-7046-45a2-8c9a-364b2bae72c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/GS F/GS F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee45ad1-4c62-4ad9-872e-30095dc41551</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d18893a-f8f2-43aa-8062-5dddc0f098d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/GX/460-Premium-Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dedfe1c-4dd9-4cb4-b4ec-a30da0a4eed3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e70a5888-6489-4970-af4d-5e11a8477625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/IS/300 F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d309d81d-6693-497c-9203-89924e47c156</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8000c146-7db4-4cd1-beea-5bf1422c2cef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/IS/300 RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83de2c4c-4f74-465c-a318-bcdf6803801e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a84b6700-c884-4400-8b06-c0f50fa57822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/IS/350 F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>232fd100-fe9b-4706-bd74-43191893af4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f39a27fe-cce2-45a1-8c4c-e1a4f197cc67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/IS/350 RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e26a96e-61e3-4990-89fb-4a450a3d93c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87c14772-f1c1-4724-abb1-00ba73526249</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/LS/500 F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcb7f715-d24b-433a-b254-5470fb61ae20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>075392db-2b8d-43ab-b48f-517b3cc2c2d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/LS/500 RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1c2485f-a3db-4e59-b188-9e43718bbab7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9272ce6-d7ae-46ac-b30a-a569d2888d5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/LS/500h RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1061690-9986-4d5b-add4-d196e04b564c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed8a03ab-76e4-49aa-a5f9-f423770821dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/LX/570 Two Row-Three Row</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff6b54d3-1e0e-4f18-85b7-1bf68e1f6157</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e98a2873-5899-4679-88b3-332896c0ea2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/NX/300 FWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3037e293-8d13-493f-a84a-53e59f6c5b5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cef3f4d9-34ba-42e4-ac07-8bbce25b8b11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/NX/300h-FSport FWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f6a15c1-ba20-4d52-8172-6e276ab77e21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a3d1148-c6e8-4f9d-9774-410f287992a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/NX/300LuxuryFWD-AWD-hAWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>713ccfe9-9900-44e8-9b69-b17e4c09fdfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d323a713-0bae-47db-9163-c12ff830288d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RC/300 F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8cb22f-949a-4bb1-9d58-fe9fded008cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bc4abac-2529-47a0-b95f-94a4d9d84df7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RC/300 RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24c1fd0-2f7e-45d4-86a1-3fcd0de4ba9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bf9f02a-eed5-43c3-b842-70060642b34a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RC/350 RWD-AWD-F Sport RWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7d64100-2437-4987-8bcb-e447b2816734</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>727be3fa-da7f-47a2-8c0c-be5e0a0aae46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RC F-LC/RC F-LC 500-500h-Convertible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed676f7-da5a-465f-bd31-1f41936776ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a7d394b-3309-48fb-b919-ed199bd9b3fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RX/350 F Sport FWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc669ef-f9de-427f-b60e-65b7ffee0012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7d47e62-f7ad-48d5-8b67-74eec5ec9a90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RX/350 FWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c69f82e1-ff77-45c2-b468-fdedc37bb89e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbab4554-2ce8-4732-bee2-f34735b3d874</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RX/350L FWD-AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5809ea5f-dfd3-4efc-8633-17edf19c4a87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a63820b-d435-4852-9605-ed84c66d5a79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/RX/450h-F Sport-L AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d639f9d-5bb1-4db1-89df-2934df8eca35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57342944-fd7a-4704-b84e-044577d68af0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/UX/200FWD-FSport-Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc54fe4c-2911-44b1-b429-1a8e2b4d1156</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a043e4b-5211-4461-83a5-f7d1b8bf9a9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/report pages/UX/250hAWD-FSport-Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>472e9877-5e3c-4613-ade4-601863d63fbf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
