<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorSedans_ES_GS_GSF</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1258ca3c-331e-40fb-b9cf-85129e0b3fde</testSuiteGuid>
   <testCaseLink>
      <guid>ba0fa85c-def3-45c2-9ebe-68156d073395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 300h Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f48aa0cf-6a93-4abd-8cfe-b07a8dcd2cf8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49db818b-b151-481d-be0e-970a53ca61d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 300h Ultra Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2737caf-47d3-490f-94a1-c4a8fe4d0176</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c96f76e7-e780-487b-b7de-c92e644bc983</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 300h</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea14027c-6881-47da-8224-b4c0817115a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbb356e4-4719-4580-8d93-7edf81bd6de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 350 F Sport</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6873e96d-7730-4733-bd8a-96de7a6ff620</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10bcec05-4a66-463c-be61-80e3991d22cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 350 Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>957fab84-7a27-4799-9c2e-d1dfd046114d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35035213-f184-4733-9c79-1ad62edaca57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 350 Ultra Luxury</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ad3032-e5c7-479d-9eea-da627364be8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43840472-66b0-43cc-8651-819009ac3114</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - ES 350</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4014b1e-8919-4893-ae5f-ef8ef6668674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7a63a5f-b290-445f-bb2a-63d63fcd2e3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - GS 350 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>166bf792-5db6-4155-b560-e19d05481259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3a17f77-5408-4579-b66e-31fe30f80fa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - GS 350 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76d47607-3fe9-4865-b01e-d6a47c588fd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>507e54e8-30c7-436b-81e7-580450fcb38b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - GS 350 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31c5b2a5-a551-40ec-b7d5-f3c7979e0838</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a52f2976-fc6d-4b6f-9e9d-b14a4c541189</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - GS 350 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5afb9ef-c4a1-4202-8e0b-8f547653d8a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>481f6947-82b5-499a-96a3-51032fbf1fa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - GS F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb0026af-de0e-4b59-9531-983f463d3ac0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
