<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareSeries</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5245ba37-8f8d-4e63-84a0-29018e267986</testSuiteGuid>
   <testCaseLink>
      <guid>f752e53a-4a5d-4f92-8064-6309914d2815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - ES</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67e7d81b-e8e5-4670-bd8b-a4f470ca9b0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7ddc923-4827-4a73-b1c7-5e371eb72d4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - ESh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb0285b-6c9d-4600-bcd7-55b7dcd18208</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>535df5a2-2d98-4e31-9aef-96c5087859fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - GS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e457bef2-d7fa-4b70-bf9b-515cd5a6828e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6edbaef0-370c-4ab3-b18f-3cddf2bf6762</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - GX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7272fffa-7095-4d35-abec-6bb046ea5b92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>893f783a-9ee4-42aa-8d17-478ae9a400a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - IS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>027f828b-7d4a-4a78-b018-a46f87834934</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e340b7e1-4b88-404f-b3c6-b0060a8cf312</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - LC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c659efa9-0505-4702-ac57-d4ce5d08e6d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>191e0ad7-aa63-4b9f-804b-4efced6001cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - LS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6050b9-1e0b-4e4f-9588-063637e33113</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd4610ba-1401-4859-b305-06111229ba7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - LSh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac874b00-864a-47c3-bd12-34ee80752564</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29238c49-e99a-4266-91da-b91479c2813d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - LX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d066690-2417-4888-b27b-052ea08e15d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7584b121-ca0a-44ec-8f34-85ba93f74de2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - NX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>463e0b2d-2d74-44fa-9725-b4c974aff3e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34f62395-b2a6-4948-9da6-b15ed8cd92e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - NXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d3afb9f-6ff2-481a-a057-3933c3c843d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c2ead7b-f67c-44d6-bddb-9eeecf0b6781</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - RC F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18a0029e-e971-4d0f-9d2e-bb0dcd4cbe3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fa92790-2115-4d3f-b0ad-9e2a30dce6e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - RC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b85666d-1091-4631-86c3-df7ac682e2a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5352f3a-14be-4cbb-a4ba-4cece65c8e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - RX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f4915ee-b3da-4ba2-aba8-42cb3fb1cc8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ee0774c-4268-4c15-9f94-53efed420215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - RXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aaf7dbb-4360-4069-84a4-046a73fa6af8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d250cbf-4076-4d7f-9fd0-033e65d3de54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - UX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cf73fd9-396c-4713-8f24-34594cccbd4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0424b273-214c-4061-8f1e-d009b1ab8ef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/series pages - UXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ac50fd6-4afa-4560-bc45-5549e49e7221</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
