<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorSUVs_RX_UX</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a340ffd7-0361-453f-9cfb-a3c8a5dbf48e</testSuiteGuid>
   <testCaseLink>
      <guid>ac89bc99-2241-4739-b3dd-cd9e385b4687</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce0ef2b-ce78-48ee-8e93-404486bb473c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>122ce456-d0e3-49a8-8ea6-cf7ba3e24706</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28216b82-ad97-4b51-8f52-e3ad7f5f0d43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fcc3b28-ec12-4182-be47-8ec3483dcfd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f83c809b-56e6-43c2-b5b8-098b54ab1f01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95a96266-56bd-4643-8467-b8810f94f20b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3d29b21-2a91-43a6-8d0f-69e5184ea24b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d773b0b-6cb5-417a-86a8-f4e00b624c4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350L AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22872797-61d9-4cac-ba68-34e2ffa2017f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88b65ad2-bdae-49c8-b113-571b67fe1f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 350L FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b623cad8-8960-447c-9efe-01555151deed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>355bfde8-1c6d-4f8a-a11c-9336bac62087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 450h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8501eb93-1d39-4dda-b8cb-7777c88f632c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33c356ca-8e3c-4d52-a788-2db30e4be758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 450h F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea816a6-7359-4351-a67e-3907dac63390</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ce694e-0917-407e-95df-3acdad811472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RX 450hL AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e34a5eb2-c404-4034-a07e-4809cffd633f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6959f462-6ae4-4264-8598-4ac5c687cb29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 200 F Sport FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b731ab59-c192-4a19-adf2-216863e98dfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0db02237-1203-410b-ba94-44d9bd425f8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 200 FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cec3522b-e5d9-4402-aba5-1e7cf3823efd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a3ba5a-a10f-4395-baa9-539848679376</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 200 Luxury FWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0693f5c3-4a95-425b-9f9e-084c2dadce26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a42e8282-cb9c-4ded-8ebe-240d6590a0e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 250h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d70106f-bf9a-450c-87f5-140adc313d1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d917bf08-309a-464c-88a5-13177e22f791</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 250h F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f28a1377-5963-4f65-99f8-dd9cd9ab0c4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b5d45f-6ed3-42a8-addb-62ae9d1c5e62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - UX 250h Luxury AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da4d318-2374-48f0-b544-ee31d77b42b4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
