<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorCoupes_RC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b6c5fa0d-dcc1-47e5-b671-5c6c23f9ae51</testSuiteGuid>
   <testCaseLink>
      <guid>bc10a536-2871-459a-8959-3ce8993666f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 300 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f79d84a7-adbe-4331-bc5d-dae9252489f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5085817b-2828-4836-8fd9-c9e83725a9fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 300 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7259a8-dc4b-4cac-a45e-5c29019a9e31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8be451cf-0ff0-45de-a42b-1bbdb1c19e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 300 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1895339-1c02-4a68-aec0-ee6c65edf594</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1259dba-4c47-42c0-803e-8c7e566a70a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 300 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4b9f8d-79f4-47ab-941b-0b90f9df66e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e28bd254-8cd4-447f-b1aa-884eb4d73c87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 350 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8031beb5-a6a4-41e9-8287-6f9ba667110a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0be0a491-61ba-4b17-88a9-351dfedc7cf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 350 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13b19aff-add5-45f8-bf11-371cbd1be9ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>132b1c93-5d18-4b6a-9250-bcc4bea78f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 350 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45da6568-2970-4a26-bb47-e951657a0451</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f1314db-cf26-477b-8e2e-3da301219ced</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages - RC 350 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c288feb2-c54c-497e-bc2b-2dcbead81c7c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
