<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorSedans_IS_LS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3fdb197b-e754-4a8d-8d7e-604ac948fb3f</testSuiteGuid>
   <testCaseLink>
      <guid>7810f127-118e-4252-9cac-e22b830bafc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/300 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca36cca-5c92-42c0-aa5b-852e135a79d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbac9019-2aca-425a-bc2d-7d06bd3f6b4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/300 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14101a45-17da-4ad8-9293-6bf4c666eaa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02c99a31-fa1d-4d4f-b3a9-293ad34c9e21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/300 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9880ab3-96fe-4b65-81d7-2c5558dc3df6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45cf87d0-01e9-402d-9a2d-6a27c9b5dff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/300 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b169bc8-5e30-4abc-a21f-ce85215a867e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95f45edc-dfbb-4988-aa10-6d9a1f8b3792</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/350 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c9bd091-a4b1-40e3-8f89-5549ae367067</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>034a130f-c84b-4787-ad05-cec5a9636cf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/350 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40d1504f-793a-4f92-8da7-a7096b91a40c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f6d22a2-d74f-4023-9dd7-58922697ae97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/350 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61422593-1141-4bd8-8a1f-f6ddbfa3182c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30c9c3ab-bdea-4d81-9864-8d636dd58f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/IS/350 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>734a6576-7c40-421d-a0ed-9b531eba23c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0f0f25-1baa-4d3a-829f-e8e85033810a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500 AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc42f05-1308-48a2-96fc-2517b88cd13a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e39a134-df7b-451e-a7f1-9b459e4c09b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500 F Sport AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb608a5-1e15-4129-9d37-fecffb7fb0eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5cd6cc7-3994-491f-a74e-583c4f486490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500 F Sport RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>802dd69e-8b18-4fb1-b225-428bf4fa0350</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1354cda-a809-40d8-960c-43fec30f85da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500 RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01976146-0081-4f5a-8daf-b3aa9859fcae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d85fe739-15d4-428d-ad7c-1f1ac432d71f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500h AWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29ae8646-5c4a-4818-97c8-d67273fed5b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0ec5fee-dc86-4302-9498-ee40c8ba68f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/sedans/LS/500h RWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098c48f2-0910-4a89-be7c-2fffe2d439f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
