<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompareCompetitorCoupes_LC_RCF</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3c5815c9-23d1-4c5c-96dd-b4d57c24f74f</testSuiteGuid>
   <testCaseLink>
      <guid>780c9181-4916-43e4-8024-d2481456b537</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/coupes/LC/500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cde3ba7-3538-440f-bbd0-866016febc44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34dca0c9-4a7e-4d97-9ad6-6912b1d5ef76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/coupes/LC/500h</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3df7066-c19f-4ff7-a125-5d1adba0beeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d8d2389-d04a-4847-9243-e9bc0cf0b586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/coupes/LC/500 Convertible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68717c11-6ee4-44fc-b9ef-ed447b4bd3c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a6a9964-ef42-432f-bd29-4d40b941f210</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/coupes/RC F/RC F Track Edition</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e62c00e5-4259-4432-b882-59a6aea3570f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>586c0ce3-a416-4ce6-95d1-4fc8affef634</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/Compare/competitor pages/coupes/RC F/RC F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e4cddf8-5225-49c5-91fa-b2da15476463</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
