<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HomePage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5e1a4c68-aa12-4240-9d93-ca55c29f9cbe</testSuiteGuid>
   <testCaseLink>
      <guid>af40e3d4-a28f-4845-8002-d452e8cb9cb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/correct prices in vehicle selector</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cb84dbb-cebd-453d-a86a-a6937b9f3791</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40940761-802e-44ac-a0de-9bf0c0b3e33e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/default</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c560579-764b-48b6-8910-2838ad19c238</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81b8fbb2-05c3-4703-8b6e-ed2cea762268</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - ES</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24b62d47-e289-41c7-81da-bfbed2be5e6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7cdf66da-2195-4c6e-988b-3ecbe0a94ab9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - GS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52fc752-0c50-4d65-b517-91f5e6302240</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87c6b53e-142c-48a5-b923-ce217d3ed6fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - GX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ff6e0c-e3bc-4ca5-b2af-45fd13b9351a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6db1778-e33c-4fbf-9c69-1e29dbfebe91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - IS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6c97e25-8534-42a6-899b-4916d5a89bd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c827974-64e9-496e-b5e4-6be2556a65b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - LC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>039d0e2b-cf5c-48e6-a330-b6b9f33fc4e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7787c6a-8b21-4da7-93e3-36c2dfb74d6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - LS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9300757d-f42e-410e-9da9-16ea9e0afc3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b0c96d6-1c5a-441b-b7db-02f971277231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - LX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc79d468-e0eb-45d8-8ab0-8f68927dcede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48569489-9fff-4ed2-bf38-7f9d86ac2e32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - NX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>047d2f2b-b643-402d-b9ee-8d35877b416c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ab04151-160f-4c76-9c5e-50813d3fb14f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - RC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a6a0a8f-3f2f-49f2-a18b-2d703053b33a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b212090-9f82-4d1e-8d34-de2ba447832a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - RX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f61dd18-6bdc-435c-9cfe-6805dc07a99a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f23b7c76-6706-4c35-acf4-cf2ee662ed8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PMOI - UX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf5752ca-5edc-4361-96f3-aaee991c6676</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d449fb92-e162-467c-bd77-7bfdfe315426</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - ES</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbb1736e-45e6-4d3e-b6b9-8970dca3414a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65868d12-de45-42fd-a510-e37bda298543</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - GS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b06ad25-afc0-49e9-b33d-5828e21c0fb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b03daf85-f1d6-45d8-809e-8d6118e660d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - GX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d802b4-2aca-4ff8-972d-7ef408d008d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e1b18be-6e20-4805-83d2-5ce3a704f440</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - IS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df63ff09-f9c2-4d40-9f2f-d75cc2f29593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9ac13e7-6931-4c71-9a06-b7671e1e29b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - LC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0788d14-b908-4444-b4d2-b126fe07a211</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3f95c7d-c694-4eac-979e-380b1aa76760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - LS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e156229e-10af-4d5d-9005-3131aab057d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1cd29e8a-933a-45e8-9f60-18d53c403a2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - LX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dc36006-82d0-44e2-b8a2-bbf19a774580</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3756f6db-876c-4527-893f-4cecaa59f8a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - NX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>122981df-d8c9-4017-8464-d893b9b34d88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fa502c0-7dfd-44d2-9353-da8a25a4a312</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - RC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68064e47-7ba8-4deb-8475-593c24aeff31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87f0e969-b41e-4f75-99fc-a587f8d07d40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/HomePage/PO - RX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>325d69f0-408f-4e3f-8670-53c4de218738</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
