<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ModelSpecs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9241459e-16da-475b-84af-d15421924c0e</testSuiteGuid>
   <testCaseLink>
      <guid>fc472b5c-ed9d-4bf0-bf2d-450e32fe1e34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/ES</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd1a87f-84f3-41c0-8d33-67f872649f62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fac5c72f-4c6b-41bd-971a-cb2fb80644c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/ESh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b619d45-8595-4104-af8a-abe6ee742b4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>260156e3-cbf4-476b-920e-bf1ea69278c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/GS F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35beb7a-8b0b-4af1-9ea6-3a2d5e3d7580</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcd44637-6d30-49c6-91e4-06307bd389d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/GS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88350d3-d3de-4991-9857-9d49cf963d43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05c66de1-def2-4c5e-a904-3e92e9f89d6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/GX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>116728f1-78d9-4987-bb22-117e5b5a780d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79481853-bc9d-41a3-8282-3bdef44fc063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/IS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77ddb92c-4388-43b3-84a5-ad35d4831ab9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ebd6ca0-567c-41cb-a28a-df5c28f8593a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/LS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d88909-ec40-45f5-a9a1-720c19ad8879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b43aa4a-7586-4f26-8979-81e84bdc1d08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/LSh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17bd2731-7c5d-400a-a384-0a86613d9eb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c574299-dbda-4a8d-90d6-527e9997ca3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/LX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c51848-9fb2-4a5b-9c75-58a1ab78fdc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>103b32b4-5141-4426-ad2f-21477593fb68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/NX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a816ee85-1337-430e-9cb7-df0b08349aef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>858975eb-493f-448b-af58-3f5fb2015761</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/NXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4bcb467-54de-4dc2-8614-d14bb944fee2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9d6454f-dfcb-4084-a64e-1274e4283560</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/RC F</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>819ee839-a6ba-4117-9dff-5053d24f4db5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79eb61b7-7b3e-45d3-845a-078b28046637</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/RC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fefac9a3-c881-4555-84fc-24cf1a7dd9ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f3069ac-227f-4143-bab7-0c83169da8b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/RX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07e78d6b-95bd-4e9e-8644-82daf81ce871</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8739de2c-fe32-40fb-b5f8-3bbad843fd95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/RXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8180a679-1c8f-468c-aad7-389e9e21c0f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6153ec3-bd52-41bc-b479-67d09c0d85a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/UX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e892bbb-9ab2-44b4-aade-98ca86210d11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03ee7a8d-69a3-4ebc-976e-37cf804e5475</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lexus.com/MSRP/ModelSpecs/UXh</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c1ce3e-f73a-40fa-8c0f-9699c5c6853b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
