<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BYL link image</name>
   <tag></tag>
   <elementGuidId>6da73947-cbcf-4a61-bad4-dc7271244c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src, 'icons/Lexus-byl')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>#/build-your-lexus/#!/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>icons/Lexus-byl</value>
   </webElementProperties>
</WebElementEntity>
