<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NXh</name>
   <tag></tag>
   <elementGuidId>6424f7c8-f487-4e06-8848-b444ef5ede87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleSelector div[class*=&quot;selected&quot;] img[alt=&quot;NX Hybrid&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@data-category, 'Suvs') and @data-model = 'NXh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Suvs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model</name>
      <type>Main</type>
      <value>NXh</value>
   </webElementProperties>
</WebElementEntity>
