<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RX</name>
   <tag></tag>
   <elementGuidId>a8c87e5c-cf24-4bff-b421-a1cc1c122433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleSelector div[class*=&quot;selected&quot;] img[src*=&quot;rx&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@data-category, 'Suvs') and @data-model = 'RX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Suvs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model</name>
      <type>Main</type>
      <value>RX</value>
   </webElementProperties>
</WebElementEntity>
